### ISSUE TITLE
Print helpful message when dispatching `undefined`

### ISSUE THREAD

**Issue by ratson** [reactjs/react-redux#231]
I encounter this problem because I was careless not returning anything from `connect`.
Not sure this should be resolved in `react-redux` or `redux`.
Here is the pseudocode to see the meaningless `console` error.

```javascript
import {connect} from 'react-redux'

connect(() => {}, {
  increase() { /* forget to return */ }
})(SomeComponent)
```

**Comment by gaearon** [comment]
What message do you currently get? It should say about action being a plain object.

**Comment by ratson** [comment]
I have created a demo for the problem, you could check it out by the following commands.
```bash
git clone https://github.com/ratson/demo-redux-undefined-action
cd demo-redux-undefined-action/examples/basic
npm install
npm start
```
Then `open http://localhost:8080` and click the `increase` button, you should the errors in browser console.

**Comment by alex-deas** [comment]
So you're currently getting `TypeError: Action is undefined` with a Stack Trace. Which it is as you're passing in a function with no body as part of state to `connect(state)(Home)`, thus not passing in an `action` which causes the `TypeError`. What error would you expect here? I'm struggling to see what error you'd want to see.

**Comment by ratson** [comment]
I don't get `TypeError: Action is undefined` in console.

Instead I have this following printed in console.
```
TypeError: Cannot read property 'type' of undefined
```
which points to the line
```
if (typeof action.type === 'undefined') {
```

I would expect the `typeof action` is checked and give out a more meaningful message on how to fix the problem.

**Comment by timdorr** [comment]
This may have been before Redux switched to lodash. [There is a check in place](https://github.com/reactjs/redux/blob/master/src/createStore.js#L150-L155) to prevent the more opaque error you were getting.
