### ISSUE TITLE
Flow types?

### ISSUE THREAD

**Issue by tmcw** [reactjs/react-redux#264]
Is there any way to enforce types for the action creators in `mapDispatchToProps`, whether in react-redux core or a contrib? Would it be possible to annotate propTypes to enforce function signatures, or add an interface? I'm working on a large application that benefitted a lot from Flow annotations on action creators, and no longer can because of the dispatch/props disconnect.

**Comment by gaearon** [comment]
I don't know enough about Flow to answer this. Your best bet is to investigate this and report the results :-)

**Comment by tmcw** [comment]
Done a bit of research and seeing two options:

* If react-redux is to be type-annotated, it's blocked by [default support in type destructuring](https://github.com/facebook/flow/issues/183) because of [connectL43](https://github.com/rackt/react-redux/blob/9c50ae13b84a9fe1702190a94bf900e4ffa32a26/src/components/connect.js#L43)
* For an external declaration to work, I think the upstream blocker is [Object type spread support](https://github.com/facebook/flow/issues/1326).

I'm looking into Object spread support to see if it's something I could contribute, but, y'know, OCaml has a bit of a learning curve :)

**Comment by nmn** [comment]
perhaps connected: #389

**Comment by kristian-puccio** [comment]
If you haven't seen this is worth a look.
http://makeitopen.com/tutorials/building-the-f8-app/testing/

Also there are some flow definitions here:
https://github.com/flowtype/flow-typed

**Comment by vicapow** [comment]
@timdorr could you leave a comment why the task was closed? If it's a duplicate / resolved could you link to the related ticket or if it's a "wont fix" could you describe why?

**Comment by gaearon** [comment]
Yea this was a bit odd. We definitely want Flow types for this. I just don't know enough about Flow at this point to say what next steps should be. There is already a PR to flowtyped, right?

**Comment by gaearon** [comment]
@timdorr For future reference, please comment with a reason for closing so we know what the intention was :wink:

**Comment by timdorr** [comment]
Sorry, I didn't put a link to the appropriate PR. Efforts are ongoing over there: #389 (and reactjs/redux#1887 is related too)

**Comment by gaearon** [comment]
Thanks!
