### ISSUE TITLE
Getting warning in browser console

### ISSUE THREAD

**Issue by topgun743** [reactjs/react-redux#287]
I am getting following unknown warning in my Firefox browser console. This only occurs if I am using a component on page that is making use of react-redux. It does not occur on other pages using simple React components.

```getDefaultProps is only used on classic React.createClass definitions. Use a static property named defaultProps instead```

Whats this? Can anybody please tell?

**Comment by gaearon** [comment]
It doesn’t have anything to do with React Redux. 

The component that happens to use React Redux *also* happens to define `getDefaultProps` on an ES6 component class. React warns that this is not a supported pattern anymore:

```js
class MyStuff extends Component {
  getDefaultProps() {
    return { lol: true }
  }

  // ...

}
```

This will not work. You need to convert this code (likely copy-pasted from `createClass` style component) to

```js
class MyStuff extends Component {

  // ...

}
MyStuff.defaultProps = { lol: true }
```

**Comment by topgun743** [comment]
OK, but could not understand whats the difference between the above two snippets. They are almost doing the same thing. Then why React warns? Is it concern with some syntactic sugar?

**Comment by FredyC** [comment]
There is some explanation in this article: http://www.newmediacampaigns.com/blog/refactoring-react-components-to-es6-classes (Step 1)

**Comment by gaearon** [comment]
They seem to be doing the same thing but one is supported way of declaring default props and another is the unsupported one. :-)

**Comment by topgun743** [comment]
Nice link by @FredyC Thanks. Some good insight into the ever evolving complexities of ES*

**Comment by gaearon** [comment]
This is not about ES semantics. Props are a feature of React. getDefaultProps() was part of React createClass() API but they decided that there is no need for a method it a property can suffice so when you *don’t* use createClass(), you use defaultProps instead.

**Comment by topgun743** [comment]
Appreciate. Thanks for correcting my misunderstanding :)
