### ISSUE TITLE
if state has single key, mapStateToProps hasn't whole state as parameter

### ISSUE THREAD

**Issue by mananvpanchal** [reactjs/react-redux#288]
Hello,

If my state tree looks something like `{ text: ""}`. In this case, mapStateToProps will has only `text` as parameter. But, if my state tree looks like `{ text: "", name: ""}` and now I have two reducers and mapStateToProps will has whole state tree as parameter. If I need whole state tree in mapStateToProps when there is only one key in state, I need to use combineReducer. Is this intentionally or for some other reason?. Please fill free to close this if this is discussed already and give me that link.

Thanks

**Comment by gaearon** [comment]
Unfortunately I don’t quite understand the question.

`mapStateToProps()` receives whatever the shape of your state is. So if it is `{ text, name }`, whether you use `combineReducers()` or write root reducer by hand, you will get `{ text, name }` there.

We suggest using `combineReducers()` in larger apps but it doesn’t make sense to use it when you only pass a single key. The whole point of `combineReducers()` is to combine *multiple* reducers by their keys. If you don’t have multiple reducers yet, don’t worry about it.
