### ISSUE TITLE
Not sure how to do propTypes validation correctly

### ISSUE THREAD

**Issue by phorust** [reactjs/react-redux#302]
On page load the following code gives me warnings in the console about `propType onHighlight is invalid; it must be a function, usually from React.PropTypes`.
```
const mapDispatchToProps = dispatch => {
  return {
    onHighlight: _ => { ... }
    }
  };
}

const mapStateToProps = state => {
  return { highlights: state.articleReducers.highlights };
}

const Article = React.createClass({
  ...
  propTypes: {
    article: React.PropTypes.object.isRequired,
    topics: React.PropTypes.array.isRequired,
    onHighlight: React.PropTypes.function,
    highlights: React.PropTypes.array
  }
  ...
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Article);
```
Later though, after dispatches and state changes, there's no complaining. If I take `onHighlight` and `highlights` out of propTypes my eslint/jscs config complains (and so do I to some extent). What's the right way to do this?

**Comment by gaearon** [comment]
This is unrelated to React Redux.
There is no `React.PropTypes.function`, only `React.PropTypes.func`.
This might be related to `function` being a reserved word in older browsers.
