### ISSUE TITLE
How to initialize component

### ISSUE THREAD

**Issue by mananvpanchal** [reactjs/react-redux#307]
Hello,

I created smart component using "connect" like below. 

```JS
let Home = ({ text }) => {
	return (
		<div>{text}</div>
	);
};
Home = connect(
	(state) => {
		return {
			text: state.text
		};
	},
	null
)(Home);
export default Home;
```

Now, where should I write my ajax call to get server data ("text" in this case) to initialize my component?

**Comment by iamakulov** [comment]
I’d create an async action creator:

```js
export function loadText(loader) {
  return dispatch => {
    dispatch({ type: 'LOAD_TEXT_STARTED' });

    loader()
      .then(data => {
        dispatch({ type: 'LOAD_TEXT_SUCCEEDED', text: data.text })
      })
      .catch(error => {
        dispatch({ type: 'LOAD_TEXT_FAILED', error })
      });
  }
}
```

And then simply dispatch the action passing the method that loads the data:

```js
import { loadText } from './reducers/loadText';

const dataLoader = () => fetch('/api/data')
  .then(response => response.json());

store.dispatch(loadText(dataLoader));
```

The dispatching can take place in any appropriate part of your app. If the app is small, I’d do it right where the store is created.

Additionally, you’ll need to create a reducer that handles `LOAD_TEXT_SUCCEEDED` actions and updates the store with the new text.

**Comment by gaearon** [comment]
Also feel free to check out https://github.com/reactjs/redux/tree/master/examples/async and other examples :wink:

**Comment by mananvpanchal** [comment]
@iamakulov  Thanks lot for your answer. I understood how to dispatch for initial loading.

> The dispatching can take place in any appropriate part of your app. If the app is small, I’d do it right where the store is created.

Now, my application wouldn't be small. I have scenario where I need to initialize a component with fresh data whenever it gets called. 

Now, I have three case where my component gets called.

1). When I simply click on link to go to "home". `<Link to="/home"/>`

2). When I do dynamic routing to "home". `store.dispatch(push("/home");`

3). When user sometimes directly change URL in brwoser and hit "Enter". `http://localhost:8080/myapp/home`

> The dispatching can take place in any appropriate part of your app

So, I actually don't know what is appropriate part of my app where I can handle all three scenarios?

Thanks again
Manan V. Panchal

**Comment by iamakulov** [comment]
@mananvpanchal, do you have any action that is triggered when a user switches to a route? If so, I’d create a middleware that listens for such switch actions, checks if the switch is performed to `/home`, and dispatches an additional `loadText` async action if it is. This way is quite verbose (as the new middleware is created), but I don’t know the more elegant one.

**Comment by mananvpanchal** [comment]
@iamakulov Thank you very much. I will try to implement triggering actions on route switching. Need to research on route switching. That way I can handle all three scenarios. But, need to research first that how can I know that "route is going to switch now".

**Comment by mananvpanchal** [comment]
@iamakulov I found something like this.

`<Route path="home" component={Home} onEnter={loadHome}/>`

and I write "loadHome" like this

`const loadHome = () => {
	store.dispatch({type: "LOAD_HOME"});
};`

Using this, I can handle all that three scenario.

Thanks.
