### ISSUE TITLE
Improve `mapStateToProps` invariant validation error message

### ISSUE THREAD

**Issue by pke** [reactjs/react-redux#309]
During refactoring of my stores I more than once hit an invariant violation like this:

```
Uncaught Invariant Violation: `mapStateToProps` must return an object. Instead received "A string".
Uncaught Invariant Violation: `mapStateToProps` must return an object. Instead received .
```

It would be nice of the name of the connected component would also be part of the error message

The latter error message above is from an "undefined" return I guess, so it should print that in the error message:
`Uncaught Invariant Violation: 'ComponentName mapStateToProps' must return an object. Instead received undefined`

**Comment by gaearon** [comment]
Totally. Those messages were never considered carefully. Please feel free to work on a PR to make them user-friendly!

**Comment by BerkeleyTrue** [comment]
:+1:

**Comment by moaazsidat** [comment]
Hey @BerkeleyTrue, @gaearon, is anyone working on this currently? 
Would love to take a look and see if I can work on this if no one is. :smiley: 
Cheers!

**Comment by pke** [comment]
No time at the moment. Feel free to create a PR
