### ISSUE TITLE
Property binding to dynamically injected sub-components

### ISSUE THREAD

**Issue by Dreculah** [reactjs/react-redux#316]
Hi,

I am loving react-redux, thank you!

We have a requirement to dynamically inject sub-components into a component after it has rendered.

However, the injected dynamic sub-component properties, although specified in mapStateToProps(), do not update in render(), even though I've verified they are updated in the state and are updated in the component's this.props.

If you move ```javascript <span>prop in getChildren(): {me.props.getChildrenProperty}</span> ``` into the render method, getChildrenProperty is updated in the UI when its button is pushed.

So, this.props.getChildrenProperty in ProblemChild:
- is populated from the Redux store and it renders with the correct value after its injected
- is updated with its new value from the redux store
- this update triggers render()
- However, the new property is not displayed even though this.props.getChildrenProperty has new value

Here is a simple example:

```javascript
import React from 'react';

import {connect} from 'react-redux';
import { bindActionCreators } from 'redux';
import * as actionCreators from '../actionCreators/ProblemChildActionCreator.js';

function mapStateToProps(state) {
    return {
        renderProperty     : state.getIn(['uiState', 'renderProperty']),
        getChildrenProperty : state.getIn(['uiState', 'getChildrenProperty'])
    }
}
function mapDispatchToProps(dispatch) {
    return {
        actions: bindActionCreators(actionCreators, dispatch)
    };
}

@connect(mapStateToProps, mapDispatchToProps)
export default class ProblemChild extends React.Component {
    constructor() {
        super();
        console.log('! constructor, value of props: ', this.props);
        this.state = {children: null};
    }
    /**
     * Add children in setDynamicChildren() versus within render()
     */
    componentDidMount() {
        this.setDynamicChildren();
    }
    setDynamicChildren() {
        this.setState({
            children: this.getChildren()
        });
    }
    getChildren() {
        var me = this;
        console.log('render() - value of domain')
        return (
            <div>
                <br/>
                <button style={{marginBottom: '10px'}}
                        onClick={me._handleGetChildrenAction.bind(me)} >UI State Change Action for prop in getChildren()</button>
                <br/>
                <span>prop in getChildren(): {me.props.getChildrenProperty}</span>
            </div>
        )
    }
    render() {
        var me = this;
        return (
            <div >
                <button style={{marginBottom: '10px'}}
                        onClick={me._handleRenderAction.bind(me)} > UI State Change Action for prop in render()</button>
                <br/>
                <span>prop in render(): <b>{me.props.renderProperty}</b></span>
                <br/>
                {this.state.children} <br/>
            </div>
        )
    }
    _handleRenderAction() {
        var me = this;
        me.props.actions.actionForPropInsideRender('bloodBag!');
    }
    _handleGetChildrenAction() {
        var me = this;
        me.props.actions.actionForPropInsideGetChildren('Baka !!!');
    }
}
```

**Comment by madmax983** [comment]
Here is a jsfiddle demonstrating the issue: https://jsfiddle.net/fL8ab2hx/65/

**Comment by gaearon** [comment]
The problem is that `this.state.children` depends on the current props (calculated from the store), but are not re-generated when those props change. This is a very problematic pattern and I strongly suggest you to find a way to model this problem with React top-down data flow without keeping `children` in `state`.

However, as a temporary measure, you can change `getChildren()` to accept `props` as an argument. This is better than reading from `this.props` because ideally you want to be able to update `this.state.children` **before the new props have been received** so `componentWillReceiveProps(nextProps)` is your best chance, at which point `this.props` is not up to date yet. Additionally, instead of initializing `this.state.children` in `componentDidMount`, I would advise you to initialize `this.state.children` right in the constructor so they are ready by the time component mounts.

See the updated fiddle that works: https://jsfiddle.net/mxb505pw/1/

Relevant code:

```js
class ProblemChild extends React.Component {
constructor(props) {
        super(props);
        this._handleGetChildrenAction = this._handleGetChildrenAction.bind(this);
        this._handleRenderAction = this._handleRenderAction.bind(this);
        this.state = {
            children: this.getChildren(props)
        };
    }
    componentWillReceiveProps(nextProps) {
        // Can use shallowEquals() helper here to avoid comparing every prop
        if (this.props.getChildrenProperty !== nextProps.getChildrenProperty) {
            this.setState({
                children: this.getChildren(nextProps)
            });
        }
    }
    getChildren(props) {
        return (
            <div>
                <br/>
                <button style={{marginBottom: '10px'}}
                        onClick={this._handleGetChildrenAction} >UI State Change Action for prop in getChildren()</button>
                <br/>
                <span>prop in getChildren(): <b>{props.getChildrenProperty}</b></span>
            </div>
        )
    }
  render() {
    return (
        <div>
            <button style={{marginBottom: '10px'}}
                    onClick={this._handleRenderAction} > UI State Change Action for prop in render()</button>
            <br/>
            <span>prop in render(): <b>{this.props.renderProperty}</b></span>
            <br/>
            {this.state.children} <br/>
        </div>
    )
  }
  _handleRenderAction() {
        store.dispatch(actionForPropInsideRender('One Fish!'));
    }
    _handleGetChildrenAction() {
        store.dispatch(actionForPropInsideGetChildren('Two Fish!'));
    }
}
```

Hope this helps!

**Comment by Dreculah** [comment]
Thanks, Dan.

This is a simplified version of our real world problem, which that we need to dynamically inject children and bind them to redux AFTER the first mount/render cycle. Calling getChildren() from the constructor won't satisfy the requirement.

If we're not to keep the (dynamic) children in state, how best might we cause a re-render after a 'binding run' of redux after the children are added?
