### ISSUE TITLE
Act on actions inside a component.

### ISSUE THREAD

**Issue by mahadazad** [reactjs/react-redux#318]
Hello,
I am creating an app which is based on canvas. I am using react-redux. I have some color pickers, text size components, etc. What I want to achieve is; e.g. user changes the color in the picker an action fires which updates the UI and also the canvas component can listen to it and act accordingly. I don't want to pass handlers explicitly to the canvas component, that would be messy. I am really confused how to handle this situation in a neat way.

**Comment by gaearon** [comment]
Please see https://github.com/reactjs/react-redux/issues/251 and the issues linked from there. If you have a component that cares about specific actions and can’t derive the UI from the current state, your best bet is a custom middleware that emits all actions to some kind of global pubsub system. We don’t provide this but it should be possible to create with an event emitter. If you have issues with this please create a question on StackOverflow with the code that you tried, leave a link here, and I’ll try my best to reply.
