### ISSUE TITLE
Support React 15.0.0-rc.1 and next 15.* releases

### ISSUE THREAD

**Issue by slorber** [reactjs/react-redux#319]
Hi,

Is it possible to support the new release of React? 
I guess the code should be compatible

Thanks

**Comment by FedericoKCL** [comment]
I just asked a question about this:
 [http://stackoverflow.com/questions/35890730/react-15-not-compatible-with-react-redux?noredirect=1#comment59468510_35890730](url). 
It would be great to know if it's possible to support it. :)

**Comment by deep-c** [comment]
+1

**Comment by gaearon** [comment]
Done in 4.4.1 via #317.
For the future reference, you can use `npm@3.x` which only warns but doesn’t enforce peer dependencies.

**Comment by slorber** [comment]
thanks! will try that next time
