### ISSUE TITLE
mapStateToProps and mapDispatchToProps looks to me like a viewModel

### ISSUE THREAD

**Issue by vladap** [reactjs/react-redux#321]
ViewModel maps model (state) into props for rendering and can include commands. It might be benefitial to keep established terminology. It might as well simplify API into a single function. I assume that viewModels are small hence the separation into two function is a boilerplate which could be reduced:

const viewModel = (state, dispatch) {
  todos: state.todos,
  onTodoClick: id => dispatch({...})
}

const TodoList = connect(viewModel)(TodoList)

**Comment by Ciantic** [comment]
I don't think they can be combined. 

Would you remap the actions to their same properties each time the state changes also?

mapStateToProps and mapDispatchToProps are separate for a good reason, consider the performance: mapStateToProps is actually run several times when state changes, and mapDispatchToProps once (or way fewer anyway than mapStateToProps) it doesn't depend on the state.

I won't start to fight about naming however.

**Comment by gaearon** [comment]
Yeah, the separation exists for performance reasons:

>mapStateToProps and mapDispatchToProps are separate for a good reason, consider the performance: mapStateToProps is actually run several times when state changes, and mapDispatchToProps once (or way fewer anyway than mapStateToProps) it doesn't depend on the state.

Please see #1 for a history of how this API came to be. The single function approach was considered before and rejected.

**Comment by vladap** [comment]
Makes sense. Naming seems fine to me then.
