### ISSUE TITLE
`haveOwnPropsChanged` is set to be true, although the props is unchanged

### ISSUE THREAD

**Issue by haohcraft** [reactjs/react-redux#326]
In some cases, we would like to pass in some function as a prop to the child, but this will result in re-rendering the child even though the function passed in is the same. I think this is because `/utils/shallowEqual.js` can not handle the case where the two are functions.

Check [this](http://stackoverflow.com/questions/12216540/how-to-test-for-equality-of-functions-in-javascript)

**Comment by gaearon** [comment]
The link to the SO question doesn’t seem to be very relevant. The question is about comparing two different functions, so their identities differ, but comparing the same function will return `true`.

Now, *if you pass different function identities* as props, yes, they will differ. For example something like `onClick={() => this.handleClick()}` will be a different function every time. In this case the solution is to make sure you always pass the same function, e.g. `onClick={this.handleClick}`.

It is hard to say anything more without seeing the code. But I believe that comparison is correct so I am closing. If you are sure it’s not please add your code, or better, submit a PR with a failing test that we can discuss.

Cheers!

**Comment by haohcraft** [comment]
You are right. Thanks for explaining.
