### ISSUE TITLE
this.props. "ActionCreator" failed: Cannot read property "ActionCreator" of undefined

### ISSUE THREAD

**Issue by skywalkerlucas** [reactjs/react-redux#328]
I am building and testing my redux project, but I encounter a problem which I cannot solve:

I have a Container - PostList (which is used to show posts), and in the PostList I have a Component: SimplePage, which is to show the pagination info of the posts list.

And in the SimplePage component, I can click on the page number and it will Dispatch a Action that is to load the posts list of that specific page. I pass in a function, "jumpToPage()", from PostList into the SimplePage for it to dispatch the action.

The code is as below:

PostList:

```
import React, { Component } from 'react'
import { load } from '../reducers/post'
import { connect } from 'react-redux'
import SimplePage from '../components/SimplePage'
import Explore from '../components/Explore'

class PostList extends Component {

  renderPost (item) {
    return (
      <div> {item.title} </div>
    )
  }

  jumpToPage (page_num) {
    console.log('hello, jumping page')
    this.props.load(page_num)
  }

  render() {

    const {loaded, pages, page, items, load} = this.props;

    return (
      <div>
        <h1><i>I am PostList</i></h1>
        <div>{loaded ? 'Loaded.' : 'Not Loaded Yet.' } </div>

        <div>{ items.map(this.renderPost)} </div>

        <SimplePage
          toPageFromParent = {this.jumpToPage}
          pages = {pages}
          page = {page} /> 

      </div>

    )
  }
}

function mapStateToProps(state, ownProps) {
  const {
    post: { loaded, pages, page, items },
  } = state

  return {
    loaded,
    pages,
    page,
    items,
  }
}

export default connect(mapStateToProps, {load})(PostList)
```

SimplePage:

```
import React, { Component } from 'react'
import Class from "classnames"
import {Range} from "immutable"

class simplePage extends Component {

  ToPage(event, page_num) {
    event.preventDefault();
    this.props.toPageFromParent(page_num);
  }

  render() {
    const { pages, page } = this.props;

    return (

      <div>
        <h1><i>I am Simple Page Component</i></h1>

        <nav>

          <ul className="pagination">

            <li className={Class({disabled: page == 0})}>
              <a href={"#"}
                onClick={event => this.ToPage(event, page - 1)}
                title={`To Previous Page`}>
                <span>&laquo;</span>
              </a>
            </li>
        ...
```

"load" is the action creator. Now when I click on the pagination, the "jumpToPage" is indeed executed, but I got the error ------ "Uncaught TypeError: Cannot read property 'load' of undefined".

I don't know why and I want help.

(

However, if I modify the code in PostList simply to:
```
 toPageFromParent = { load(page_num) }
```
It worked, but I think this is a ugly way to write the code, and I want to pass a function into the pagination component. Actually I learnt the above code style from the popular "erikras/react-redux-universal-hot-example" project, but here it does not work, and I do not know why. : (

As to my understanding, I already connect my ActionCreator ("load") the PostList. But in the "jumpToPage" function, it says  this.props.load(page_num) "Uncaught TypeError: Cannot read property 'load' of undefined".

)

Thanks!

**Comment by tgriesser** [comment]
> "load" is the action creator. Now when I click on the pagination, the "jumpToPage" is indeed executed, but I got the error ------ "Uncaught TypeError: Cannot read property 'load' of undefined".

The `jumpToPage` method is not auto-bound to the class, so when passed down into the `SimplePage` component, "this" is now the global object, so `this.props` is now undefined which causes the error `cannot read property 'load' of undefined`. You'll need to bind the method in the constructor:

```js
constructor() {
  super(...arguments)
  this.jumpToPage = this.jumpToPage.bind(this) 
}
```

or better, just use the `load` prop directly with:

```js
<SimplePage
  toPageFromParent = {this.props.load}
  pages = {pages}
  page = {page} /> 
```

**Comment by skywalkerlucas** [comment]
@tgriesser  Thanks a lot, seems it is a common JavaScript gotcha, and I have to learn more about JS :100:   ^_^.  Thank you a lot for your help!

**Comment by tgriesser** [comment]
Sure thing!
