### ISSUE TITLE
redux connecting old state

### ISSUE THREAD

**Issue by l2silver** [reactjs/react-redux#341]
Figured it out!

This is an issue I first posted on Stackoverflow, but I've since moved to this plugin.

I have an idea of whats happening here. The parent props.state is updating before the child state, and then the parent state doesn't update, even though the child has a new state that has not been updated yet. Is there anyway for me to get around this, or is there a react-redux solution?

--------
Original Post:

Kind of an interesting problem... 

I have a set of components that all use connect to get the state. These components are often children of each other, sometimes deeply nested children.

I want these components to shouldComponentUpdate only when the state changes, otherwise return false. The states are immutable Maps, and I use the is(...)to verify equality. The problem is that when the state changes, some of them see the change, and some of them appear to get an old state, and see no changes. If I complete another action that changes the state, they see the previous state, but not the most recent.

Any ideas? No middleware here.

*Edit... Code. There are a lot of pieces here so bear with me

```
function checkNewState(nextProps, instance){
    return !is(nextProps.state.reducerName, instance.props.state.reducerName)
}

const StupidParent = React.createClass({
    shouldComponentUpdate: function(nextProps){
        return checkNewState(nextProps, instance)
    },
    render: function(){
        return <p>{this.props.state.reducerName.get('name')}
            {this.props.replace(this)}
        </p>
    }
})

const StupidChild = React.createClass({
    shouldComponentUpdate: function(nextProps){
        return checkNewState(nextProps, instance);
    },
    render: function(){
        return <p onClick={changeStateNameProperty}>
            {this.props.state.reducerName.get('name')}
        </p>
    }
})

function mapStateToProps(state){
    return {state}
}

export const Parent = connect(mapStateToProps)(StupidParent);
export const Child = connect(mapStateToProps)(StupidChild);


<Parent replace={(parent)=>{
    return <Child />
}} />
```

**Comment by markerikson** [comment]
So, uh... if you figured it out, what was the issue and the fix?  Please don't leave us with another [DenverCoder9](https://xkcd.com/979/) situation :)

**Comment by l2silver** [comment]
Yeah sorry, basically the problem was my components weren't pure. I was doing this
```
<Parent replace={(parent)=>{
    return <Child>
<p>{parent.props.state.reducerName.get('name')}</p>
</Child>
}} />
```

Both components would update when the state would change, but the child state would not receive the new name from the parent component. So the order of change through me off. It went like this.

All components connected to the state immediately rerender, with the state being the only thing that changed. Then components receive changes from the parent.

**Comment by ChrisConti** [comment]
Could you please show your code after correction ? Thx
