### ISSUE TITLE
React-Native: Could not find "store" in either the context or props

### ISSUE THREAD

**Issue by miqmago** [reactjs/react-redux#344]
With this `index.android.js`:

```javascript
const store = createStore((state = {}, action) => state);

const MyComponent = () => (
    <Provider store={store}>
        <Text>Hello</Text>
    </Provider>
);

AppRegistry.registerComponent('MyComponent', () => connect()(MyComponent));
// Also tried this one with same result:
// AppRegistry.registerComponent('MyComponent', () => connect(state => state)(MyComponent));

```

I'm getting the red screen error in native device (tested in Android 5.0 and Android 4.3).

```bash
$ npm ls react
TestReact@0.0.1 /Volumes/DATA/TestReact
└── react@0.14.8 

$ npm ls react-native
TestReact@0.0.1 /Volumes/DATA/TestReact
└── react-native@0.22.2 
```

Am I doing something wrong or this is a redux with react-native issue?

**Comment by gaearon** [comment]
It should be the other way around. `<Provider>` should be around the root element that you render, or at least it should be around any element that uses a `connect()`ed component.

```js
const store = createStore((state = {}, action) => state);

const MyComponent = () => (
    <Text>Hello</Text>
);
MyComponent = connect()(MyComponent)

const Root = () => (
    <Provider store={store}>
        <MyComponent />
    </Provider>
)

AppRegistry.registerComponent('Root', () => Root);
```

**Comment by stnc** [comment]
> It should be the other way around. `<Provider>` should be around the root element that you render, or at least it should be around any element that uses a `connect()`ed component.
> 
> ```js
> const store = createStore((state = {}, action) => state);
> 
> const MyComponent = () => (
>   <Text>Hello</Text>
> );
> MyComponent = connect()(MyComponent)
> 
> const Root = () => (
>   <Provider store={store}>
>     <MyComponent />
>   </Provider>
> )
> 
> AppRegistry.registerComponent('Root', () => Root);
> ```

thx gaearon
