### ISSUE TITLE
Can I add className or style on Provider and Router

### ISSUE THREAD

**Issue by Tinple** [reactjs/react-redux#346]
Such as

```
ReactDOM.render(
  <Provider store={store} className="example">
    <Router history={history} className="example">...</Router>
  </Provider>,
  targetEl
)
```

But it seems not work

**Comment by markerikson** [comment]
Pretty sure the answer is "no".  As far as I know, both of those simply pass along their children, and do not directly render any HTML themselves.  Therefore, there is no tag to apply "className" or "style" to.

What are you trying to accomplish?

**Comment by gaearon** [comment]
You would need to add them to the actual root component that renders some DOM instead. Usually that would be the component corresponding to the top-level route.
