### ISSUE TITLE
React-Native

### ISSUE THREAD

**Issue by kennetpostigo** [reactjs/react-redux#350]
Hello,

I'm new to react-native and I've been attempting to integrate Redux into react-native.

I get an odd error and I'm not certain what it may be that is going wrong.

heres a link to [StackOverFlow](http://stackoverflow.com/questions/36586902/trouble-integrating-redux-into-react-native)

**Comment by markerikson** [comment]
Posting questions on SO is good, but don't think there was really a reason to open an issue just to point to the SO question.

Also note that you can often find help in the Reactiflux chat channels on Discord - invite link is at http://www.reactiflux.com.
