### ISSUE TITLE
Switch eslint off eslint-config-rackt

### ISSUE THREAD

**Issue by adrian-bobev** [reactjs/react-redux#353]
The link to the eslint configuration is wrong. I guessed it should be https://github.com/pwmckenna/eslint-config-rackt
because in the package.json it looks that this package is used.

**Comment by mxstbr** [comment]
I *think* the repo for that doesn't exist anymore, but maybe it got moved and I missed it – @mjackson any input here?

**Comment by gaearon** [comment]
Yeah it’s dead and we plan to switch back to airbnb: https://github.com/reactjs/redux/pull/1559

**Comment by mxstbr** [comment]
I've closed #354, but let's keep this issue open to remember to change the documentation when reactjs/redux#1559 is merged!
