### ISSUE TITLE
Hot reloading failed with react-native

### ISSUE THREAD

**Issue by cpunion** [reactjs/react-redux#359]
I don't know react-native or react-redux has the problem, but I think it be ignored if I post it as react-native's issues.

I created a project to reproduce this: https://github.com/cpunion/ReproRN24HMRWithReactRedux

**Create steps**

```
$ react-natie init TestHMR24
$ cd TestHMR24
add reducer.js
modify index.ios.js to add store, Provider
```

**Test steps**

* open ios/TestHMR24.xcodeproj
* run on simulator
* enable Hot Reloading

<img width="322" alt="2016-04-19 12 10 59" src="https://cloud.githubusercontent.com/assets/8459/14627675/239fa314-0629-11e6-9bba-bef00f325a75.png">

* touch reducer.js, has error

<img width="321" alt="2016-04-19 12 11 12" src="https://cloud.githubusercontent.com/assets/8459/14627679/2aaa8016-0629-11e6-99bd-91b269fde30c.png">

* touch reducer.js, get well

* After this step, hot reloading always success, just failed on first update.

**Comment by cpunion** [comment]
Updated repo, touch view may see the state changes.

**Comment by cpunion** [comment]
I found my code has error, react-native's HMR has different module.hot.accept method, it isn't `accept(path, callback)`, it's `accept(callback)`, so it just used in module. I fixed code, but same result.

**Comment by cpunion** [comment]
Used a workaround, just put store into a state or object field:
```
class App extends Component {
  state = {
    store: configureStore()
  }
  render () {
    return (
      <Provider store={this.state.store}>
        <TestHMR24/>
      </Provider>
    )
  }
}
```

**Comment by gaearon** [comment]
This is not really our issue so closing. The error comes up if Provider receives a different store instance via props. It is up to you to figure out how to avoid it in your setup.

**Comment by cpunion** [comment]
@gaearon Thanks.

Is it a problem of `react-native` hot reloading? I found no problem in some `react-redux` hot reloading examples likes https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/client.js#L46

**Comment by gaearon** [comment]
I don’t know. You can ask in their repo :-)
