### ISSUE TITLE
Redux.replaceReducer throw error "Unexpected key found"

### ISSUE THREAD

**Issue by andreechristian** [reactjs/react-redux#360]
Hello,
I tried to do a code splitting on route change.

When the route changes to '/register', i dynamically add "registration" as one of the root state using replaceReducer and it work just fine.
Once the registration completed i want to remove the reducer using replaceReducer again, but instead it return the following error :

> Unexpected key "registration" found in initialState argument passed to createStore. Expected to find one of the known reducer keys instead: ... Unexpected keys will be ignored.

Thanks in advance

**Comment by gaearon** [comment]
I think you should file this in Redux proper, not React Redux. This is probably a bug but I’m not sure if there is a good fix for this other than disabling the warning altogether.

**Comment by gaearon** [comment]
Note this is not an error. It is just warning.

**Comment by andreechristian** [comment]
Noted. I'll submit this bug on Redux. Thanks ya!
