### ISSUE TITLE
How can I access the store in non react components?

### ISSUE THREAD

**Issue by nmaves** [reactjs/react-redux#361]
We have a standard react-redux setup but we have a plain old api service class that need some of the information that we store in our redux state.  This service class is used by all of our components to access our backend.  

I understand that I could pass the info from a component to our service class functions but I would have to do that everywhere.

I can't seem to find a solution for this.  Has anyone else come across it?

Nathan

**Comment by markerikson** [comment]
The general answer to that is "middleware".  Either write a middleware that listens for custom actions you dispatch and makes the API calls itself, or something like redux-thunk that runs dispatched functions and injects the correct store functions.

http://chrispearce.co/redux-quick-hack-custom-thunk-apis/ explains the usefulness of thunks.  Also, if you look at the [Middleware](https://github.com/markerikson/redux-ecosystem-links/blob/master/middleware.md) page in my [Redux addons catalog](https://github.com/markerikson/react-redux-links), you'll find numerous examples of centralizing interaction with various external services.

**Comment by gaearon** [comment]
Yep, middleware is the way to go.

```js
function myServiceMiddleware(myService) {
  return ({ dispatch, getState }) => next => action => {
    if (action.type == 'SOMETHING_SPECIAL') {
      myService.doSomething(getState());
      myService.doSomethingElse().then(result => dispatch({ type: 'SOMETHING_ELSE', result }))
    }
    return next(action);
  }
}

// Usage:
import { createStore, applyMiddleware } from 'redux'
const serviceMiddleware = myServiceMiddleware(myService)
const store = createStore(reducer, applyMiddleware(serviceMiddleware))
```

**Comment by StevenBlack** [comment]
👋 Helpful hint:  the link to Mark @markerikson's article is:
  [Redux Hack: Custom Thunk APIs](http://chrispearce.co/blog/redux-hack-custom-thunk-apis.html)
