### ISSUE TITLE
When to default mapStateToProps and mapDispatchToProps 

### ISSUE THREAD

**Issue by seanstrom** [reactjs/react-redux#367]
In #363 we were discussing a potential refactor, and in that refactor I came across some interesting behavior. The `connect` function will default the `mapStateToProps` and `mapDispatchToProps` arguments if necessary. Here are the current conditions:

* `mapStateToProps` is defaulted to `defaultMapStateToProps` when the argument is a falsy value.
* `mapDispatchToProps` is defaulted to `defaultMapDispatchToProps` when the argument isn't a function and is a falsy value.

My question is what is suppose to happen when we pass an invalid truthy value? And should we be making all invalid values default to the default values? One repercussion of not doing so it passing invalid values to `wrapActionCreators` and then later to `bindActionCreators`, which will result in that functions thrown error instead of our own error handling. Thoughts?

**Comment by gaearon** [comment]
Wherever possible we want to fail early on bad values. I haven't taken time to make the error messages great in this library so feel free to work on it!

**Comment by seanstrom** [comment]
Cool I'll start working on this and I'll open a PR later, thanks for the quick response :smile: !
