### ISSUE TITLE
use connect() with immutable js

### ISSUE THREAD

**Issue by Yixi** [reactjs/react-redux#369]
I create redux store use the facebook immutable js. 
so I get state in my component like this:

`@connect(state => { rules : state.get('rules').toJS() })`

because connect only receive the plain object, so I need use `toJS` to pass object to connect.

there is a problem , my `rules` is a array of object like `I.fromJS([{id: 1} , {id: 2}, {id, 3}])`

so every time `state.get('rules').toJS()` result is not equal. so when store change, this component always will rerender, because the `shouldComponentUpdate` in connect() only make a shallow equal. not a deep equal.

so how can I use the `Immutable.is` for `shouldComponentUpdate` in connect(), or other method to improve the performance with the array of object props equal problem?

**Comment by gaearon** [comment]
`toJS()` negates many benefits of Immutable because you’re spending work assembling plain objects.

While technically you can ensure referential identity with [Reselect](https://github.com/reactjs/reselect) because selectors memoize their outputs when the inputs are the same, I would suggest just using Immutable props in your components directly. `Record`s make this fairly neat, with no need for `get()` accessors for properties.

**Comment by enrique-ramirez** [comment]
@gaearon Hi! Sorry for posting on such an old post (I didn't want to create a new issue that is essentially the same).

The redux docs suggest using `toJS` HOC on `mapStateToProps` (https://redux.js.org/docs/recipes/UsingImmutableJS.html#use-a-higher-order-component-to-convert-your-smart-components-immutablejs-props-to-your-dumb-components-javascript-props) while you advice against doing so.

So my take is this: I'm using reselect's `createStructuredSelector` alongside immutablejs for my props. This should make immutable.js only change its parameters when they actually change, and reselect should memoize the results of those parameters so it'd only trigger when changes happened. 

The point is: the redux best practices state that I should NOT use immutable objects in my dumb components. I have 2 folders on my project: `components` (dumb components that are for presentation only) and `containers` (smart components connected to the store), so basically, my `components` folder should work with plain JS objects, while my smart components should deal with immutable objects and pass over plain objects to the dumb ones.

So I'm thinking that implementing the HOC the redux docs state is a smart step forward, but I really wanted your input on the matter. Is this overkill? Should I just deal with immutable everywhere (I really don't feel like I'm sacrificing that much maintainability, portability or easier testing by doing so, but I may be wrong).

Thanks for your time!

**Comment by apaatsio** [comment]
> The redux docs suggest using a `toJS` HOC on `mapStateToProps`

No, they don't. In the HOC example there is no `toJS` in `mapStateToProps`.

Moreover, the same page explicitly says in big letters "Never use toJS() in mapStateToProps"

**Comment by enrique-ramirez** [comment]
@apaatsio sorry, not sure what happened there. I probably misread or got confused. Thanks for clarifying that out!

**Comment by thuctung** [comment]
@apaatsio , so we should use toJS() in body of component, right?. If not use it, how to get value from immutable?
