### ISSUE TITLE
React 15.0.x support

### ISSUE THREAD

**Issue by akoshman** [reactjs/react-redux#371]
Hi all,

How about 15.0.x support? React made some changes in API and current version of react-redux doesn't work with latest React :)

Thanks

**Comment by TrySound** [comment]
@akoshman It's supported https://github.com/reactjs/react-redux/blob/master/package.json#L98
How it doesn't work? Show your code and config.

**Comment by gaearon** [comment]
Yeah, it is supported just fine!

**Comment by akoshman** [comment]
Thanks for help guys
