### ISSUE TITLE
v4.4.4 appears to prevent components from receiving context changes

### ISSUE THREAD

**Issue by krukid** [reactjs/react-redux#372]
I have a project based on https://github.com/erikras/react-redux-universal-hot-example and one of my components needs to check `router.isActive(someUrl)` whenever a route changes and update its style/markup. The router object is accessible from components via context. Since `react-redux` v4.4.4 the component no longer updates (`render`, `shouldComponentUpdate`, `componentWillReceiveProps` are not called) on route change.

I've specifically checked that it works with `<= v4.4.3` and not with `>= v4.4.4`.

The essential code of the component is:
```es6
class Item extends Component {
  static contextTypes = {
    router: PropTypes.object
  };

  render() {
    return (
      <div>{this.context.router.isActive(this.props.url) ? 'yes' : 'no'}</div>
    );
  }
}
```

**Comment by gaearon** [comment]
Context updates are notoriously broken with `shouldComponentUpdate` (https://github.com/facebook/react/issues/2517). If a library you use relies on them, you should be using impure version of `connect()`. We can’t protect against random breakage in patch versions here because you are essentially relying on known buggy behavior.

Please pass `{ pure: false }` to any `connect()` calls in the hierarchy of this component. If this is a common problem, you can write `myConnect()` that calls `connect()` with `{ pure: false}` and use it instead.

Related: https://github.com/reactjs/react-router/issues/470.

**Comment by krukid** [comment]
This makes me sad. I guess I'll wait for [react-router v2.4.0](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.4.0.md) that will seemingly address this problem.

**Comment by gaearon** [comment]
It makes many people sad but that’s our reality :-/.
As a library we can’t really guarantee whether context propagates or not because the whole thing is buggy.

**Comment by krukid** [comment]
Just tried `react-router v2.4.0` that allows receiving the router via props, but that doesn't work with `react-redux v4.4.4` either. Passing location prop all the way down the component hierarchy seems to be the way this is going. I just hope some kind of consensus is established among the major players in the React world on how to propagate global state without clutter. Meanwhile the little people suffer :(

**Comment by gaearon** [comment]
Sorry but 2.4.0 had no relation to this issue. `withRouter` that was added there just exposes context as a prop but it doesn't affect how that context is actually updated.

https://github.com/reactjs/react-router/issues/470 is still open. This is the issue you want to be tracking.

I documented a workaround above. Please don't “suffer”, just use `{ pure: false }` in the meantime. This is exactly why it was added.

**Comment by krukid** [comment]
Ok, will do, thanks :)

**Comment by landabaso** [comment]
> Context updates are notoriously broken with shouldComponentUpdate (facebook/react#2517). If a library you use relies on them, you should be using impure version of connect(). We can’t protect against random breakage in patch versions here because you are essentially relying on known buggy behavior.

@gaearon, AFAIK react-redux also relies on the context feature of React. So does that quote above also apply to react-redux itself? Say, for instance:
```
<Parent>
<Child/>
</Parent>
```

a) The parent's `shouldComponentUpdate` returns `false`.
b) Child is connected to some part of the `state` that changes.

Will it render? Do we need to pass `{ pure: false }`?

**Comment by gaearon** [comment]
@landabaso React Redux only uses context for dependency injection of the `store`. The future updates work because `Child` subscribes to the `store` directly via `store.subscribe()` API.

@krukid I sent a few PRs to fix this in React Router, and it won’t be an issue in 3.0 anymore.
