### ISSUE TITLE
Duplicated dependencies

### ISSUE THREAD

**Issue by anaibol** [reactjs/react-redux#377]
I am not sure it's something relative to react-redux, redux or webpack.
Using both on a project I have a duplicated module of lodash.
![selection_036](https://cloud.githubusercontent.com/assets/3210177/15148298/da854b82-16c4-11e6-852f-daa607fe17dd.png)
Is that something normal?

**Comment by gaearon** [comment]
You can use [`npm dedupe`](http://4waisenkinder.de/blog/2014/06/09/flatten-your-dependencies-with-npm-dedupe/) to make it more flat. Also it’s best if you use npm@3 which dedupes better by default.
