### ISSUE TITLE
It should get the latest state on component which is in iframe.

### ISSUE THREAD

**Issue by sevenLee** [reactjs/react-redux#380]
Normally, the state changing (redux application state), it will trigger other component to get the latest state. I think it should get the latest state in component which is in iframe. That is the problem I encountered.

I can't get the latest state in iframe (source is React component), when I changing state in another component, and actually the mapStateToProps was triggered!(means iframe source component) but its state is not the latest in mapStateToProps function. it does not really concerns with the react-redux library? Is it not the bug?

I already post the issue on the stackoverflow, please check it: http://stackoverflow.com/questions/37218422/redux-react-why-i-cant-bind-state-to-this-props-on-component-which-is-in-ifra

Thanks a lot!

**Comment by gaearon** [comment]
Hi! Unfortunately there is no way we could help you unless you provide a project consistently reproducing the issue, with exact instructions to reproduce it. Thanks!

**Comment by sevenLee** [comment]
@gaearon  Thanks of your kind reply! I already got your answer in stackoverflow. maybe I should not separate partial app from the whole web app in iframe, it was not allowed in redux structure?

**Comment by gaearon** [comment]
This is not related to Redux. Any state (not just Redux state) will get duplicated in an iframe because **an iframe is an independent instance of the whole app**. It’s like if you opened it in a different tab—each tab is completely isolated.

I don’t understand why you’re using iframes at all. But if you need them (make sure you know why!), please use something like `react-frame-component` to have just one instance of the app.

**Comment by sevenLee** [comment]
I already uploaded my whole project, please check it: https://github.com/sevenLee/ServerSideRedux.git
npm install, then npm run dev. I would like to real time change the iframe page by outer component, it is like template generator app. I can define custom style on iframe page (like a theme), that is my real object.

**Comment by gaearon** [comment]
Thanks, but I still don’t understand why you want to use iframes rather than render the component that implements a preview directly.

**Comment by sevenLee** [comment]
The main reason is the iframe page has its own css theme style, if I render directly, the theme preview page will be polluted by outer css style... that why I need iframe. The tricky is I used react component  to be the iframe page through react route....is it appropriate architecture?

**Comment by gaearon** [comment]
>The main reason is the iframe page has its own css theme style, if I render directly, the theme preview page will be polluted by outer css style.

This is the real problem. I think you need to find a way to isolate styles so it’s possible to render two components with different themes in one app. This can be done by using specific CSS class names for each themes, and passing corresponding class names to the components.

**Comment by sevenLee** [comment]
Yeah, If I really want the iframe.....is it possible pass the store into iframe? Because iframe source link page with react-router, do you have any idea pass store through Route or get the sync store in inner component (in iframe)? I use <Provider> to pass store to component, how I get the store in component? If I still use connect(), can I get the store manually?

**Comment by gaearon** [comment]
Have you looked into using https://github.com/ryanseddon/react-frame-component?

**Comment by sevenLee** [comment]
Yeah I just had a glance it, I am not sure that is what I need, I try to use it to combine with iframe and react-route now.....thank you:)

**Comment by gaearon** [comment]
You would need to do anything with React Router for it though. This *is* the component that renders to an iframe—you don’t need to “combine it with an iframe” either. The point is that anything inside `<Frame>` would get rendered into a separate frame, so you can render your CSS there *and* the component itself. Not the `<script>` bundle.

**Comment by sevenLee** [comment]
The package works so great! I don't need to use react-router to decide iframe source any more, I directly put the component I want to display inner < Frame > , the component will render in iframe, like so:
```
<Frame>
          <AnotherView />
</Frame>
```
The most awesome feature is the state is synchronous ! the inner component works the same as outer component. Now I can dynamically change inline style in inner component. That is big present for me, @gaearon very much appreciated ! :D

**Comment by sevenLee** [comment]
I don't know why the inner state could be synchronous even the component in iframe? What the magic in react-frame-component? amazing!

**Comment by gaearon** [comment]
Great, I’m glad it worked for you. The state is in sync because there is just one instance of your app. Inside of using iframe as a container for the app with its own `<script>` tag, `react-frame-component` just [uses `ReactDOM.render()`](https://github.com/ryanseddon/react-frame-component/blob/1770610ddbfcf4362e3d75f8b8268946ce9fcd14/index.js#L88) (well, not quite, but pretty close) into the iframe body.
