### ISSUE TITLE
refactoring with HOC connect and mergeProps

### ISSUE THREAD

**Issue by darul75** [reactjs/react-redux#382]
Hi,

I have updated some parts of our codes with deep use of connect hoc, sometimes mergeProps function was needed and it worked like a charm. My only question is about how we could improve how we deal with a new function that is recreated each time and if it might be possible to avoid that.

considering this example

```
function mergeProps(stateProps, dispatchProps, ownProps) {
  const { val1, val2 } = stateProps;

  return Object.assign({}, ownProps, {
    ...stateProps,
    ...dispatchProps,
    handleSignIn: () => dispatchProps.handleDispatchSomeStuff(val1, val2)
  });
}
```

I have made some tests of [whyDidYouUpdate](https://github.com/garbles/why-did-you-update) middleware and got this warning that is pretty obvious.

```
Value is a function. Possibly avoidable re-render?
deepDiff.js:43 before handleDispatchSomeStuff() {
      return dispatchProps.handleDispatchSomeStuff(val1, val2);
    }
deepDiff.js:44 after  handleDispatchSomeStuff() {
      return dispatchProps.handleDispatchSomeStuff(val1, val2);
    }
```

Is it a solution to avoid that ?

Thanks,

Julien

**Comment by gaearon** [comment]
I don’t think there’s any simple way to avoid it.

The best way to solve this is to have the components pass those values directly in the callbacks.
You can introduce intermediate components that do just that, if you’d like.

**Comment by darul75** [comment]
Ok thanks dan
