### ISSUE TITLE
connect's state.storeState becomes out of sync with context.store.getState()

### ISSUE THREAD

**Issue by vitosamson** [reactjs/react-redux#384]
I'm running into a really weird issue. I've got a Breadcrumbs component with the reducer, actions and component below.

Everything works fine until about the fifth time that the `addBreadcrumb` action is fired. When that happens, I see the action get logged in console, I see the correctly updated state in the `next state` part of the log, but my Breadcrumbs component is not receiving the updated state via props.

After digging a little bit I noticed that the `Connect` that wraps the Breadcrumbs component has an inconsistent state when comparing its `state.storeState.breadcrumbs` with its `context.state.getState().breadcrumbs`. The store state on the context is correct but the connect's local state is not. This seems to only happen at about the fifth time that the `addBreadcrumb` action fires, until that point the state is consistent.

I'm fairly certain I'm following the immutability rules with my reducer. I've tried passing `{ pure: false }` to connect but that didn't help.

I'm unfortunately not able to reproduce this in a codepen but I was hoping you might be able to point me in the right direction for possible issues.

react 0.14.7
redux 3.0.3
react-redux 4.2.1

```js
// reducer
import assign from 'object.assign';

import {
  ADD_BREADCRUMB,
  REMOVE_BREADCRUMB,
} from '../../actions/breadcrumbs';

const initialBreadcrumbsState = {
  crumbs: {},
};

export default function breadcrumbs(state = initialBreadcrumbsState, action) {
  switch (action.type) {
    case ADD_BREADCRUMB:
      return assign({}, state, {
        crumbs: assign({}, state.crumbs, {
          [action.crumb.key]: action.crumb.title,
        }),
      });

    case REMOVE_BREADCRUMB:
      return assign({}, state, {
        crumbs: assign({}, state.crumbs, {
          [action.key]: '',
        }),
      });

    default:
      return state;
  }
}
```

```js
// actions
export const ADD_BREADCRUMB = 'ADD_BREADCRUMB';
export const REMOVE_BREADCRUMB = 'REMOVE_BREADCRUMB';

export function addBreadcrumb({ key, title }) {
  return { type: ADD_BREADCRUMB, crumb: { key, title } };
}

export function removeBreadcrumb(key) {
  return { type: REMOVE_BREADCRUMB, key };
}
```

```js
// component

export class Breadcrumbs extends Component {
  ...
}

export default connect(state => ({ breadcrumbs: state.breadcrumbs }))(Breadcrumbs);
```

**Comment by gaearon** [comment]
The code looks good. Any chance your `Breadcrumbs` component implements a bad `shouldComponentUpdate`? Have you tried logging when it gets rendered, or logging the value you get in `mapStateToProps`? It’s hard to say what goes wrong without a reproducing case.

**Comment by vitosamson** [comment]
The component doesn't implement `shouldComponentUpdate` at all, nor do any of the components above it in the hierarchy. I added logging in both the `render` and `componentWillReceiveProps` on the Breadcrumbs component, and it shows the (inconsistent) state from `Connect.state.storeState`. Adding a log in the `mapStateToProps` fn shows the same.

Interestingly, nothing gets logged at all after the last `addBreadcrumb` action fires (the one that doesn't seem to be updating the connect's state). The action itself is logged but the component doesn't re-render, `componentWillReceiveProps` doesn't get called, and the log in `mapStatesToProps` doesn't get called either.

The inconsistent breadcrumb state appears to be across all the Connects throughout the app, not just the one wrapping the Breadcrumb component.

**Comment by gaearon** [comment]
Can you try updating `react-redux` and `redux` to their latest versions?

**Comment by vitosamson** [comment]
Looks like this was actually an issue in a different part of my code (a faulty `onEnter` hook in my routes). Figured that out when other parts of the app started misbehaving in the same fashion after five route changes 😄 

Thanks anyway for the quick response and all your hard work on redux, @gaearon!

**Comment by gaearon** [comment]
No problem! Happy you got it resolved.
