### ISSUE TITLE
How to call actions right after each other

### ISSUE THREAD

**Issue by RezaRahmati** [reactjs/react-redux#386]
Hello

I have a problem that I cannot figure out how to tackle that with react-readux

I have an app which constantly produce some logs (from beacon device) and store them in state (consider 2 logs/second). Then I need to send this logs sequentially to server api and remove them from the state.
Since calling api might take times I cannot call them in loop, because I need the first api call be done and call for the next row then (the second call needs some information from the first call)

Right now I have the logs ready to send in store, but I cannot figure out how to process them.

**Comment by gaearon** [comment]
Please ask the usage questions on StackOverflow.
We use the issue tracker for bug and feature requests only.
Thanks!

**Comment by RezaRahmati** [comment]
OK, this is the link for my question [http://stackoverflow.com/questions/37350783/how-to-call-actions-right-after-each-other-in-react-redux](url)
