### ISSUE TITLE
Uncaught TypeError: Cannot read property 'displayName' of undefined

### ISSUE THREAD

**Issue by ffxsam** [reactjs/react-redux#387]
disregard

**Comment by zedd45** [comment]
For future reference for people who come here, this is possibly related to [imports being malformed](https://gist.github.com/jmarceli/7aa4aed6e5e825e85e56#1).  

In my specific case, it was the import {x as y} syntax that Babel 6 wasn't liking.

**Comment by totymedli** [comment]
I got this error because I accidentally added parentheses after my class decorator:

```js
@withRouter() // Don't write parentheses here!
@connect(null, { loginUser })
class Login extends React.Component { ... }
```
The way to write it is just `@withRouter`.
