### ISSUE TITLE
connect prevents LinkContainer from marking links as active

### ISSUE THREAD

**Issue by olalonde** [reactjs/react-redux#388]
Took me a while to figure this one out. For some strange reason, when I use connect to decorate my component, `<LinkContainer>` stops marking links as active. If I remove the `connect()(Header)` call, `<LinkContainer>` works as expected.

```javascript
import React from 'react'
import { connect } from 'react-redux'
import { LinkContainer } from 'react-router-bootstrap'
import {
  Nav,
  Navbar,
  NavItem,
} from 'react-bootstrap'

class Header extends React.Component {
  render() {
    return (
      <div>
        <Navbar>
          <Navbar.Collapse>
            <Nav pullLeft>
              <LinkContainer to="/dashboard/registrations">
                <NavItem>
                  Registrations
                </NavItem>
              </LinkContainer>
              <LinkContainer to="/dashboard/monitoring">
                <NavItem>
                  Monitoring
                </NavItem>
              </LinkContainer>
            </Nav>
          </Navbar.Collapse>
        </Navbar>
      </div>
    )
  }
}

export default Header

/*
When using connect(), LinkContainer stops working and
links are no longer marked as active when URL changes
*/

// export default connect()(Header)
```

Here's the behaviour I get when using connect:

![gif](http://g.recordit.co/FHbgKYv8N8.gif)

Thinks those are related but I can't figure out a quick/official fix:

https://github.com/reactjs/react-router/issues/3286
https://github.com/reactjs/react-router/issues/470

**Comment by gaearon** [comment]
This is fixed in React Router `3.0.0-alpha.1` and newer.

**Comment by gaearon** [comment]
In fact the last comment in the issue you linked says exactly that 😉 
https://github.com/reactjs/react-router/issues/470#issuecomment-220491445

**Comment by olalonde** [comment]
@gaearon thanks. Upgrading to React Router `3.0.0-alpha.1` doesn't appear to have fixed the problem :(

**Comment by olalonde** [comment]
Just tested with `<Link>` directly and same problem.

**Comment by olalonde** [comment]
```javascript
export default connect(s => ({
  user: s.user,
}))(withRouter(Header))
```

fixed the problem.

**Comment by gaearon** [comment]
The Link component is fixed in router 3.0 alpha 1. Not the LinkContainer component from the router bootstrap package. Unfortunately it doesn't even use the Link directly so it doesn't benefit from the Link being fixed. I will file an issue there.

**Comment by olalonde** [comment]
@gaearon ah ok thanks. Any idea why `withRouter()` fixed the problem anyway?

**Comment by gaearon** [comment]
@olalonde Because both `withRouter()` and `Link` contain the necessary fix.

**Comment by gaearon** [comment]
FWIW you can use `withRouter(LinkContainer)` as a temporary measure.
