### ISSUE TITLE
Connect can't pass on context when using Enzyme

### ISSUE THREAD

**Issue by 5punk** [reactjs/react-redux#399]
Hi Guys,
I've a bit of a situation, when using enzyme for rendering React Components for my unit tests, I cannot pass over the context when I am exporting the component using `connect`.

Let me show you what I mean:

Component: 
```
class TestPage extends Component {
  contextType = {
     a: required
  }
  render() {
    return (<div>1</div>);
  }
}
export default TestPage;
```

Test:
```
import { shallow } from 'enzyme';

wrapper = shallow(<TestPage>, {
  context: {
    a: 10
  }
});
```

This WORKS!

BUT:

Component:
```
class TestPage extends Component {
  contextType = {
     a: required
  }
  render() {
    return (<div>1</div>);
  }
}
export default connect( state => ({ a: state.runtime.a }))(TestPage);
```

Test:
```
import { shallow } from 'enzyme';

wrapper = shallow(<TestPage>, {
  context: {
    a: 10
  }
});
```

Spits out: ``Warning: Failed Context Types: Required context `a` was not specified in `TestPage```

Help... How do I pass on my context through Redux's connect function?

**Comment by gaearon** [comment]
Hi! This is a usage question, so it would be much better to ask on StackOverflow. This is just a bug tracker, it’s not meant to be a place for Q&A because answers would get lost here. I’ll close but feel free to post a link to your StackOverflow question. Thanks!

**Comment by jarekb84** [comment]
@5punk did you end up creating a SO post for this issue?
