### ISSUE TITLE
Q: What is the reasoning behind the naming of mapStateToProps?

### ISSUE THREAD

**Issue by sdtsui** [reactjs/react-redux#406]
I have used Redux for many projects, and I use React daily.  I was asked a great question today: "why call it mapStateToProps -- wouldn't that be easy to confuse with a React component's `state`?". Why not call it something else?

I was hoping someone would have thoughts. Thanks! :)

**Comment by markerikson** [comment]
Did some digging through the issue archives and commit logs.  Looks like the argument name was changed from "select" to "mapStateToProps" roughly around August 7, 2015, in commit 3079d0045f8ced7c79db9b255172295d2294ae51, but I'm having trouble finding specific discussion around that.  

Beyond that, given that Redux is explicitly a "state management library", and `connect()` is supposed to hook together your Redux store to your React components, the intent is hopefully clear.  Also, the word "state" is sorta overloaded contextually anyway in that it means "the current values / variables / data that make up your application", so the same point could be made in regards to React.Component.state as well.

**Comment by gnoff** [comment]
Redux store has a getState method. mapStateToProps maps this state to some props that should be provided to the connected component.

Same thing for dispatch property and mapDispatchToProps.

The state name is overloaded but you can see that the naming is derived from redux terminology itself.
