### ISSUE TITLE
every single reducer fires for every single action I dispatch

### ISSUE THREAD

**Issue by mgenev** [reactjs/react-redux#409]
It appears that in Redux I have no way of saying "I want to fire _this_ particular action", I can dispatch in general and then I have to do conditionals to find out what action was dispatched and thus every single one of my reducers fire for every single action and every single reducer has to contain a conditional to find out if it's handling the right action. Not only is this redundant and not elegant, but it seems like a big waste.

**Comment by gaearon** [comment]
Please see http://redux.js.org/docs/FAQ.html#performance-all-reducers.

**Comment by gaearon** [comment]
(Redux manages global state. So actions are global by design. If you want a local update, you might want to use something other than Redux—for example, `setState()` in React or something similar.)

**Comment by markerikson** [comment]
You may also want to look at the numerous utilities and libraries in my Redux addons catalog at https://github.com/markerikson/redux-ecosystem-links.  In particular, the [Action/Reducer Creation](https://github.com/markerikson/redux-ecosystem-links/blob/master/action-reducer-generators.md) and [Component/Local State](https://github.com/markerikson/redux-ecosystem-links/blob/master/component-state.md) pages have a number of options for isolating reducer logic.
