### ISSUE TITLE
Proposal: HOC provider interface

### ISSUE THREAD

**Issue by billyjanitsch** [reactjs/react-redux#412]
The current `Provider` interface:

```js
const App = props =>
  <Provider store={store}>
    <MyComponent {...props} />
  </Provider>
```

Is, imo, expressed more cleanly as an HOC:

```js
const App = provide(store)(MyComponent)
```

A naive implementation:

```js
const provide = store => Component => props =>
  <Provider store={store}>
    <Component {...props} />
  </Provider>
```

Of course, you'd want to add some invariants and provide a displayName (or better yet, just let it add the store to context itself and do away with the `Provider` dependency). Bonus: [this check](https://github.com/reactjs/react-redux/blob/master/src/components/Provider.js#L36) is no longer necessary, and the syntax makes it more clear that you're providing a single store once.

What do you think about providing this API out of the box? Happy to send a PR if you like the idea.

**Comment by gaearon** [comment]
This is how it used to be in very early versions. It has significant downsides. Specifically it is more awkward to supply a store when server rendering and in tests because you have to generate classes every time.

**Comment by billyjanitsch** [comment]
That's a good point, thanks for explaining!

**Comment by sveinburne** [comment]
What does HOC stands for ?

**Comment by gnoff** [comment]
Higher order Component

check out https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.b5clq7pea

**Comment by sveinburne** [comment]
thanks :-)
