### ISSUE TITLE
Question: doStatePropsDependOnOwnProps

### ISSUE THREAD

**Issue by erykpiast** [reactjs/react-redux#413]
I'm curious why `doStatePropsDependOnOwnProps` is defined by checking length of function `mapStateToProps`. It causes weird issues with generated functions (ex. with `pipe/compose`) or ones with default arguments (see [Babel transpilation results](http://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=function%20add(a%2C%20b%20%3D%200)%20%7B%0A%20%20return%20a%20%2B%20b%3B%0A%7D)). Is it some kind of microoptimization or core concept?

**Comment by markerikson** [comment]
Well, per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length , `Function.length` "specifies the number of arguments expected by the function".  `connect()` can accept a `mapState` function that only depends on `state`, or depends on both `state` and `ownProps`, and since in both cases the `mapState` argument would be a function, checking the number of expected arguments is a reasonable way to determine which use case it is.

I would find it surprising that someone would be supplying default arguments as part of their `mapState` function, and also probably uncommon to be wrapping/generating it in some way.  Can you provide some examples of such a `mapState` implementation, and some possible use cases?

**Comment by erykpiast** [comment]
I think I understand the code, but I wish to know the motivation. If the function doesn't use `ownProps` argument (does not declare it in its definition), then passing this to the function after `state` cannot break anything, am I right?

The case was pretty simple, I need component depending on `params` only. I can define `mapStateToProps` for it like that:

```
const mapStateToProps = (_, { params }) => params;
```
or like that:
```
import R from 'ramda';

const mapStateToProps = R.pipe(R.nthArg(1), R.prop('params'));
```
Ignoring the fact which approach is better, the second one does not work because of that function length checking.

**Comment by markerikson** [comment]
The actual motivation is that if a connected component only needs generic-ish data from the store (such as `state.someField`, then `connect` will only re-run `mapState` when the store updates.  However, if a connected component needs to make use of its own props values in `mapState`, such as looking up the data for a specific item ID ( like `state.someData[ownProps.itemID]`), then `connect` will _also_ need to re-run `mapState` whenever the parent of the connected component re-renders, in case the own props have changed (which _could_ cause the result of `mapState` to change).  So, it's a performance optimization to only call `mapState` as much as is actually needed.

Your example confuses me a bit.  It sounds like you don't actually need `mapState` at all.  First, your component could be given, say, `<ChildComponent a={1} b={2} c={3} />`, but only bother to read and use `a` and ignore any other props.  Second, if you do really want to ensure that a component is only actually given a certain prop and ignores the others, just create a simple React wrapper component that does that.  `mapState` is irrelevant in that case.

**Comment by erykpiast** [comment]
Regarding my use case, I use react-redux-router along react-redux and that's because I need `mapStateToProps` with the second argument only, react-redux-router puts path params to `ownProps`. But it doesn't really matter, I just did want to talk about general issue.

Anyway, I see know what is happening based on `doStatePropsDependOnOwnProps` - quite a lot of. So I understand that nothing may change. And I consider my initial question as answered :)

Would you mind if this detail is included in documentation? I mean the requirement that `mapStateToProps` must be formally defined as binary function to receive `ownProps`.

**Comment by markerikson** [comment]
The docs for `connect` do indicate that `ownProps` is optional, and mention that your `mapState` will be called more often: https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

But yeah, doc PRs are always welcome if you've got improvements in mind.

**Comment by erykpiast** [comment]
Please, look at https://github.com/reactjs/react-redux/pull/417. I hope my english is good enough :)
