### ISSUE TITLE
Not clear error message

### ISSUE THREAD

**Issue by vinhlh** [reactjs/react-redux#418]
Inside a container, add mapStateToProps:
```
const mapStateToProps = (state, props) => {
  haha()
}
```

The error message is showed in console.log is
```
warning.js?8a56:44 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `AppContainer`.
```

That should be something like: haha is undefined

**Comment by markerikson** [comment]
That error message is from React, not React Redux.  Also, while it could maybe be improved a bit, it _is_ straightforward: your JSX is not correctly written, and one of the elements you are trying to render is not a valid variable.  Remember that rendering `<SomeComponent />` gets turned into `React.createElement(SomeComponent)`, meaning that the variable `SomeComponent` must exist at that point.  You are likely not correctly importing one of your components.

Also, your `mapState` function is not correct - you're not actually returning anything from it, as the use of curly braces with the arrow function means there is no implicit `return statement`, and you don't explicitly return anything.

But, ultimately, this is not anything to do with React Redux at all.

**Comment by gaearon** [comment]
Most likely you forgot to export the component from the file, so you get `undefined` when importing it.
`mapStateToProps` probably doesn’t run at all for this reason.

**Comment by haikyuu** [comment]
Another cause might be that you're using `module.exports = { containerComponent }`  which

> Creates an empty object for the module that is available immediately for reference by other modules. [from the docs](http://requirejs.org/docs/api.html)

Use `export { containerComponent }` instead.

The error message i got is "Element Type is invalid: expected string or a class/function but got undefined. Check the render method of `Component`
