### ISSUE TITLE
Is the WrappedComponent required?

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [reactjs/react-redux#422]
The `connect()` is being create WrappedComponent like
```
<div data-reactid=".0.0.0.0.0.0"> ... </div>
```

I'm work on some project porting application to project using react, redux from traditional web project. Sometime old css codes has some selector like `.parent > .child` doesn't works because unintended created WrappedComponent.

Also I'm worrying about that in case of the massive DOM tree(like many items of list), `connect()` add one or more empty div(WrappedComponent) per item, then it make DOM tree so heavy that performance might be decreased.

Am I worrying unnecessarily? or can I use `connect()` without WrappedComponent?

**Comment by markerikson** [comment]
The wrapper component generated by `connect()` doesn't generate any DOM elements.  This should not be a concern.  

Also, there is not a 1:1 correspondence between React component instances and DOM elements anyway.  A React component could generate many DOM elements, one, or none.  Try using the React DevTools to see what components are actually generating those elements.  You could also start adding extra classes to the elements your components are generating to help see how the structure corresponds.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Thanks~ I will check!
