### ISSUE TITLE
Put function that returns promise in redux state

### ISSUE THREAD

**Issue by realbugger** [reactjs/react-redux#424]
I'll explain why I want to do this later. 
Here is the problem. I have a function that returns a promise like below:
```
const testFunc = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (Math.random() >  0.5) {
        resolve('succeeded');
      } else {
        reject('failed');
      }
    }, 1000);
  });
};
```
As expected, I can invoke it like this just fine:
```
testFunc()
  .then((result) => console.log(result)) // 'succeeded'
  .catch((error) => console.log(error)); // 'failed'
```
Or assign it to a variable and call it like this
```
const testFuncVar = testFunc;
testFuncVar()
  .then((result) => console.log(result)) // 'succeeded'
  .catch((error) => console.log(error)); // 'failed'
```
These are all expected. However, once I put the function in redux state, then invoke it from there, it doesn't work anymore. Here is what I did (grossly simplified).
```
const initialState = {testFunc: testFunc};
// redux reducer, action creator, etc.
...
...
// somewhere later
function testFunInState(state) {
  // this is not working
  state.testFunc()
    .then((result) => console.log(result))
    .catch((error) => console.log(error));
}
```
The error I got was `_promise2 is not defined`. Somehow the `Promise` object got lost whenever the function is put in redux state?

But I did find a workaround. If I change the function to
```
const testFunc = (resolve, reject) => {
  setTimeout(() => {
    if (Math.random() >  0.5) {
      resolve('succeeded');
    } else {
      reject('failed');
    }
  }, 1000);
};
```
And call it with `resolve` and `reject` passed in as parameters, then I'm good.
```
// this works
new Promise((resolve, reject) => state.testFunc(resolve, reject))
  .then((result) => console.log(result))
  .catch((error) => console.log(error));
```
I'm wondering why a function that returns promise doesn't work once it's put in redux store, but one without returning promise works?

Now onto why I want to do it this way. What I'm trying to achieve is to have a job queue that periodically dispatch some async actions, and depending on the result (resolve or reject), does something else (like retry, or send out notification). I want to dynamically add/remove jobs to and from the queue, therefore it's hard to have a reducer that can handle all possible actions. It feels like this is a reasonable way to approach it. I'm open to suggestions.

**Comment by gaearon** [comment]
This is a usage question. Please ask it on StackOverflow or Discord. We use the issue tracker to track bugs. Answers get lost here, and people ask the same questions again and again 😄 . Thanks!

**Comment by gaearon** [comment]
(Also note that we don’t recommend putting anything non-serializable into the state. Redux Saga or Redux Obseravble seems like better ways to do what you described.)

**Comment by realbugger** [comment]
Got it. Thanks @gaearon
