### ISSUE TITLE
Make storeShape available for importing

### ISSUE THREAD

**Issue by fatfisz** [reactjs/react-redux#434]
Hello, would it be possible to make the store shape available for importing (or requiring, etc.)? Right now it is only possible through `react-redux/lib/storeShape` or `react-redux/src/storeShape`, but it would be so much nicer to be able to write:
```
import { Provider, storeShape } from 'react-redux';
```

`react-router` does something like this, i.e. `routerShape` and `locationShape` are exported at top level too additionally to `react-router/lib/PropTypes`.

**Comment by timdorr** [comment]
If you want to access Provider's context directly, that's not really supported behavior at the moment. It's best to use connect, as it provides a number of performance improvements over vanilla access.

**Comment by fatfisz** [comment]
No, that's not what I wanted to do. Why the assumption?

IIRC I had a top level component which needed the store to be passed so that it could render the `Provider` component with it. The linter was complaining about prop types, because in this situation the store was the provider's provider prop.

I honestly don't remember the details, but that's the gist of it. Now, wouldn't an easy access to the store shape be good in this situation?

**Comment by fatfisz** [comment]
@timdorr Could you please reply?
