### ISSUE TITLE
[Question/Help] Dynamically requiring container components is returning undefined

### ISSUE THREAD

**Issue by bretthadley** [reactjs/react-redux#440]
Hi,
I'm having an issue where I need to require a container into a map and dynamically render them based on a string the server sends back. To do this I have a "resolver" file that imports my container / adds them to a Map(). That is then required in a component where I call  resolver.get(this.props.component). However doing this for some reason returns undefined.

When I require the ComponentContainer in my resolver.js it's undefined? Anyone have an idea on why that is?
If i require my container directly into the component and just render <ComponentContainer /> it works. I don't understand why requiring a contaienr component outside of a react file returns undefined.

```js
//resolver.js
import { SnippetContainer } from '../containers';
import { Cta } from '../components';

const resolverMap = new Map();

console.log(SnippetContainer); //undefined

resolverMap.set('SnippetContainer', SnippetContainer); //this is undefined. redux connect()
resolverMap.set('Cta', Cta); //this works just a standard React.Component

export default resolverMap;
```

```js
//page.js
import React, { Component } from 'react';
import { Grid, GridColumn } from '../';
import { SnippetContainer } from '../../containers';
import resolver from '../../services/resolver';

console.log(SnippetContainer); //undefined

export default class Page extends Component {
    static defaultProps = {
        components: [
            'Cta',
            'SnippetContainer',
        ]
    };

    render() {
        console.log(resolver); // [undefined, function cta]
        const components = this.props.components.map(component => {
            const Component = resolver.get(component);
            return <Component />;
        });

        console.log( SnippetContainer); // this works here. Why?

        return (
            <div>
                <Grid>
                <SnippetContainer /> //this works! so problem isn't to do with the container code.
                    <GridColumn default="one-whole">
                        {components}
                    </GridColumn>
                </Grid>
                {this.props.children}
            </div>
        );
    }
}
```

I have the requirement where the CMS can specify strings for the components to render to a page dynamically.

**Comment by jimbolla** [comment]
What does `containers` look like?

**Comment by bretthadley** [comment]
```js
containers/index.js
export SnippetContainer from './SnippetContainer';
```

```js
SnippetContainer.js
import { connect } from 'react-redux';
import { Snippet } from '../components';

const mapStateToProps = (state) => state.snippet;

export default connect(
    mapStateToProps
)(Snippet);
```

@jimbolla The import / export definitely works because I can render the SnippetContainer inside the <Page /> if I do it directly. The <Cta /> component also work using the dynamic way.

**Comment by jimbolla** [comment]
Is it possible that your imports form a circular reference? Ex: A.js imports B.js imports C.js imports A.js

That would explain why SnippetContainer is undefined during definition but available during render.
