### ISSUE TITLE
Redux API docs: use selectors, parameter destructuring, and spread operators for examples section

### ISSUE THREAD

**Issue by yangmillstheory** [reactjs/react-redux#441]
https://github.com/reactjs/react-redux/blob/master/docs/api.md#inject-dispatch-and-todos

If we want to endorse using selectors as a best practice for querying the store, does it make sense to change

```js
import * as actionCreators from './actionCreators'

function mapStateToProps(state) {
  return { todos: state.todos }
}

export default connect(mapStateToProps, actionCreators)(TodoApp)
```

to something like

```js
import * as actionCreators from './actionCreators'
import * as selectors from './selectors'

function mapStateToProps(state) {
  return { todos: selectors.getTodos(state) }
}

export default connect(mapStateToProps, actionCreators)(TodoApp)
```

For parameter destructuring, we could do 

```js
import * as actionCreators from './actionCreators'
import * as selectors from './selectors'

function mapStateToProps(state, { userId }) {
  return { todos: selectors.getTodosForUserId(state, userId) }
}

export default connect(mapStateToProps)(TodoApp)
```

Spread operator changes would be pretty straightforward, and would replace `Object.assign` in snippets like https://github.com/reactjs/react-redux/blob/master/docs/api.md#inject-todos-and-all-todoactioncreators-and-counteractioncreators-directly-as-props.

**Comment by timdorr** [comment]
#416 is going to use selectors internally. What you do for your own mapping of state to props is really up to the user to decide on. If anything, I would open a PR on Redux's examples to make use of reselect.
