### ISSUE TITLE
Unable to initialise state in mapStateToProps

### ISSUE THREAD

**Issue by tomitrescak** [reactjs/react-redux#444]
#Hi. I have a more complex store in which one of the keys keeps state of multiple objects, identified by id.

My problem is, that when editor is loaded I need to initialise default properties in the store. When editor is loaded again, these values are reused. I tried to do this in mapStateToProps, yet it results to error. This is what I do:

1. In mapStateToProps I detect whether store has a specific key
2. If the key is not there, I dispatch action to initialise it

What would you recommend to do about this? I cannot in it this in the reducer, as before the component is loaded I do not know under what key I will store values in the store.

```
Store = { 
  Editors: { 
      Id1: {},
      Id2:{}
      ...
  }
}
```

**Comment by jimbolla** [comment]
Have your component dispatch an action in component(Did|Will)Mount that initializes the store state.

**Comment by tomitrescak** [comment]
@jimbolla is there any other way? I'm sticking to the stateless components.

**Comment by jimbolla** [comment]
You could use recompose's `lifecycle` method to wrap your component.
