### ISSUE TITLE
Invalid prop type Object for an Array

### ISSUE THREAD

**Issue by tayyabshabab** [reactjs/react-redux#445]
I have a reducer which returns an array of slides.
`const initialState = {
  slides: []
};`

I have added a PropType of Array in the component.
`Homepage.propTypes = {
  slides: React.PropTypes.array
};`

The problem is that I receive this warning when the component gets rendered. However I am returning array from the reducer.
> Warning: Failed prop type: Invalid prop `slides` of type `object` supplied to `Slider`, expected `array`.

![screen shot 2016-07-27 at 17 48 47](https://cloud.githubusercontent.com/assets/1446474/17182050/7f15ed7e-5422-11e6-9937-d57f9df8d86c.png)

I checked in console and when the component is rendered the first time it receives an object of type List in slides prop but after the data is fetched from API it then displays array.

What should I do to remove this warning?

**Comment by markerikson** [comment]
This is a usage question, and really not even related to React Redux at all - it's React-specific.

That said, I suppose you could do something like `PropTypes.oneOf([PropTypes.array, PropTypes.object])` or something.  There's also a third-party package of PropTypes types for Immutable data structures out there that you could use with this as well.

**Comment by BeAce** [comment]
I used [reselect](https://github.com/reactjs/reselect)  in my project,you can try this to change the data source.

```jsx
const makeList = () => createSelector(
  selectAbout,
  (HomeState) => Array.from(HomeState.get('dataList'))
);
``` 

```jsx
dataList: React.PropTypes.array,
```

```jsx
const initialState = fromJS({
  dataList: []
});
```

**Comment by sindhana3** [comment]
@tayyabshabab were you able to fix this issue?
