### ISSUE TITLE
Can mapDispatchToProps() provide an extra param  `state`  if a function is passed ? 

### ISSUE THREAD

**Issue by Mutefish0** [reactjs/react-redux#448]

**Comment by markerikson** [comment]
The question isn't really clear.  What are you trying to do?  What is insufficient about `mapDispatch`'s behavior?  What do you want to see?

**Comment by Mutefish0** [comment]
for example
```js
let mapDispatchToProps = (dispatch,ownProps,/* state*/) => ({
    handLogin:(user,pwd) =>{
        // i want to access `state` here
        if(!state.hasLogin)
            dispatch({ type:'LOGIN', user, pwd })
    }
})
export connect(mapStateToProps,mapDispatchToProps)(App)
```

**Comment by markerikson** [comment]
Yeah, `mapState` and `mapDispatch` don't support that scenario directly.  That's actually part of what prompted @jimbolla to start implementing a new approach to `connect()`.  

There are two ways you could do something like that right now:

1. Select the data using `mapState`, and have the component call `this.props.doStateDependentAction(this.props.someValueFromState)`
2. Select the data using `mapState`, and use the third argument to connect (`mergeProps` ) to define the action creator.  Note that this would probably involve re-defining the action creator function every time the state changes, which could be a performance issue.

**Comment by Mutefish0** [comment]
Got it,Thanks! @markerikson
