### ISSUE TITLE
Docs consistency

### ISSUE THREAD

**Issue by mbaroukh** [reactjs/react-redux#450]
A really small suggestion :
On http://redux-form.com/6.0.0-alpha.4/docs/api/Field.md/ I can read

Field .... 1. .... The name prop is required.

Then a few lines later : 
`<Field component={MyCustomInput}/>`
=> no name prop.

Maybe adding a name prop to the sample for consistency ?

**Comment by markerikson** [comment]
Ah... your example is talking about Redux-Form, which is a _completely_ separate library than React-Redux.

**Comment by mbaroukh** [comment]
Oups ... Really sorry ... Wrong tab ...
