### ISSUE TITLE
printWasted - should I ignore connected component's wrapper?

### ISSUE THREAD

**Issue by foiseworth** [reactjs/react-redux#452]
When using the React Performance tools and specifically printWasted I'm unsure as to whether I should be paying attention to connected component's wrapper.

Whenever the state changes, all my connected component's wrappers re-render (as intended) and (unless the stateProps have changed) return the cached rendered component. So in this case render has run but there has been no DOM update. Therefore I think it should show up in printWasted but I should ignore it.

The only thing that makes me doubt this is that not all my connected component's wrappers are in the wasted table.

**Comment by gaearon** [comment]
How much time is reported being spent there? If it’s a lot, it might mean your `mapStateToProps` is saving you from re-renders below but you do a lot of work in it, and maybe you could find a way to do less work there.

**Comment by foiseworth** [comment]
Many thanks for replying.

I'll investigate optimising mapStateToProps (unfortunately it just consists of some gets on immutable maps) but there are many instances of the component (200). However, from your reply, I'm presuming seeing a ```Connect(aComponent)``` in printWasted doesn't indicated a wasted render?

If I make a change to my store which has no effect on the current display (ie all components should return renderedElement early) and then printWasted, I don't see all my connected components which seems to contradict my presumption.

**Comment by gaearon** [comment]
It’s hard to say without a specific example reproducing this. If you can create one and you believe ReactPerf is behaving in a wrong way please file a bug in React and I’ll take a look.

**Comment by foiseworth** [comment]
@gaearon I kept looking into this and discovered there are two reasons why I might be missing some printWasted entries:
1) some are being filtered out by DONT_CARE_THRESHOLD which you seem to have removed from React in this https://github.com/facebook/react/pull/6647/files#diff-f5e99eb03b46b76237d2e7632d018f91L16 (we're still using v15.0.2)

2) after updating to the latest React, some entries were still missing, this (I believe) is because of the way perf tools work (not sure if it is a bug). As suggested, I will close and have opened a bug on the react project: https://github.com/facebook/react/issues/7484
