### ISSUE TITLE
connect does not account for child context.

### ISSUE THREAD

**Issue by mihirk** [reactjs/react-redux#454]
When I try and connect a component with context being passed from the parents, and required for my overall application routing, the new component generated by `connect` does not merge the context with the top level component it creates. I am not sure whether this something people want or not?

**Comment by DavidBrear** [comment]
Do you have an example of this? Also, what versions of the libraries are you using? I just got an app running using `create-react-app` and here's the gist of the code: https://gist.github.com/DavidBrear/5208b5ec1268c4c8ba8265d1bb6f0496. This displays the result: 
<img width="473" alt="screen shot 2016-08-12 at 9 11 27 am" src="https://cloud.githubusercontent.com/assets/1081640/17623255/17b0a2bc-606d-11e6-9192-67609f38e417.png">

**Comment by timdorr** [comment]
You can definitely access multiple parent contexts from a single component. So, something must be set up wrong. Without an example, I'm not sure what's going on, but it sounds like an error on your side, unfortunately. I'd look at @DavidBrear's example to see what you might be doing differently.
