### ISSUE TITLE
Remove redux as a react-redux dependency

### ISSUE THREAD

**Issue by adamterlson** [reactjs/react-redux#455]
## Some Background

I am working on a library which implements the redux store API, without actually using redux to store the data.  The purpose is to connect to state stored in Backbone models and collections in a redux-like fashion.  

In theory, by implementing the redux store API, one can even use redux middleware and other supporting libraries such as react-redux, without redux itself.  This can provide a nice "bridge" for projects who are evolving from a backbone ecosystem to that of react and eventually redux.

Check out the work-in-progress [here](https://github.com/adamterlson/backbone-redux-store) and a sample of it in action [here](https://github.com/adamterlson/backbone-redux-store/tree/api-docs/sample)

## The problem

In theory, one does not need redux, but in reality, react-redux takes a dependency on Redux for, as far as I can find, a singular purpose: supporting the shorthand `mapDispatchToProps` notation of simply passing an object by using redux's `bindActionCreators` function in [utils/wrapActionCreators.js](https://github.com/reactjs/react-redux/blob/93cdfaeaf9d3e5400ffc05fe9d177118286109ca/src/utils/wrapActionCreators.js):

```
connect(
    null,
    { foo: () => { ... } } // <--- Supporting this
)(MyComponent)
```

## Proposal

I (crazily) propose dropping the dependency on the redux library from react-redux. The package is only truly dependent upon the redux store **API** to function, not redux itself, and this one use of `bindActionCreators` may not be sufficient enough warrant redux as a dependency.  

After all, there could be other applications out there (like mine :D) which wish to leverage react-redux but don't want to use redux.

I'm open to any discussion about how crazy wrong I am. :)

Thanks!

**Comment by jimbolla** [comment]
But that won't necessarily always be true. For example, some code I'm working on right now in react-redux related to subscription notification, if accepted, might get moved into redux proper to remove code duplication. Then react-redux will definitely depend on redux.

**Comment by timdorr** [comment]
I've got to agree with @jimbolla here. Redux has both an API and a guaranteed way of behaving. And that behavior can be fairly critical to this library and isn't always documented exactly. If you happen to build something that works with it, great, but a hard requirement on Redux is going to be needed. 

At the very least, if your minification process is sufficient, any bytes spent on Redux code should be eliminated by dead code removal. And if you *really* want to get rid of it, you can use an alias in your build process to an empty module.

**Comment by adamterlson** [comment]
@timdorr Thanks for the explanation!
