### ISSUE TITLE
Connect on the server

### ISSUE THREAD

**Issue by atbjk** [reactjs/react-redux#463]
When you use connect to connect to a store server side, what happens? Does it stay subscribed to the store on each request? Would this not cause memory to build up?

Is there a way to use connect store without subscribing to the store?

**Comment by jimbolla** [comment]
Components subscribe during `componentDidMount` and unsubscribe during 'componentWillUnmount`.

**Comment by atbjk** [comment]
oh ok, for example if you did react.renderToString it would not subscribe

**Comment by jimbolla** [comment]
My understanding is that server-side-rendering via `renderToString` never calls `componentDidMount` and thus never subscribes.
