### ISSUE TITLE
Dispatching a redux action in componentWillMount leads to weird app behaviour

### ISSUE THREAD

**Issue by pke** [reactjs/react-redux#468]
## Version
react-router: 2.6.1
react: 0.14.8
redux: 3.5.2
react-redux: 4.4.5

## Steps to reproduce

`react-router` said its not related to them, so I'll try here.

I have this Pages component that does page transitions using `ReactStyleTransitionGroup` which uses `ReactTransitionGroup` internally.

```es6
const Pages = ({ location, children, page }) => {
  const { pathname, state } = location
  const transition = state && state.transition
  const transitionStyles = TRANSITIONS[transition] || TRANSITIONS.fromLeft
  return <ReactStyleTransitionGroup
    component="div"
    style={{ WebkitFlex: 1, flex: 1, overflow: "hidden" }}>
    <Div
      key={"page" + pathname}
      style={{ position: "absolute", top: 0, left: 0, right: 0, bottom: 0 }}
      transitionStyles={transitionStyles}>
      { page || children }
    </Div>
  </ReactStyleTransitionGroup>
}
Pages.propTypes = {
  location: React.PropTypes.object,
  children: React.PropTypes.node,
  page: React.PropTypes.element,
}


<Route component={App}>
    <Route component={Pages}>
          <Route path="/account" component={AccountRoute}>
            <IndexRoute component={AccountOverviewRoute}/>
            <Route path="/activity" component={AccountActivityRoute}/>
          </Route>
        </Route>
      </Route>
</Route>
```

My AccountRoute looks like this:

```es6
class AccountRoute extends React.Component {
  componentWillMount() {
    this.props.setTitle("Your account")
  }
  ...
}
```

## Actual Behavior

When I navigate from `/account` to `/activity` I am getting an error in `ReactTransitionGroup.js:_handleDoneLeaving:166` (React 0.14.8) saying that component is `null`. And its clear why.
Because when I look at `this.refs` I see one key in there named: `.$page/activity` but the functions parameter `key` has the value of `.$page/account`. So no `component` with the key `.$page/account` can be read from it.
The key is composed in my `<Pages/>` from the routers location.

Now the interesting thing is, when I move the action dispatch code from `AccountContainer:componentWillMount` to `AccountContainer:componentDidMount` everything works as expected. That page transitions happen without any errors. All the code does is dispatching an action to the redux store. Which, I know, triggers (maybe) a re-rendering. According to the (redux, react) docs its fine to call dispatch/setState from within `componentDidMount`.

I'd like to understand whats going on here. If you think this is more related to `redux` or `react` close this an I will carry it over there.

**Comment by timdorr** [comment]
Just logically, this makes sense. If your component hasn't mounted, it's not in the DOM and there's no ref for it yet. 

What's not clear is what is going on around all of this. Are you using something like react-helmet to do the page title? Where does this `AccountContainer` live?

**Comment by pke** [comment]
No I am not using `react-helmet`. I know the component has not mounted when `componentWillMount` is called. But I wonder why that should be play a role when dispatching actions. According to the docs its safe to dispatch action in this lifecycle hook.

About the confusion about `AccountContainer`. It is imported as `AccountRoute`. But I have updated the OP to make it less confusing

**Comment by timdorr** [comment]
If you follow through the entire dispatch lifecycle, it will eventually reach your connected component (within the same JS message queue). If there is a request to access a ref within whatever code is called in that component and the ref has not been mounted, that would be why you see the error.

It sounds like a quirk of the transition component that you're using. I would stick to cDM instead to avoid that issue.
