### ISSUE TITLE
Example of TodoApp?

### ISSUE THREAD

**Issue by wzup** [reactjs/react-redux#469]
What's that? How does `TodoApp` look? Is it just a function as everywhere in you your example here http://redux.js.org/docs/basics/ExampleTodoList.html, or should it be a full-featured React component? If one follows your examples and uses functions, there is no `dispatch` within the `TodoApp` function. It only injects `todos`, not `dispatch`. Why do you say that it injects `dispatch` then? Please be more detailed writing the documentation. Provide `TodoApp` example. Now it is not possible to understand.

![react-redux_api md at master reactjs_react-redux - google chrome 2016-08-21 12 57 10](https://cloud.githubusercontent.com/assets/3880497/17835444/19d842dc-679f-11e6-8202-276f448304ff.png)

**Comment by timdorr** [comment]
That's fair. I can see that being hard to understand if you haven't been following along with the Redux documentation. Want to submit a PR to clear it up?

**Comment by markerikson** [comment]
Please note that `dispatch` accepts two main arguments, `mapStateToProps` and `mapDispatchToProps`.  If a `mapDispatch` argument is not provided, `connect` will provide its own, which by default will inject the `dispatch` reference.  So, in that example, the provided `mapState` will inject a `todos` prop, and the default `mapDispatch` will inject a `dispatch` prop.

**Comment by mtomcal** [comment]
I can help out with this if nobody has dibs. Wouldn't the PR have to go to "redux" repo proper for this file: https://github.com/reactjs/redux/blob/master/docs/basics/ExampleTodoList.md ? @markerikson @timdorr 

Thanks guys!

**Comment by mtomcal** [comment]
More I look at this, I am not sure if this issue is in the docs currently as of Dec 2016. Might be already solved issue.
