### ISSUE TITLE
Request for error message

### ISSUE THREAD

**Issue by derekdreery** [reactjs/react-redux#479]
When doing

```
connect(...)
```
instead of
```
connect(...)(Component)
```
the error messages are not related to the mistake. Is it possible to include a test in debug mode that connect has actually been called on a component?

**Comment by timdorr** [comment]
Unfortunately, we can't know if you're currying the call for later use on a component. I don't see how you would detect this case at all. If you're using decorator syntax, then it will end up being unlikely that you'll run into this at least.
