### ISSUE TITLE
Code in docs causing error with new Airbnb ESLint update

### ISSUE THREAD

**Issue by samcorcos** [reactjs/react-redux#482]
I just updated eslint with the latest airbnb style guide and noticed that the [4.0 update in July](https://github.com/airbnb/javascript/blob/ca1124cd8d2e33addbffb3b1743849e2bf774039/packages/eslint-config-airbnb-base/CHANGELOG.md#400--2016-07-02) now registers an error for `no-named-as-default`. 

I bring this up because the documentation suggests exporting [both a named and default export](http://redux.js.org/docs/recipes/WritingTests.html#connected-components), and because I imagine many (most?) people are using enzyme and the Airbnb style guide for linting. For example:

```
In a unit test, you would normally import the App component like this:

import App from './App'
```

With the new rule, this would show a linting error (though it wouldn't cause a compile/runtime error). 

In order to solve this, we could do one of two things. Either add a `default as` or import the component with a name that is different than the named export. 

```js
import { default as App } from "./App"
```

or

```js
import ConnectedApp from "./App"
```

I am currently using `default as` and it works fine. The second option seems clunky, but it works just as well.

Is this worth updating in the docs? Or is this something we should just ignore/add an exception to `.eslintrc`?

**Comment by timdorr** [comment]
I don't really think we need to mention this. That's really out of scope for our documentation.

**Comment by samcorcos** [comment]
Hmm, ok. I was really suggesting that we change the documentation to the new syntax suggested by the Airbnb style guide using `{ default as ... }` rather than mentioning the style guide specifically, but it's fine either way 😄
