### ISSUE TITLE
 React.PropTypes validation warning

### ISSUE THREAD

**Issue by luckydrq** [reactjs/react-redux#484]
I have `react@15.3.1` and `react-redux@4.4.5` in my project and got the following warning:

```
warning.js:36 Warning: You are manually calling a React.PropTypes validation function for the `store` prop on `Connect(ToolboxContainer)`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
warning.js:36 Warning: You are manually calling a React.PropTypes validation function for the `store` prop on `Provider`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
warning.js:36 Warning: You are manually calling a React.PropTypes validation function for the `children` prop on `Provider`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
warning.js:36 Warning: You are manually calling a React.PropTypes validation function for the `actions` prop on `ToolboxContainer`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

How to avoid these warnings? I've read this [guide](https://facebook.github.io/react/warnings/dont-call-proptypes.html) but still have no idea. Not sure if it is emitted by react-redux's [storeShape](https://github.com/reactjs/react-redux/blob/master/src/components/Provider.js#L52). Please point out if i'm wrong, thanks!

**Comment by timdorr** [comment]
Something outside of react-redux is calling proptype validation. We don't do that internally.

**Comment by luckydrq** [comment]
Thank you for your reply!  I've found the reason. I have another react version(15.1.0) which used as a dependency, when i upgrade it to 15.3.1 the warnings disappear.

**Comment by farzer** [comment]
I use 15.4.1 version and my react-redux version is 5.0.1 meet this problem, can you give me some help?

code:

``` js
export default connect(state => ({
    app: state.app
}))(App);
```


error:

```
Warning: You are manually calling a React.PropTypes validation function for the `store` prop on `Connect(App)`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

Warning: You are manually calling a React.PropTypes validation function for the `storeSubscription` prop on `Connect(App)`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

**Comment by actionnick** [comment]
@timdorr 

I am seeing this error on `react@15.4.2` and `react-redux@5.0.3`.

It does seem like [here](https://github.com/reactjs/react-redux/blob/master/src/utils/PropTypes.js#L3) you are calling a validator function which according to [this](https://github.com/reactjs/prop-types/blob/master/README.md#difference-from-reactproptypes-dont-call-validator-functions) would result in a warning or error being thrown.

**Comment by gaearon** [comment]
No, calling `shape()` is fine (because it returns a validator, and calling *that* would throw).

Have you updated to `react-redux@5.0.4`? Seems like it fixes the deprecation warnings: https://github.com/reactjs/react-redux/releases/tag/v5.0.4.

**Comment by actionnick** [comment]
Tried updating the 5.0.4 and still seeing the warning.

Really seems like react-redux is generating the warning. Stack trace looks something like...

```
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types
    in Connect(Component) (created by OtherComponent)
    in OtherComponent (created by SomeOtherComponent)
    ...
```

**Comment by gaearon** [comment]
Are you sure you don't have older versions of React somewhere in the tree?
Please run `npm ls react` and paste the results.

The reason I’m asking: https://github.com/reactjs/prop-types#compatibility.

**Comment by denieler** [comment]
@gaearon have the same issue with `react@15.5.4` and `react-redux@5.0.4`

**Comment by timdorr** [comment]
That was specifically fixed in 5.0.4 (see #663). Something else must be triggering it.

**Comment by gaearon** [comment]
@denieler Please provide a minimal project reproducing it and I can take a look.

**Comment by denieler** [comment]
@gaearon nothing special, I just add `Provider` and build the script. In `app.js` file I have next:

```
import React, {Component} from 'react'
import { Provider } from 'react-redux'

export class App extends Component {
  render () {
    const store = {}

    return (
      <Provider store={store}>
          <span>Hello World!</span>
      </Provider>
    )
  }
}
```

And it doesn't show warnings in webpack-dev-server mode, but when I built it and mounted as a library - it does.

**Comment by denieler** [comment]
@gaearon I've investigated it a little bit and it seems that happening only when `process.env.NODE_ENV: "production"`

**Comment by denieler** [comment]
@timdorr maybe you have your comment how it can be fixed in this conditions?

**Comment by timdorr** [comment]
We need a more complete example. Can you share your whole repo? Just that code snippet by itself doesn't really tell us anything.

**Comment by denieler** [comment]
@timdorr sorry, created clean project and seems it works
