### ISSUE TITLE
seamless-immutable with connect breaks pure components?

### ISSUE THREAD

**Issue by braco** [reactjs/react-redux#492]
Noticed some bad performance with react-redux + [seamless-immutable](https://github.com/rtfeldman/seamless-immutable).

Firstly, here's a related problem I'm having. PureComponent works well:
```
import React, { PureComponent } from 'react';
export default class Thing extends PureComponent {}
```

Component above will only rerender when immutable props are changed.

```
import React, { PureComponent } from 'react';
class Thing extends PureComponent {}
export default connect(..., ...)(Thing);
```

Component above will rerender constantly. Am I correct in assuming PureComponent's shouldComponentUpdate is overwritten? I tried to outsmart it, but this is even true with `{ pure: false }`.

I'm looking through the code right now, and it looks like connect thinks the state is being changed. From (here)[https://github.com/reactjs/react-redux/blob/93cdfaeaf9d3e5400ffc05fe9d177118286109ca/src/components/connect.js#L60]:

```
shouldComponentUpdate() {
  return !pure || this.haveOwnPropsChanged || this.hasStoreStateChanged;
}
```

The above yields `false || false || true`, because of [this line](https://github.com/reactjs/react-redux/blob/93cdfaeaf9d3e5400ffc05fe9d177118286109ca/src/utils/shallowEqual.js#L17) in shallowEqual, as called by state comparison

Any thoughts?

**Comment by braco** [comment]
Fixed for now by making a HoC, will revisit

**Comment by jimbolla** [comment]
@braco Can you try perf testing against the v5 beta by running `npm install react-redux@next`?
