### ISSUE TITLE
How to use redux in non-fully-react project?

### ISSUE THREAD

**Issue by pcompassion** [reactjs/react-redux#493]
> Makes the Redux store available to the connect() calls in the component hierarchy below. Normally, you can’t use connect() without wrapping the root component in <Provider>.
> 
> If you really need to, you can manually pass store as a prop to every connect()ed component, but we only recommend to do this for stubbing store in unit tests, or in non-fully-React codebases. Normally, you should just use <Provider>.

So we can't use <Provider> since the root is not react component (non-fully-react project). 
Then we are not able to use `connect` either? 
The description above is confusing as what I need to do for non-fully-react project. 

I interpreted what the above statement as the following, hope I'm right. 
1. create store with `createStore` as in the doc
2. pass the store <MyComponents store={store} /> for all connected components (such as `connect(mapStateToProps, mapDispatchToProps)(MyComponents)

**Comment by timdorr** [comment]
You need to use `<Provider>` if you are creating `connect()`ed components within the parts of your app that are running on React. This library is solely for your React parts. It doesn't apply to non-React stuff and you can use the store you create directly elsewhere.
