### ISSUE TITLE
Can I connect every component with container?

### ISSUE THREAD

**Issue by lhz516** [reactjs/react-redux#495]
I often have this situation: I wrote a pure component and used it somewhere. But later I needed to do some data fetching for this component, so I had to add a container for it and modified the path where it's been imported. This wasted some time.

Can I just wrap EVERY component in a container using `connect`? If a component needs no data fetching at all, just put `export default connect()(Foo)` for it.

Does it somehow have performance impact if I do this?

**Comment by markerikson** [comment]
Feel free to connect as many components as makes sense for your own application.  `connect` actually does automatically implement `shouldComponentUpdate`, which can be helpful.

However, don't over-think the whole "containers" vs "presentational" aspect.  That's one reason why a feature-based folder structure _may_ be nicer than a "components" and "containers" folder structure.  But yeah, don't get too caught up in "oh, I made this a container, now I have to move it around".  Find something that works well for you.

Also see the Redux FAQ entry: http://redux.js.org/docs/FAQ.html#react-multiple-components .
