### ISSUE TITLE
Connect is not causing render on ownProps change. 

### ISSUE THREAD

**Issue by Daniel-Baranowski-BJSS** [reactjs/react-redux#496]
My ownProps is an object containing objects. connect looks something like this: 
```
@connect(
  (state,ownProps)=> {
    return {
      stateProp: state.reducer.favouriteReducer.favourites,
      ownProps: ownProps.myProps
    };
  }
)
```
Props received:
```
ownProps.myProps { 
   subPropOne: { 
      changedProp: "I was updated why won't you render again? "
   }
}
```

Also its worth mentioning that a grand parent of this component also has a @Connect on it.

**Comment by markerikson** [comment]
That example doesn't really make sense.  `ownProps` is the props passed directly to the connected component by its parent, like `<SomeConnectedComponent a={42} b={123} />`.  You don't need to include those in the return value from `mapState`, since `connect` will combine the incoming props and the `mapState` results to form the combined props passed to your real component.

**Comment by Daniel-Baranowski-BJSS** [comment]
If I don't include my props like described above they are invisible in my component. They are only passed once, and If the described component becomes re-rendered, due to its stateProp updating the new ownProps wouldn't be populated. The issue was fixed when I added ownProps mapping, but now the component doesn't re-render when my-props change.

**Comment by naw** [comment]
You should inspect what props your underlying component receives. If `ownProps` has a key called `myProps`, then your component should have a props key called `myProps` without needing to explicitly include it in `mapStateToProps`, like @markerikson said.

It sounds like you might be mutating the nested pieces of the `myProps` object in place, which won't trigger a re-render in and of itself.  How are you actually "updating" `changedProp`?

When you said "props received", how do you know they are received? Are you investigating inside `compnentWillReceiveProps` or something?

Forgetting redux for a moment, consider this example:
```javascript
class Parent extends Component {
  render() {
    return <ChildComponent someProp={window.someValue} />
  }
}
```

Changing `window.someValue` will not cause `ChildComponent` to rerender --- `ChildComponent` won't receive the new value until `Parent` renders.  When you change values, you need a component somewhere in the ancestor chain to get the ball rolling, with something like a `setState`

**Comment by jimbolla** [comment]
@Daniel-Baranowski-BJSS Were you able to resolve this?

**Comment by timdorr** [comment]
Looks like some good guidance and answers were given, so I'm closing this out.
