### ISSUE TITLE
Allow us to filter ownProps before connect

### ISSUE THREAD

**Issue by mafzst** [reactjs/react-redux#504]
Hi all!

## Problem
I'm currently developing an application in which I use third party React components. I wrap them into a Redux container.

In some cases (see eg below) I need to pass some infos to the container for behavioral purpose (generally in dispatch). For this I use the `ownProps` parameter.
The problem is that props are injected by `connect` in the connected component and then throw a React error because they are unknown.

Is it possible to filter them before connecting ?

## Example
In this case I use a third party dropzone component (around an image) to allow user to drag&drop image from his computer and update the image content.

### The container (`ReplaceableImage.jsx`)
``` javascript
const mapStateToProps    = (state) => {
  return {
    draggable: true,
    className: "ow-replaceable-image",
  }
};
const mapDispatchToProps = (dispatch, ownProps) => {
  return {
    onDrop:      (files) => {
     /* I need ownProps here to identify in which column the updated content goes */
      dispatch(fileDropped(files, ownProps.columnId));
    },
    onDragStart: (event) => {
      const src = event.target.getAttribute('src');
      dispatch(setDraggingImage(src));
    }
  }
};

export default connect(mapStateToProps, mapDispatchToProps)(Dropzone);
```

### Container usage
``` javascript
<ReplaceableImage columnId={getId(this.props)}>
   /* getId just return an id */
    <img
        src={this.props.props.src}
        alt={this.props.props.alt}
    />
</ReplaceableImage>
```

## What I hope to do
For me I must to keep passing `columnId` by `ownProps` to use it in `mapDispatchToProps` and then, use a function to filter the properties (I've written one).
After filtering I want to completely override the `ownProps` variable with the filtered one.

**Comment by jimbolla** [comment]
You can:
```js
function mergeProps(stateProps, dispatchProps, ownProps) {
  return {
    ...stateProps,
    ...dispatchProps,
    // filter only the ownProps you want here...
  };
}

export default connect(mapStateToProps, mapDispatchToProps, mergeProps)(Dropzone);

```

**Comment by mafzst** [comment]
@jimbolla Can I remove props with this function ?

**Comment by mafzst** [comment]
@jimbolla Thanks a lot :+1: 
I(ve misunderstood this function
