### ISSUE TITLE
render is called in the wrong order for connected nested components

### ISSUE THREAD

**Issue by ynonp** [reactjs/react-redux#509]
Consider the following where both components are connected to a store:

```
<Parent>
  {hasChild && <Child />}
</Parent>
```

hasChild is a parent prop that is received from store.

If a single action changes both hasChild and a separate property that affects the child, first Child's render is called and only then Parent's render is called removing Child from the tree (unlike normal react flow)

Currently I used shouldComponentUpdate in `Child` to prevent redundant renders, but that involves implementing shouldComponentUpdate in every case. 

Any ideas for a generic solution?

**Comment by jimbolla** [comment]
This is fixed in v5, which is currently in prerelease. You can try it out by `npm install react-redux@next`

**Comment by epeli** [comment]
You can also workaround this by enabling batched updates http://stackoverflow.com/questions/38099512/redux-child-receiving-props-before-parent/38102408#38102408

**Comment by ynonp** [comment]
Thanks @epeli this worked very well! BTW is this the way you solved it in v5?

**Comment by jimbolla** [comment]
Nope. Doesn't rely on batched updates. Basically, control the order of subscriptions to always fire top-down. Details are in #416 and #407 if you're curious.

**Comment by Mythli** [comment]
Is there a way to turn that on or is it on by default? Cuz I'm struggling with the same issue > v5.

**Comment by Mythli** [comment]
cloneDeep though does not resolve the issue - it was something else that worked: If I move the component to another nesting level everything starts working fine... Which I can totally not explain myself.

State corruptiuon is therefore ruled out and I'm out of my wits :(

This is the test case (which is working fine).
https://codesandbox.io/s/p2wm6r8nj

Would you be willing to do a review together? My company is willing to pay for that of course.

Best regards
