### ISSUE TITLE
Action subscription in components

### ISSUE THREAD

**Issue by iLikeKoffee** [reactjs/react-redux#512]
Sometimes I want to subscribe my components on actions. 

For example:
- `LoginFormContainer` should redirect user to some page when `LOGIN_FULFILLED` action is dispatched
- `CommentFormContainer` should show [alertify.js](http://alertifyjs.com/) popup when `COMMENT_CREATE_FULFILLED`

I understand that I can implement this with flags in store and `componentWillReceiveProps` lifecycle method. Also, this is achievable with store, which can be found in context or custom middleware. But I think both ways are not very convenient.

I propose adding one more wrapper to `react-redux` which will be called `subscribe`. Example usage:

```
export default subscribe(/* some configuration which should be discussed */)(SubscribedComponent)

/*Or, in combination with connect */

export default connect(/*...*/)(subscribe(/* some configuration which should be discussed */)(SubscribedComponent))

/*
I know, that combination with connect function seems not very beautiful, but decorators can save us (I hope, one day we will se them in ECMAScript standard)
*/

@connect(/*...*/)
@subscribe(/*...*/)
export default class SomeContainer extends Component{

}
```

I created a [gist](https://gist.github.com/iLikeKoffee/b85c9c6c5a0f0f4608ff1128cd54fc00) with `subscribe` pseudo-code implementation

P.S. The other way is adding one more argument to `connect()` and implementing action subscription there. As for me, I don't think that this is a good idea, but it should be discussed.

P.P.S If there will be a PR with such functionality, has it chance to be merged? Or action subscription contradicts with redux/flux philosophy?

**Comment by timdorr** [comment]
This doesn't fit in with the React lifecycle model. Your component should be willing to change how it renders or does certain things depending on the props passed to it. If you need to handle a particular action, that's business logic that should be encapsulated in your reducer(s). This conflates two separate concerns too directly, leading to coupling and less scalable code.

**Comment by markerikson** [comment]
This is also a good use case for `redux-saga` or other similar middleware.
