### ISSUE TITLE
Legacy warning: <Provider> does not support changing 'store' on the fly

### ISSUE THREAD

**Issue by maullerz** [reactjs/react-redux#527]
It seems, that this [warning](https://github.com/reactjs/react-redux/blob/master/src/components/Provider.js#L13) is no longer relevant.

<img width="601" alt="2016-10-21 16 22 59" src="https://cloud.githubusercontent.com/assets/5295025/19599698/abc0e948-97aa-11e6-9702-25b451e69106.png">

<img width="289" alt="2016-10-21 16 17 23" src="https://cloud.githubusercontent.com/assets/5295025/19599881/32d7080e-97ab-11e6-8a0f-f35e90d3ea07.png">

This is confusing, and does not describe real issue - https://github.com/reactjs/redux/pull/667

**Comment by timdorr** [comment]
If the wording needs improvement, a PR would be best. But the basic idea of not automatically accepting store hot reloads still applies.
