### ISSUE TITLE
lodash causing bad imports in bundled output

### ISSUE THREAD

**Issue by dyakovlev** [reactjs/react-redux#528]
I'm having some bundling issues related to `react-redux` importing `lodash` - getting a couple `require` calls in the output due to the module mixing several different module import styles.

`lodash` import [here](https://github.com/reactjs/react-redux/blob/68a4f2b78671329e10bfca87f8f1c82cc8690459/src/components/connect.js#L6)

original bug and minimal test repo [here](https://github.com/rollup/rollup/issues/1073)

sounds like switching the import to `lodash-es` might fix it...

**Comment by timdorr** [comment]
This is already fixed on the `next` branch. Use that one.

**Comment by kzc** [comment]
Where can I find the official lodash next npm module?

https://www.npmjs.com/package/lodash-next

points to

https://github.com/elierotenberg/lodash-next
