### ISSUE TITLE
document link is broken

### ISSUE THREAD

**Issue by GongT** [reactjs/react-redux#529]
https://github.com/reactjs/react-redux/blob/v4.0.0/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

argument `mapDispatchToProps`:   
link to "bindActionCreators()" is broken

I'm new to redux and react, not sure where is the right document.

**Comment by timdorr** [comment]
Can you submit a PR to update it? Thanks!

**Comment by markerikson** [comment]
FYI, that was broken as of the 4.0.0 tag.  The current version of the file appears to be working-ish, although it points to reactjs.github.io instead of redux.js.org.
