### ISSUE TITLE
Sharing the same store with another Window

### ISSUE THREAD

**Issue by sethcall** [reactjs/react-redux#530]
I have an iframe that I'd like to have re-use the parent window's store.

In my iframe, I have:
```

render(
        <Provider store={callerWindow.store}>
            <Popup />
        </Provider>,
        document.getElementById('root')
    )
```

Where callerWindow.store is the store created in the parent window.

However, when I change the state of something in the parent window store, the child/iframe does not re-render.   This makes sense to me as both windows have their own React instance... but I have no idea on how to somehow make React in the iframe get triggered/re-run (i.e., setState() called correctly) when the parent window's store changed.

I'm thinking the secret must be in connect.js: https://github.com/reactjs/react-redux/blob/master/src/components/connect.js  

Still looking.  Any pointers would be appreciated!

**Comment by sethcall** [comment]
I haven't figured it out, but I am thinking this is user error.    I'll update this if I find this does indeed work without any special work.

**Comment by sethcall** [comment]
Yes it works as-is.  I just had to get the store from the parent window and pass it in as shown above.  My problem was that my iframe was being cached and I was getting some false negatives.

**Comment by stephmilovic** [comment]
Hey @sethcall . I'm trying to do the same thing and struggling to reach the solution. Would you mind posting a gist?

**Comment by jonshuttfd** [comment]
Old post but I just solved this issue in my own app, which contains an iframe. The iframe then contains another react component). Both share the same store. 

main react app sets a reference to the store on the window level:
`if(document.getElementById('root')) {
  **window.mystore = store**
  render(
    <Provider store={store}>
      <App/>
    </Provider>,
    document.getElementById('root')
  )
}
`

The when I initialize the react app within the iframe I simply reference the store on window.parent.mystore

`if(document.getElementById('preview')) {
  render(
    <Provider store={**window.parent.mystore**}>
      <Preview/>
    </Provider>,
    document.getElementById('preview')
  )
}`
