### ISSUE TITLE
connect() doesn't trigger after dispatch & store is out of sync

### ISSUE THREAD

**Issue by rodeyseijkens** [reactjs/react-redux#531]
So I'm running into the problem that the connect() doesn't trigger after my dispatch and the store is out of sync or something when rendering/updating the component after a route change that fires a new dispatch.

I check my store via the React Context.

``` javascript
  static contextTypes = {
    store: PropTypes.shape({
      subscribe: PropTypes.func.isRequired,
      dispatch: PropTypes.func.isRequired,
      getState: PropTypes.func.isRequired,
    }).isRequired,
  }
```

Then I do a console log of the context.store.getState() on each of the component its life cycles and even in the router after the await store.dispatch().

![The console.log](http://i.imgur.com/KDIah39.png)

A the start of the render function the context.store is suddenly the new data. The props inside of the render function is still the old data because connect() hasn't triggered before the component is getting updated.

My reducer isn't mutating the state its returning new objects like this

``` javascript
case FEED_REQUEST_ACTIVITIES:
  return {
    ...state,
    limit: action.payload.limit,
    page: action.payload.page,
    origin: action.payload.origin,
    isFetching: true,
    didInvalidate: false,
  }
case FEED_RECIEVE_ACTIVITIES:
  return {
    isFetching: false,
    didInvalidate: false,
    limit: action.payload.limit,
    page: action.payload.page,
    origin: action.payload.origin,
    total_count: action.payload.total_count,
    items: action.payload.items,
    lastUpdated: action.payload.receivedAt,
  }
```

Does any of you know the problem and how to fix it.

Thanks.

**Comment by jimbolla** [comment]
Can you try installing `npm install react-redux@next` to see if it fixes your problem?

**Comment by rodeyseijkens** [comment]
Ok I figured it out, I accidentally created a new store every route change on the client side.
Normally it would give the warning that it couldn't be changed on the fly, but apparently it didn't.

Hope this may help other people that have this same function because all the other functionality was working correctly.
