### ISSUE TITLE
shallowEqual dates?

### ISSUE THREAD

**Issue by pcompassion** [reactjs/react-redux#532]
I tried using shallowEqual to compare prevProps and this.props in `componentDidUpdate`

The props seems equal, but shallowEqual says they are not when there's a date object in the props

```
objA[keysA[i]]
Sun Sep 25 2016 00:00:00 GMT+0900 (KST)
objB[keysA[i]]
Sun Sep 25 2016 00:00:00 GMT+0900 (KST)
typeof objA[keysA[i]]
"object"
typeof objB[keysA[i]]
"object"
objA[keysA[i]] !== objB[keysA[i]]
true

```

Is this intended behavior?

**Comment by markerikson** [comment]
Yeah, Date instances are actual objects, and two Dates with the same value are compared by reference, not contents (as far as I know).  See http://stackoverflow.com/questions/492994/compare-two-dates-with-javascript for some info.

For storing dates in Redux, it's generally better to keep them as strings or numeric timestamps, which are serializable and also comparable.

**Comment by pcompassion** [comment]
ah ok.

Just want to clarify, I'm talking about props not state.  

Is using Date instance as props still anti-pattern?

So I guess I need to use different shallowEqual implementation because react-redux's implementation is meant to be used with state.

**Comment by markerikson** [comment]
Ah... think there's some confusion here.

To clarify: as best as I understand it, two Date instances with the same value cannot be compared using reference equality ( `===` ).  Now, if you're literally passing down the exact same Date instance each time, then I think the equality check would return true, but if a new Date instance with the same value is being created and passed down, then the comparison would return false.

So, my working assumption is that it's generally going to be safer to _not_ pass around Date instances, and that you should pass around timestamp values instead.
