### ISSUE TITLE
render() called twice with rn 0.36

### ISSUE THREAD

**Issue by jsappme** [reactjs/react-redux#536]

**Comment by jimbolla** [comment]
Can you provide more information?

**Comment by jsappme** [comment]
absolutely, here is my code:

class App extends Component {
  constructor(props) {
    super(props)
  }

  render() {
    console.log("this will be displayed twice");
    return (
      <View style={{flex: 1}}>
      </View>
    )
  }

}

export default connect(mapStateToProps)(App)

"react": "15.3.2",
"react-native": "0.36.1",
"react-redux": "^4.4.5",
"redux": "^3.6.0",

**Comment by jimbolla** [comment]
There are times when react-redux has to call a component's `render` twice, mostly related to child components dispatching actions on mount. Without seeing a complete code sample, I can only assume that's what you're running into.

**Comment by jsappme** [comment]
You can see the complete code at https://github.com/jsappme/react-native-firebase-starter

**Comment by markerikson** [comment]
Not seeing anything actionable here.
