### ISSUE TITLE
JSPM can't find a react-redux version that matches react@^15.4.0

### ISSUE THREAD

**Issue by JoaoMosmann** [reactjs/react-redux#544]
When I try to install react-redux using jspm I get the following message:

`Installing npm:react-redux@4.4.6, no version match for npm:react@^15.4.0`

However, looking into the package.json, it seems to be correct.

`"react": "^0.14.0 || ^15.0.0-0 || ^15.4.0-0",`

**Comment by bennybrau** [comment]
Yep.  React hasn't released this yet.

**Comment by jimbolla** [comment]
15.4 is current in RC.  `react@next` points to `15.4.0-rc.4`.

**Comment by timdorr** [comment]
Is this a bug in jspm? It sounds like it.

**Comment by bdwain** [comment]
i think this is how node semver is expected to behave

> ^1.2.3-beta.2 := >=1.2.3-beta.2 <2.0.0 Note that prereleases in the 1.2.3 version will be allowed, if they are greater than or equal to beta.2. So, 1.2.3-beta.4 would be allowed, but 1.2.4-beta.2 would not, because it is a prerelease of a different [major, minor, patch] tuple.

**Comment by JoaoMosmann** [comment]
Currently, I'm using react@15.3.2. I'm not an expert in versioning, but it seems that 15.3.2 doesn't match any of the versions required by react-redux. Is that right ?

**Comment by JoaoMosmann** [comment]
It definitely looks like a JSPM bug.

I tried from scratch using npm `npm install react redux react-redux` and it installed everything.

However, doing the same with jspm `jspm install react redux react-redux` it throws t he same error.

**Comment by JoaoMosmann** [comment]
The problem was that the version 0.16.* of **jspm** doesn't support  ` || ` in dependencies version.

With the **jspm@0.17.0-beta4** I was able to overwrite the peerDependencies.

Issue created on jspm repo: jspm/jspm-cli#2173

**Comment by timdorr** [comment]
Ah ha! I was right! 😄 

Thanks for the follow up, @JoaoMosmann
