### ISSUE TITLE
Custom component based on example not working?

### ISSUE THREAD

**Issue by xavicolomer** [reactjs/react-redux#547]
Hi there,

I'm trying to create a widget to upload an image with the correct width and height. I was following the documentation but it throws an Error at the very beginning. Is the documentation up to date?

http://redux-form.com/6.2.0/docs/api/Field.md/

(...)
1. A component

This can be any component class that you have written or have imported from a third party library.

// MyCustomInput.js
import React, { Component } from 'react'

class MyCustomInput extends Component {
  render() {
    const { input: { value, onChange } } = this.props
    return (
      <div>
        <span>The current value is {value}.</span>
        <button type="button" onClick={() => onChange(value + 1)}>Inc</button>
        <button type="button" onClick={() => onChange(value - 1)}>Dec</button>
      </div>
    )
  }
}
Then, somewhere in your form...

import MyCustomInput from './MyCustomInput'

...

<Field name="myField" component={MyCustomInput}/>
(...)

Throws:

`warning.js:36 Warning: Failed prop type: Invalid prop 'component' supplied to 'ConnectedField'`

**Comment by jimbolla** [comment]
This isn't the repo for redux-form. You want https://github.com/erikras/redux-form

**Comment by xavicolomer** [comment]
Sorry! Too-many-hours
