### ISSUE TITLE
Extending commected components to include a Debug Widget

### ISSUE THREAD

**Issue by avanderhoorn** [reactjs/react-redux#548]
If I wanted to augment a connected component so that a little UI decoration is added which indicates various debug info, how would I be best to do this? I'm thinking that I want to make more visible the selectors that run, how long they took, etc. 

We are finding that unless we are keeping an active eye on these details, its easy for the team to let regressions slip in and having that front and center might help. Plus its a good way to learn/scratch an itch.

**Comment by markerikson** [comment]
I've got links to a few component render monitoring utils and approaches as part of my Redux addons list, at https://github.com/markerikson/redux-ecosystem-links/blob/master/devtools.md#component-update-monitoring .  Those might serve as useful inspiration (particularly the "render visualizer" pieces).

**Comment by avanderhoorn** [comment]
Thanks!
