### ISSUE TITLE
mapStateToProps is not called if entity is from initialState

### ISSUE THREAD

**Issue by BjornMelgaard** [reactjs/react-redux#551]
When I asynchronously remove project ...

```js
export const removeProject = project => (dispatch) => {
  if (!isProjectExist(project)) return Promise.resolve()
  return projectService
    .delete(project)
    .then(
      () => {
        dispatch(remove(project))
        console.log("post removeProject resolved")
      },
      handleError,
    )
}
```
.... that was created after initialization ([by reducer](https://github.com/BjornMelgaard/react-test/blob/master/app/assets/javascripts/reducers/projects.js)) - it will be deleted and properly unmounted, but when project was passed as `initialState` -  `ProjectList` will [not call](https://github.com/BjornMelgaard/react-test/blob/master/app/assets/javascripts/components/ProjectList.js#L52) `mapStateToProps` (even if `{ pure: false }` in `connect`) and `ProjectItem` try to render itself with stale data, and fail, as in picture
 
![27-13 02 41](https://cloud.githubusercontent.com/assets/7573215/20648258/9421630e-b4aa-11e6-8c11-c807bed2d985.png)

It looks like reducer return changed data, but I use immutablejs

[This issue on stackoverflow](http://stackoverflow.com/questions/40823843/component-is-not-unmount-after-its-delete-in-store) (pictures are not the same, more info)

versions of libraries - most resent

**Comment by markerikson** [comment]
I'm not entirely sure I follow what exactly your problem is, but as a guess: it sounds like the child component is re-rendering before the parent is.  This is a known issue with React-Redux v4 and earlier.  The v5 beta fixes that issue.  Try installing `react-redux@next` and see if that takes care of your problem.

**Comment by BjornMelgaard** [comment]
@markerikson wow, thanks, I'll try))

**Comment by BjornMelgaard** [comment]
It worked!!!
