### ISSUE TITLE
More Redux confusion

### ISSUE THREAD

**Issue by kprovance** [reactjs/react-redux#552]
https://twitter.com/beeva_es/status/802953966069825536:  You guys need to put an end to this shit, NOW!!  That is OUR image they are using, and links to our site, in which we get support questions for YOUR product!  Redux Options Framework has NOTHING WHATSOEVER to do with React.  Nothing!  ZIP, ZERO!!!  Change the bloody name, and stop doing this.  Anymore marketplace confusion which impedes our work, and you can rest assured it'll go to the attorney level quickly..

**Comment by kprovance** [comment]
This has to go to, the image and the references to our website.  https://www.beeva.com/beeva-view/tecnologia/si-cuidas-tu-capa-de-presentacion-por-que-no-la-de-datos/

A;ternatively, you can begin paying us for each of your clients who come to us for help, to redirect them to you...otherwise they may not like the response they get from me.  In fact, I'm sure they won't.

We warned you about this, the theft of our Redux name, and you chose to ignore it.  NO more.

**Comment by timdorr** [comment]
That is a 3rd party posting a blog post. We have no control over this sort of thing. This is not our doing and not representative of the authors and maintainers of this project. Please contact the folks at beeva.com to have this resolved.
