### ISSUE TITLE
component module exports

### ISSUE THREAD

**Issue by msimonc** [reactjs/react-redux#553]
I switched my JSX components to module.export their class in order to get router driven chunking of the bundle to work.  Migrating to redux but none of these work:

module.exports = connect(mapStateToProps, mapDispatchToProps)(FuelSavingsPage);
// throws: TypeError: Cannot call a class as a function.

module.exports = {
	FuelSavingsPage: connect()(FuelSavingsPage)
};

export default connect(mapStateToProps, mapDispatchToProps)(FuelSavingsPage);

All help appreciated,

**Comment by jimbolla** [comment]
This would be better asked on stackoverflow.com. Also, I don't think you've provided enough information to troubleshoot your issue.
