### ISSUE TITLE
Why most guideline separate every types?

### ISSUE THREAD

**Issue by ssuhat** [reactjs/react-redux#559]
Hi, I'm curious why most guidelines of separate every types?

for example:
    
     //List of Posts
    FETCH_POSTS: 'fetch_posts',
    FETCH_POSTS_SUCCESS: 'fetch_posts_success',
    FETCH_POSTS_ERROR: 'fetch_posts_failure',

    // Single POST
    FETCH_POST: 'fetch_post',
    FETCH_POST_SUCCESS: 'fetch_post_success',
    FETCH_POST_ERROR: 'fetch_post_failure',

I've got the idea within success and error got separated. But for `fetch_posts` and `fetch_post` that only has one job to trigger ex: `isLoading` why it must got separate?

Thanks

**Comment by jimbolla** [comment]
See http://redux.js.org/docs/recipes/ReducingBoilerplate.html
