### ISSUE TITLE
v5.0.0-rc.1 breaking Internet Explorer

### ISSUE THREAD

**Issue by iotch** [reactjs/react-redux#560]
Current latest `@next` version published on npm is v5.0.0-rc.1, which is uses `Array.prototype.find` that [not supported by IE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility). It seems find was removed since then but new version was not released.
thanks

**Comment by jimbolla** [comment]
New version will be soon. In the meantime, a polyfill should add `find` for you.
