### ISSUE TITLE
Provider children error after updating

### ISSUE THREAD

**Issue by zabojad** [reactjs/react-redux#561]
I've updating redux, reat-redux and react on my project and now, this:
```
var tmp = React.createElement(myproject_view_Application.Reduxed,{ });
ReactDOM.render(React.createElement(Provider,{ store : store},tmp,"\t"),win.document.querySelector("#app"));
```
throws:
```
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `Provider`, expected a single ReactElement.
Uncaught Error: React.Children.only expected to receive a single React element child.(…)
```

I do not understand as I correctly give a sigle child to my Provider component... This was working with react 15.1.0 and react-redux 4.4.5.

I'm having this issue with react 15.4.1 and react-redux 4.4.6.

**Comment by jimbolla** [comment]
You're passing `tmp` and `"\t"` as children to `Provider`. Provider expects a single child. Get rid of the second one.
