### ISSUE TITLE
Does mapDispatchToProps run more than once?

### ISSUE THREAD

**Issue by davegri** [reactjs/react-redux#563]
I was under the impression that `mapDispatchToProps` runs only once.
I'm trying to increase application performance using the following guide:
http://benchling.engineering/deep-dive-react-perf-debugging/

Inside the guide there is a Mixin I'm using which tells me about avoidable updates. (A prop is deeply equal but not shallowly, causing an avoidable render)

Some of the output I'm getting is about functions that come from `mapDispatchToProps`. Could it be that mapDispatchToProps is run more than once? how is this possible? What am I missing?

**Comment by jimbolla** [comment]
If your `mapDispatchToProps` function depends on props (has args length !== 1) then it's called anytime the component receives new props.
