### ISSUE TITLE
[Question]: why does withRef require an opt-in ?

### ISSUE THREAD

**Issue by toranb** [reactjs/react-redux#571]
As someone trying to port the react-redux connect api to ember I'm curious why you require a `opt-in` for withRef instead of supporting this out of the box? Just curious

Thank you in advance

**Comment by gaearon** [comment]
IIRC because React prints a warning if you put a ref on a functional component and we didn't have a good way to detect functional components at the time. Also (less importantly) refs put some additional work on React and it's nice to avoid it.

**Comment by toranb** [comment]
@gaearon thank you much!
