### ISSUE TITLE
is it possible to connect inside of a render method?

### ISSUE THREAD

**Issue by lostrouter** [reactjs/react-redux#572]
example:
```
import { connect } from "react-redux";
import React from "react";
import foo from "./foo";

export default React.createClass({
    render() {
        return (
            <div>
            {connect(state => state)(foo)}
            </div>
        );
    }
});
```

when i do something like this, i don't get any errors or rendered markup.

**Comment by markerikson** [comment]
I... _think_ that may be technically legal?  But I have absolutely no idea why you'd want to do that, and it's probably not going to be good for performance.

Why _are_ you trying to do that?

**Comment by lostrouter** [comment]
So, I have an SPA and I'm using react-router.  foo is essentially a child route's component.  I want to write something like the above because I want to guarantee all child route components get a common set of props.

**Comment by markerikson** [comment]
In a strange coincidence, I actually just helped answer a sorta-similar-ish question elsewhere.  I think what you really want is to connect the parent component, and use `React.cloneElement()` to pass the additional props on to each child.  See the example here: http://stackoverflow.com/questions/40054774/how-can-i-pass-props-to-children-of-react-router

**Comment by lostrouter** [comment]
right. so that works if i want to connect the parent.  i don't want to connect the parent because i want to compartmentalize state listeners.  Like in your example, I would likely have the header and footer connected independently.  It's possible I may want to connect all three in this one react component.

**Comment by jimbolla** [comment]
Every call to connect is going to return a new component. So React will unmount the old and mount the new on every render. That will be bad for performance.

**Comment by timdorr** [comment]
Yeah, this isn't a best practice. `connect()` establishes a higher-order component, which you only have to do once (normally at the top level of the module where you export the component from). Doing it in your `render` will recreate the component definition every time, so you'll be rerendering on every change (basically what would happen if React didn't do reconciliation). 

I would establish separate route components and connected container components. That might be a bit pedantic, but I find it scales well and keeps your concerns separate enough to avoid problems or subtle bugs.
