### ISSUE TITLE
5.0.0 key "storeSubscription" is not defined in childContextTypes.

### ISSUE THREAD

**Issue by mschipperheyn** [reactjs/react-redux#573]
Tried the new version against react-native 0.38.1 (react 15.4.0-rc.4), but no joy

<img width="369" alt="screen shot 2016-12-14 at 11 57 58" src="https://cloud.githubusercontent.com/assets/384959/21184684/b7ef164e-c1f4-11e6-855f-ddb639a7ac7e.png">

**Comment by jimbolla** [comment]
We're gonna need more details.  Connect definitely defines childContextTypes.

**Comment by mschipperheyn** [comment]
Ok, what kind of details do you need? I can give you some of my code setup:


index.ios.js
	
	import './app/dev/Reactotron';
	import { AppRegistry } from 'react-native';
	import Root from './app/App';

	AppRegistry.registerComponent('Ology', () => Root);

	

App.js

	
	import React from 'react';
	import { Provider } from 'react-redux';
	import { MenuContext } from 'react-native-popup-menu';
	import UIContainer from './modules/navigation/components/UIContainer';
	import routez from './resources/routez';

	import { styles } from './MSA';

	import configureStore from './store/configureStore';
	const store = configureStore();

	export default class Root extends React.Component {

		render() {
			return (
		  <Provider store={store}>
			  <MenuContext style={styles.stretch}>
				  <UIContainer
					  routes = {routez}
				  />
			  </MenuContext>
		  </Provider>
			);
		}
	}
	

configureStore.js
	
	import { createStore, applyMiddleware, compose } from 'redux';
	import thunkMiddleware from 'redux-thunk';
	import loggerMiddleware from 'redux-logger';
	import rootReducer from './reducers';
	import { persistStore, autoRehydrate } from 'redux-persist';

	import { middleware as netInfoMiddleware } from '../modules/connection/middleware';

	import config from '../config';

	const initialState = {};

	export default function configureStore() {

		let enhancer;

		if(__DEV__) {

			const Reactotron = require('reactotron-react-native').default;
			const createReactotronEnhancer = require('reactotron-redux');
			const reactotronEnhancer = createReactotronEnhancer(Reactotron);

			enhancer = compose(
		  reactotronEnhancer,
		  applyMiddleware(
			thunkMiddleware,
			netInfoMiddleware,
			loggerMiddleware(),
		  )
		);
		}else{

			enhancer = compose(
		  applyMiddleware(
			thunkMiddleware,
			netInfoMiddleware,
		  )
		);
		}

		const store = createStore(rootReducer, initialState, enhancer);

		if (module.hot) {
			module.hot.accept('../reducers', () => {
				const nextRootReducer = require('./reducers').default;
				store.replaceReducer(nextRootReducer);
			});
		}

		return store;
	}

**Comment by jimbolla** [comment]
Ah. I think you're overwriting Connect's childContextTypes with your own. Try changing `NavigationContainer.childContextTypes = { ... }` to `NavigationContainer.WrappedComponent.childContextTypes = { ... }`

**Comment by mschipperheyn** [comment]
Thanks. That seems to do the trick. I wonder if this should be documented?

I also noticed that if using the following style, I avoid this issue altogether. It seems more elegant

     class NavigationContainer extends React.Component {
          static childContextTypes = {
             navigator	: PropTypes.object.isRequired
          }

**Comment by jimbolla** [comment]
Docs might help, although I wonder how many people would remember that. I think that's part of the downside of decorators. It looks like you're setting a field on one thing, when really you're setting it on another thing. It's a little more obvious when you write it the "traditional" way.

```js
@connect(...)
class NavContainer extends Component { ... }
NavContainer.childContextTypes = { ... }
```
is equivalent to
```js
class NavContainer extends Component { ... }
const NavContainerConnector = connect(...)(NavContainer)
NavContainerConnector.childContextTypes = { ... }
```

**Comment by mschipperheyn** [comment]
Well, at least its documented here for posterity. Maybe it will help someone as well. Thx!

**Comment by jimbolla** [comment]
If you think there's a good spot in the docs to talk about this, a PR would be welcome.
