### ISSUE TITLE
UMD build confusingly renamed in v5

### ISSUE THREAD

**Issue by Phoenixmatrix** [reactjs/react-redux#574]
So, I was upgrading one of our packages that use the UMD build, and noticed that the output was renamed in [this commit](https://github.com/reactjs/react-redux/commit/746c4506ba705e286cf15807096b76958282b5b8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R11)

It's a little confusing for react-redux to just be called redux. I kind of feel it was just an oversight.

Any thoughts?

**Comment by jimbolla** [comment]
I'm guessing that was a mistake. Want to submit a PR?

**Comment by Phoenixmatrix** [comment]
Yup will do, just wanted to be sure it wasn't intentional first.

**Comment by jimbolla** [comment]
@btd, Any insight on this?

**Comment by btd** [comment]
@jimbolla looks like just copy paste mistake. Sorry.

**Comment by timdorr** [comment]
I'll get this fixed up now and push out a 5.0.1 (we need that anyways for the HMR fix).

**Comment by btd** [comment]
@timdorr thanks 👍

**Comment by timdorr** [comment]
Published! https://unpkg.com/react-redux@5.0.1/dist/react-redux.js

**Comment by Phoenixmatrix** [comment]
thanks a bunch!
