### ISSUE TITLE
Failed building after upgrading from 5.0.0-beta.3 to 5.0.1

### ISSUE THREAD

**Issue by fabiozaffani** [reactjs/react-redux#578]
Hi,

Currently i'm having some problems after updating the package.json of my app from 
`"react-redux": "5.0.0-beta.3",`
to
`"react-redux": "5.0.1",`

The thing is, after I update this everything seems to run fine and without any problems in my localhost, but the app fails to compile in Heroku.

After rolling back to the beta version everything works fine at heroku again.

Maybe the problem isn't with react-redux and it's on heroku part, but since this is the only change made I think it was worth mentioning it here.

**Comment by jimbolla** [comment]
What's the error?

**Comment by fabiozaffani** [comment]
```
       impallets@5.3.0 /tmp/build_7d195506ac77fb369a73dea7700755a7/onyxcorp-onyx-app-49f2a80a3452d551cfedc20bc14c2b9b9a5bb06d
       ├── UNMET PEER DEPENDENCY react-addons-shallow-compare@^0.14.0 || ^15.0.0
       ├── UNMET PEER DEPENDENCY react-redux@5.0.1
       └── UNMET PEER DEPENDENCY webpack@2.1.0-beta.22
       
       npm ERR! code 1
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

If needed, i can put the entire stack trace from node

**Comment by jimbolla** [comment]
Well that's not super useful. Could you try beta2, beta3, rc1, rc2 to narrow down when this error started?

**Comment by gaearon** [comment]
Or maybe the whole stack so that it's clearer what exactly is failing. :-)

**Comment by jimbolla** [comment]
@fabiozaffani What is your current status with this?

**Comment by timdorr** [comment]
Closing due to lack of feedback. I haven't heard of anyone else with a similar problem.
