### ISSUE TITLE
mapStateToProps not always called after upgrading to 5.0.1

### ISSUE THREAD

**Issue by tleunen** [reactjs/react-redux#582]
I have a boolean value inside a reducer and the `mapStateToProps` is not always called when the value changes.

Here's the log from 4.4.6:
```
[mapStateToProps] showResults false
[reducer] previous value: false ; new value: true
[mapStateToProps] showResults true
[reducer] previous value: true ; new value: false
[mapStateToProps] showResults false
```

But here's the one from 5.0.1:
```
[mapStateToProps] showResults false
[reducer] previous value: false ; new value: true
[mapStateToProps] showResults true
[reducer] previous value: true ; new value: false
[reducer] previous value: false ; new value: false
```

**Comment by tleunen** [comment]
I wonder if this is related to an "app" within another app and maybe the relations between the stores are wrong since the upgrade?

**Comment by markerikson** [comment]
Can you post a sample project that demonstrates this issue?  Your second comment makes it sound like your setup is more complicated than "just" a store and some components.

**Comment by tleunen** [comment]
I can try to create a new project.

But basically it's something like this:

```
<Provider store={store}>
  <MainApp />
</Provider>
```

With MainApp being:
```
<div>
  <div>Something</div>
  <OtherApp />
</div>
```
OtherApp:
```
<Provider store={otherStore}>
  <MiniApp />
</Provider>
```

**Comment by markerikson** [comment]
Ah... hold on.  So you're using _two_ different `<Provider>` instances, with the second nested inside the first?  Are you updating the first store, but expecting a component inside the second `<Provider>` to respond to that update?  Because if so, I really don't think that's a supported or expected scenario.

**Comment by jimbolla** [comment]
The inner `Provider` is shadowing the `store` context property, but not `storeSubscription`, so the connected components inside the inner `Provider` are incorrectly subscribing to store changes from the outer `Provider`'s store. Easy enough to fix by changing `Provider` to also shadow `storeSubscription`, but it does beg the question "How much support does react-redux offer for multiple stores?"

**Comment by tleunen** [comment]
> Are you updating the first store, but expecting a component inside the second <Provider> to respond to that update?

Nop. Everything inside the "mini app" is self contained. So something inside send an action and update its own reducer. I only expect the mini app to be updated. The "parent app" has nothing to do with that.

I'm making another small project to reflect the issue. Stay tuned.

@jimbolla Maybe it's not the usual use case, but I'm having the issue because my "mini app" can live as a standalone application, but also embedded inside another app.

**Comment by tleunen** [comment]
See this project: https://github.com/tleunen/react-redux-pr582

**Comment by markerikson** [comment]
@jimbolla : I'd say that if we can fix it without much hassle, then we might as well go ahead and do so.  Sounds like it's "just" a matter of adding a couple more entries to context, right?

**Comment by jimbolla** [comment]
Yep. Just submitted PR #584 to fix this use case.
