### ISSUE TITLE
[Question] About areOwnPropsEqual

### ISSUE THREAD

**Issue by DevSide** [reactjs/react-redux#585]
Context

```js
const mapStateToProps = (state, props) => ({
  foobar: calculation(state.bar, props.foo)
})

const areStatesEqual = (nextState, state) => nextState.bar === state.bar
const areOwnPropsEqual = (nextOwnProps, ownProps) => nextOwnProps.foo === ownProps.foo
```

In this context, If my component gets a prop updated other than `foo` then no render occurred.
( http://codepen.io/DevSide/pen/RoOjxP )

But in most cases, I'd like to just avoid a  `mapStateToProps` call and eventually make the `shouldComponentUpdate` of my component decide about re-rendering. 

Is there any perspective to get this kind of behavior ? (using memoized selectors apart)

**Comment by jimbolla** [comment]
Overriding `areStatesEqual` and `areOwnPropsEqual` will bypass the whole render cycle if they both return true, so that's not going to work for your use case. A memoized selector *is* the appropriate place to get that behavior.
