### ISSUE TITLE
when mapStateToProps is a factory and has one, the new method does not get ownProps

### ISSUE THREAD

**Issue by lukeapage** [reactjs/react-redux#604]
```
mapStateToProps(initialState) {
    return (state, ownProps) => {
         // ownProps is undefined
    };
}
```

It works fine with no arguments or 2 arguments..

**Comment by markerikson** [comment]
What version of React-Redux are you using?  Can you provide an example snippet that demonstrates the problem?

Also, what happens if the outer `mapState` function also requests `ownProps` as an argument?

**Comment by lukeapage** [comment]
5.0.1 and when you give 0 or 2 args, it succeeds, but fails with 2

**Comment by markerikson** [comment]
Hmm.  That's interesting, because if I'm reading the current source right, it _looks_ like it does an initial check against the outer function to check the arity, and if it's a factory function, does a second check against the inner function: https://github.com/reactjs/react-redux/blob/3c5c80e757c4f6e4127fb10d5b6ccd8c88aead6c/src/connect/wrapMapToProps.js#L54 .

**Comment by lukeapage** [comment]
Sorry for the long delay, here is what is happening..

first time through it runs: https://github.com/reactjs/react-redux/blob/3c5c80e757c4f6e4127fb10d5b6ccd8c88aead6c/src/connect/wrapMapToProps.js#L43
because there are no own props needed.

because its a factory, it hits this if which is true
https://github.com/reactjs/react-redux/blob/3c5c80e757c4f6e4127fb10d5b6ccd8c88aead6c/src/connect/wrapMapToProps.js#L52

and then it calls the proxy again, passing ownProps
https://github.com/reactjs/react-redux/blob/3c5c80e757c4f6e4127fb10d5b6ccd8c88aead6c/src/connect/wrapMapToProps.js#L55

except that the ownProps it passes is undefined, because the outer function didn't need it.

So, it does set dependsOnProps correctly and the 2nd time it calls the function it has ownProps, but the first time, it doesn't.
