### ISSUE TITLE
Component can't render when it's name begin with lowercase letter

### ISSUE THREAD

**Issue by crimsonskyrem** [reactjs/react-redux#606]
Hello there,

I've just had this problem with writting my first redux app.

when I use 

`export default connect()(todoApp)`(note that todoApp begin with lowercase t)

then it just can't render anything in my page

however, when I eventually change the code to 

`connect()(TodoApp)`

it works fine.

does anyone know why this happen?

**Comment by markerikson** [comment]
This is a usage question, and should be asked on StackOverflow instead.  It's also hard to give an answer without actually seeing your code.  Please go post this question on StackOverflow, and include your code in the question.

**Comment by jimbolla** [comment]
I'm gonna guess you're also changing the casing at the callsite? Because JSX treats tags starting with a lower as a literal html tag and tags starting with an upper as a component.

**Comment by crimsonskyrem** [comment]
@jimbolla Oh,you're right, thanks
