### ISSUE TITLE
Question: peformance tuning for mapStateToProps

### ISSUE THREAD

**Issue by cjpete** [reactjs/react-redux#607]
Hi,

I have a very data-intensive application, which combines data from a number of sources before passing it to a component which then hands off to several presentational components for rendering.

The mapStateToProps call (which runs, as I understand, on every state change), does some pre-filtering/mapping of the data before passing it to the component. This, in the case of arrays, obviously changes the object reference, which will cause a re-render (I currently have no logic in componentShouldUpdate()).

Would you expect the component itself to stifle these renders through componentShouldUpdate, or are there any optimisations which can be made in mapStateToProps to not pass props to the component where the raw values haven't changed?

Thanks,
Chris

Edit: I have added some logic to the componentShouldUpdate method, to not render while it is mid-fetching. Since we display a loading indicator on the page while the data is being fetched, this cuts down on many render calls, which helps a little with the painting/blocking.

**Comment by markerikson** [comment]
This is generally where memoized selector functions are useful.  When the same inputs are given, the same result object can be returned.  That's definitely helpful for cases like filtering or sorting data.

My recent blog post [Practical Redux Part 6: Connected Lists, Forms, and Performance](http://blog.isquaredsoftware.com/2017/01/practical-redux-part-6-connected-lists-forms-and-performance/) covers some of the key concepts regarding good Redux performance, and links to a number of other useful references on the topic.
