### ISSUE TITLE
Props not being passed into connected component in react native

### ISSUE THREAD

**Issue by sguo35** [reactjs/react-redux#608]
https://stackoverflow.com/questions/41818343/props-not-being-passed-into-component-when-using-react-native-router-flux-with-r 

Code/github and description of the issue in the link. I've checked to make sure the component is connected properly, made sure mapStateToProps is correct, and made sure my reducer is correctly implemented (redux logger says the store is correctly being updated). Is something wrong with redux or is my code wrong?

**Comment by markerikson** [comment]
Definitely a usage question and not a library bug, so I'll close this.

However, glancing at your code, I think your `mapState` function is wrong.  You should be returning `state.session.success`, not `state.success`.
