### ISSUE TITLE
[RFC] optimized connect with dependencies

### ISSUE THREAD

**Issue by Andarist** [reactjs/react-redux#611]
I was wondering if it is possible to implement easily on top of existing APIs such a concept - a connected component seting its dependencies (often in runtime, but mainly upon component creation only) so they can be grouped and handled internally, so the mere top state change is not enough to fire all subscription functions.

Possible use case - multiple dynamic lists in the app where each item is a connected one.

However from what I see `connect` and `connectAdvanced` are not sufficient for this, so more internal / undocumented APIs would have to be used.

What do you think about the concept?

**Comment by jimbolla** [comment]
I don't really understand what you're suggesting.

**Comment by Andarist** [comment]
Sorry if I have phrased it in a confusing way, was writing it pretty late in the night.

The idea is to create such a `connect` which would be capable of tracking registered dependencies (via `reselect` for example) for components so they could be grouped internally. It would mean that not every state change would trigger each listener in the `connect` for each connected component, but it would only fire more relevant ones.

Imagine 2 lists of 100 items, each item connected. If we can scope them by some different dependency we could skip their listeners compeltely (if some irrelevant part of the state tree changes) or only fire 100 listeners (if only dependency of their interest changes and not the other one) instead of 200.

**Comment by timdorr** [comment]
That is really up to your mapStateToProps function. Avoiding calling that listener wouldn't really net you much performance benefit. Most of the work comes from actually re-rendering your component. If the state mapped to your props doesn't change, that render doesn't have to happen. So, you're already doing this there, but just on the other side of the subscription. A few hundred function calls (especially when they happen often, meaning they get optimized by the compiler) are not going to have any notable impact on performance.

**Comment by Andarist** [comment]
I realize that `mapStateToProps`'s results are optimized under the hood, even on compiler level and not only in the lib itself. However surely even when thats get optimized to some extent those calls are still somewhat expensive if there are too many of them.

Recently in the `redux-saga` someone has noticed (after investigating the real life perf issue) that we subscribe internally each task (and they might be plenty of them) to the action stream (and situation is there somewhat worse than in case of react-redux cause we need to notify subscribers about all actions, not only after state change) and that caused him a perf issue cause he had hundreds of tasks not even depending on the actions. We'll be optimizing this, so we create only a single, global for `redux-saga` emitter of those actions so each task can subscribe to this independently - resulting in only some listeners in the opposite of the situation when each task got its own instance of the subscriber anyway.

This situation led to me think about this idea and when I realize it might be unnecessary for most apps, I think it might be worthwile to think about such a possibility. If you still think its completely futile leave it closed.
