### ISSUE TITLE
Best practice for dispatching different actions in a single prop

### ISSUE THREAD

**Issue by pazams** [reactjs/react-redux#613]
A colleague and I ran into the following scenario:
- A component `Foo` has many props, of which one with type `func` is of our interest. e.g.:
```JS
Foo.propTypes = {
  toggle: PropTypes.func.isRequired, // toggled is passed a bool value
};
```

- 2 different existing redux actions need be dispatched from that `prop`. e.g.:

```JS
'SHOW_FOO' // action.type
'HIDE_FOO' // action.type
```

- **The restrictions**: The component interface cannot be changed, and we have to make use of the 2 existing actions.

Possible implementations:
1. Use conditional inside action creator:
```JS
if(isSelected){
  createAction(SHOW_FOO),
}
else {
  createAction(HIDE_FOO),
}
```

2. Use conditional inside the container's mapDispatchToProps:
```JS
function mapDispatchToProps(dispatch) {
  return {
    toggle: function(isSelected) {
      var action = isSelected ? createShowFooAction() : createHideFooAction()
      dispatch(action);
    }
  }
```

Other alternatives such as using a single action with a payload are not feasible due the restrictions mentioned above.

**Arguments for first approach:**
" action creators is already a place designated for application logic. Introducing logic inside the container makes it harder to expect where to find logic. "

**Arguments for second approach:**
" The job of the container is to decouple actions and components, therefore this logic should be inside the container. "

Which approach would be the best practice?

**Comment by ZephD** [comment]
imo 2) is ideal, as it correctly maps dispatches (any dispatches...) to the specific prop (in this case, 'toggle').

**Comment by timdorr** [comment]
It really depends on how you intend to use that boolean. If it's only useful in the context of the component, then the 2nd answer makes sense (and it sounds like you might only need some local state for it instead of Redux). If you need to do that kind of thing throughout your application, then moving it to your action creator makes more sense. Either form is valid and it depends on your particular use case.
