### ISSUE TITLE
Combine components the same way you combine reducers

### ISSUE THREAD

**Issue by simlrh** [reactjs/react-redux#617]
Many reducers can be combined into one while remaining responsible for their own section of the state tree. They aren't required to know about the whole app, only their own state changes.

Components receive the whole state tree in mapStateToProps, so they need to know their position within the app as a whole to find the state relevant to them. It would aid reusability if components could be composed so that they only receive the state relevant to them.

(PR incoming)

**Comment by timdorr** [comment]
Let's keep the discussion in #618
