### ISSUE TITLE
react-redux unable to push next redux state as props?

### ISSUE THREAD

**Issue by nealoke** [reactjs/react-redux#620]
For some reason react is not re-rendering when the (redux) state changed. Might it be because it is nested 1 level? 

Also **in the Redux inspector I can see that the state has changed correctly and as expected**. On manually refreshing the page, I can also see that it worked. But I am confused on why it is not pushing the new props to the component.

Also when using the `console.log(state.users)` inside the `mapStateToProps` I can see that the new state arrives but again doesn't push these props to the react component.
```
function mapStateToProps(state) {
	console.log(state.users);

	return {
		users: state.users,
		departments: state.departments
	};
}
```

**Simplified Class Component**
```
class Users extends Component {
    render() {
        const something = this.props.users.users;

        return (
            <div>
                <div className='MAIN_SECTION'>
                    <SearchBar handleChange={(value) => this.setState({searchQuery: value})} />

                    <div className='LIST'>
                        {something.mapObject((user) => <div onClick={() => this.props.deleteUser(user.id)}>{user.name}</div>)}
                    </div>
                </div>
            </div>
        );
    }
}

function mapStateToProps(state) {
    return {
        users: state.users
    };
}

export default connect(mapStateToProps, { deleteUser })(Users);
```

**Action Creator**
```
export function deleteUser(userhash) {
    return function (dispatch, getState) {
        return new Promise(resolve => setTimeout(resolve, 1000)).then(() => {
            const data = {
                status: 200,
                data: {
                    status: 200
                }
            };

            if (data.status === 200) {
                const newState = getState().users.users;
                delete newState[userhash];

                dispatch({
                    type: DELETE_USER,
                    payload: {
                        data: newState
                    }
                });
            }
        });
    };
}
```

**Reducer**
```
const INITIAL_STATE = {
    isFetching: true,
    users: {}
};

case DELETE_USER:
    return {
        ...state,
        users: action.payload.data
    };
```

**Comment by jimbolla** [comment]
You're mutating your state:
```
const newState = getState().users.users;
delete newState[userhash];
```

Change it to
```
const newState = { ...getState().users.users };
delete newState[userhash];

```

**Comment by nealoke** [comment]
@jimbolla I didn't know that this was mutating the state 👍 . However the issue at hand is not resolved by implementing the suggestion. I still have the exact same behavior. Any other things that this could cause?

**Comment by nealoke** [comment]
@jimbolla Also when using the destructuring redux no longer updates the state correctly. It says the state is equal. See attachements

**Redux state**
![image](https://cloud.githubusercontent.com/assets/17417414/22855927/375eacb6-f088-11e6-81d9-17e898acf029.png)
 
**Action**
![image](https://cloud.githubusercontent.com/assets/17417414/22855936/5325649e-f088-11e6-9b8c-2cf4f528a18e.png)

**Diff**
![image](https://cloud.githubusercontent.com/assets/17417414/22855940/6b3be026-f088-11e6-8092-1005ca647446.png)
