### ISSUE TITLE
Usage of PropType show a lot of warning in console, issue located at components/Provider.js 

### ISSUE THREAD

**Issue by dbyzero** [reactjs/react-redux#627]
Hi,

I'm on a fresh project with followng depencecies : 

```
  "dependencies": {
    "axios": "^0.15.3",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "lodash": "^4.17.4",
    "react": "^15.4.2",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-logger": "^2.8.1",
    "redux-promise-middleware": "^4.2.0",
    "write-file-webpack-plugin": "^3.4.2"
  },
  "devDependencies": {
    "babel-core": "^6.23.1",
    "babel-loader": "^6.3.2",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.23.0",
    "cordova": "^6.5.0",
    "css-loader": "^0.26.1",
    "file-loader": "^0.10.0",
    "json-loader": "^0.5.4",
    "node-sass": "^4.5.0",
    "sass-loader": "^6.0.0",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.3.0"
  }
```

I got the following errors in console : 

![selection_307](https://cloud.githubusercontent.com/assets/2214094/23098005/95172958-f643-11e6-8e56-64a5c0b41194.png)

I check code and find this : 

https://github.com/reactjs/react-redux/blob/shouldntComponentUpdate/src/components/Provider.js#L48

I'm new on react-redux looks like this code is responsible of warnings.

Regards.

**Comment by NE-SmallTown** [comment]
I think you should see the links at the end.[dont-call-proptypes](https://facebook.github.io/react/warnings/dont-call-proptypes.html#if-you-dont-call-proptypes-directly-but-still-get-the-warning),the explanation is clear and detailed.After you reading,you will realize that you should check the `storeSubscription`.

**Comment by timdorr** [comment]
You're probably doing this: https://github.com/reactjs/react-redux/issues/614#issuecomment-276469100

The fix is to define your propTypes inline with your component or not use the decorator form of `connect`.

**Comment by markerikson** [comment]
I knew I'd seen this message somewhere recently, but that wasn't actually ringing a bell.  That's what I get for answering so many questions in so many different places :)  Nice catch!

**Comment by gaearon** [comment]
I still don't understand why this is happening 😄 
Can somebody explain to me what triggers the warning in this case?

**Comment by gaearon** [comment]
Note that https://github.com/reactjs/react-redux/issues/614#issuecomment-276469100 is a different issue. This is not the same warning message.

**Comment by gaearon** [comment]
@dbyzero Where is `react-dom` in your dependencies? It is possible you get this problem because you have mismatching versions of `react` and `react-dom`. Verify you have only one of each in `node_modules`, and that their versions are exactly the same.

**Comment by dbyzero** [comment]
I don't know how but after a npm install, it disappear. I was hacking `console.error` to avoid this annoying message but recently I test it again and it's ok now...

Sorry for the late answer.
