### ISSUE TITLE
did not get defaultProps from mapStateToProps params of ownProps

### ISSUE THREAD

**Issue by kingangelAOA** [reactjs/react-redux#633]
version: "react-redux": "^5.0.2";
es6

set defaultProps in Component

static defaultProps = {
        flagId: randomString()
    };

const tableStateToProps = (state, ownProps) => {
    const {flagId} = ownProps;
    const {dataToTableSelector, pagingDataSelector} = tableSelectors;
    return {
        tableData: dataToTableSelector(state.ployReducer)[flagId] || [],
        pagingData: pagingDataSelector(state.ployReducer)[flagId] || []
    }
};
key flagId not in ownProps
ownProps has:
children: null
location: Object
params: Object
route: Object
routeParams: Object
router: Object
routes: Object

**Comment by markerikson** [comment]
`ownProps` will contain props that were passed into the wrapper component generated by `connect`.  So, if you want those `defaultProps` values to be available in `mapState`, you need to set them on the wrapper component, not the component you pass to `connect`.

**Comment by nextofsearch** [comment]
@markerikson Can you please give me a simple example code for it? I will appreciate it.

**Comment by markerikson** [comment]
Ah... as a quick sketch, something like this:

```js
const MyComponent = (props) => <div>{props.someItem}</div>;

const mapState = (state, ownProps) => {
    const someItem = state.items[ownProps.itemName];

    return {someItem}
}

const ConnectedMyComponent = connect(mapState)(MyComponent);

ConnectedMyComponent.defaultProps = {
    itemName : "theItem"
};
```

**Comment by nextofsearch** [comment]
@markerikson Thank you so much!

**Comment by enriquecaballero** [comment]
Is this a new thing? It seems to me that `connect` would always preserve a component's `defaultProps`. Not complaning, I'd just like to know if this has always been the case with `connect`.

**Comment by markerikson** [comment]
I don't _think_ that `connect` has ever proxied/passed through any `defaultProps`.  Would have to dig through the history to be sure, but off the top of my head, no.

**Comment by dandigangi** [comment]
Hey @markerikson, just wanted to bump this again for a quick question... what is the best way to handle the need for a default prop in the mapStateToProps?

I'm finding myself doing things like this... which seems 😕

```
const mapStoreToProps = ({ vehicles, user }, { vehicleId }) => ({
    isLoading: vehicles.details.isLoading,
    windowStickerImageUrl: vehicles.details[vehicleId].windowStickerImageUrl || null,
})
```

**Comment by markerikson** [comment]
First, as a general observation, I'd suggest using selector functions to encapsulate those lookups, rather than destructuring the contents of the `state` argument.  From there, you could write your selectors to fall back to default values if the relevant item doesn't exist.

**Comment by dandigangi** [comment]
Yeah... a holiday break todo. I guess it stands to reason then that I can have the selectors themselves (or if I use reselect) to provide the fallbacks unless there's a particular reason to do the fallback in the component.

Thanks for the feedback.

**Comment by wsmd** [comment]
Ran into similar issue and ended up here! @markerikson's [suggestion](https://github.com/reduxjs/react-redux/issues/633#issuecomment-299768271) works fine and makes perfect sense!

It seems to me that it's very conventional to `connect` right on `export default`:

```js
// ...

export default connect(mapStateToProps)(MyComponent);
```

So I think it would be nice to hoist the `defaultProps` from the wrapped component and pass them to the `mapStateToProps` via `ownProps`.

> I don't think that connect has ever proxied/passed through any defaultProps

Given that `defaultProps` is essentially a static on the `WrappedComponent `, isn't this line supposed to take care of that though.. or _at least_ get us there?

https://github.com/reduxjs/react-redux/blob/d16f759d727359fde3cc141cfc068fd13f184de8/src/components/connectAdvanced.js#L288-L289

If not, an explanation would be much appreciated! 😅

**Comment by markerikson** [comment]
@wsmd : nope, because that's specifically "hoist _non-React_ statics".  You can see the whitelist here:  [hoist-non-react-statics/index.js](https://github.com/mridgway/hoist-non-react-statics/blob/95bf2a2abf2112cefb9f1224dc436d1615e5174d/src/index.js).

**Comment by CharlieEarnup** [comment]
This seems a little bit bizarre! Why wouldn't you merge `defaultProps` with `ownProps` in the `mapStateToProps`? Seems like that should be expect behavior, I can't think of a situation where I would want it otherwise.

**Comment by markerikson** [comment]
@CharlieEarnup : because, as discussed earlier in the thread - when someone defines `MyPlainComponent.defaultProps = {}`, the assumption is that the props are meant for _that_ component only.  The odds of a user actually wanting to apply those default props to the wrapper component are nonexistent.

If you want to define default props for the wrapper component generated by `connect()`, you can do that yourself:

```js
const MyConnectedComponent = connect()(MyPlainComponent);
MyConnectedComponent.defaultProps = {};
```

**Comment by jneuendorf** [comment]
@markerikson This makes perfect sense to me. For everyone running into this problem, this is how we handle it:

- We have a `@subscribe` decorator. This is basically a wrapper around `connect`.
- Using a wrapper lets us use our own convention for mapping static properties. In our case we map `defaultConnectorProps` to `defaultProps` on the connected component:

```javascript
@subscribe
class MyComponent extends React.Component {
  static propTypes = {
    // ...
  }
  static defaultProps = {}
  static defaultConnectorProps = {
     somePropThatWillBeAvailableIn_ownProps_argument: 1,
  }
}
```
