### ISSUE TITLE
Problem with lodash-es dependency, when build production bundle with webpack

### ISSUE THREAD

**Issue by anagami** [reactjs/react-redux#634]
Hi!
I analizing my build and find lodash-es inside. On project have different libs, which use old lodash.
In result bundle i have two copy of lodash
![Alt text](https://monosnap.com/file/YgiUJ4GOVdyhrtKbLsaW1clsQDXW4B.png)

Have some way for load redux@5 with old lodash?
Thx!

**Comment by gaearon** [comment]
React Redux should only use a couple of small functions from Lodash. I’m confused why you seem to have a whole library there. Can you share an example project reproducing this?

**Comment by anagami** [comment]
Sorry, yes problem with another lib, clean install react-redux build only few methods lodash-es
