### ISSUE TITLE
use connect for enabling dispatch and pass props

### ISSUE THREAD

**Issue by reut-co** [reactjs/react-redux#638]
how can I use the connect function and pass props from the parent component to the wrapped one ? I don't want to use the mapStateToProps ownProps option since it will subscribe the component to store events although it has no dependency on it..

**Comment by markerikson** [comment]
The wrapper components generated by `connect` already forward any props to the wrapped component.  If I render `<ConnectedComponent a={42} b="stuff" />`, then the wrapped component has `props.a` and `props.b` automatically.  The `ownProps` argument to `mapState` is literally just those props that were given to the wrapper component.

This mini-version of `connect` may help illustrate what's going on: https://gist.github.com/gaearon/1d19088790e70ac32ea636c025ba424e .
