### ISSUE TITLE
FEATURE REQUEST: Accept object as a valid `mapStateToProps` argument

### ISSUE THREAD

**Issue by josepot** [reactjs/react-redux#644]
I think that it would be very convenient to accept an object as a valid `mapStateToProps` argument. In which case, each function inside it would be assumed to be a Redux selector.

I always use reselect and I would love to be able to do:

```
connect({
  foo: fooSelector,
  bar: barSelector,
})
```

instead of doing the verbose:

```
connect(createStructuredSelector({
  foo: fooSelector,
  bar: barSelector,
})
```

I know that this is just sugar, but I think that it would be very convenient. In the same way that I love the fact that I can pass an object with action-creators as a valid `mapDispatchToProps` argument, I would like to be able to pass an object with selectors in the `mapStateToProps` argument.

**Comment by markerikson** [comment]
This has been brought up quite a few times.  There's already an open PR with a possible implementation over in #323 , although progress on it seems to have stalled.  I'll close this as a dupe, since that PR would cover this.

**Comment by josepot** [comment]
Sorry about that @markerikson, I did check the opened Issues but I didn't checked the opened PRs. Well, I hope that PR gets merged soon. Thanks!

**Comment by markerikson** [comment]
No worries, and thanks!
