### ISSUE TITLE
SystemJS is convinced that dist/react-redux.js is or requires an ES6 module

### ISSUE THREAD

**Issue by kurtinatlanta** [reactjs/react-redux#649]
SystemJS will not load react-redux, which, in turn, makes it harder to use with TypeScript, as SystemJS wants to load a transpiler when loading react-redux.js.

Since the file is directly loadable with a script tag, I'm guessing that it's not really (nor does it contain) an ES6 module.

Is there a way to fix this? Or is this something that is not reconcilable between react-redux and SystemJS?

**Comment by gaearon** [comment]
I'm sure a minimal repro would help!

**Comment by timdorr** [comment]
Are you using plugin-typescript? Skimming this issue, it seems relevant to your error: https://github.com/frankwallis/plugin-typescript/issues/185

**Comment by kurtinatlanta** [comment]
I am putting together the repo now and will update here as soon as it's ready.

I am not using plugin-typescript since I'm doing all the TypeScript transpiling on the server side and I can make this happen without using TypeScript at all.

I did create a solution/workaround with Babel that seems to re-transpile react-redux in the browser since I have to point SystemJS to the source code instead of dist/react-redux.js.

The repo I am creating will walk through all the steps I took.

**Comment by timdorr** [comment]
Honestly, I can't figure this one out. Looking at the UMD for redux vs react-redux, I don't see any big differences. The 0th module both export with __esModule = true, both appear to be the same format of output, and have the same webpack header block. 

Unfortunately, I think this is more of a SystemJS bug or issue. I'm not a particular expert on it, so I'm not able to offer much assistance. And you'll probably find a more well-versed subject matter expert over there. If we're doing something wrong on our end, I'm more than willing to push a new fixed build, but I don't think I have any knobs I can fiddle with to try and make it work. Sorry!

**Comment by kurtinatlanta** [comment]
Thanks for taking a look at it! I'm sure it's all part of the newness of all these moving parts we are using to build modern apps. Hopefully the module standards shake out and resolve all of this soon.

**Comment by mattdell** [comment]
I’ve come across this issue a year later, but I don’t see an accepted solution for this.

I’m using ts-loader to compile my code to ES5 but SystemJS insists that it needs a transpiler. The error only goes away when I remove react-redux.
