### ISSUE TITLE
Provider is undefined

### ISSUE THREAD

**Issue by arsenalol69** [reactjs/react-redux#652]
Hello every one ! I had a problem with redux : I create a simple application with this tutorial : https://medium.com/@jonlebensold/getting-started-with-react-native-redux-2b01408c0053#.ridphemkc

But it's impossible to my to import Provider from react-redux :(
I did :
`import {Provider}  from 'react-redux'`
But Provider is undefined and it result in this exception when I try to use it :

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

Any idea ?

Here is the version of my packages :
"react": "15.4.2",
    "react-native": "0.42.0",
    "react-redux": "^5.0.3",
    "redux": "^3.6.0",
    "redux-logger": "^2.8.2",
    "redux-thunk": "^2.2.0"

Thanks in advance !

**Comment by ugogo** [comment]
Are you sure that the `undefined` is for `Provider`?
Did you tried to `console.log(Provider)`, right after the import?

**Comment by arsenalol69** [comment]
@ugogo  Yes that's what I did ... console.log(Provider) print "undefined" .. :(

**Comment by ugogo** [comment]
@arsenalol69 Can you provide a repo so that we can have a look?

**Comment by arsenalol69** [comment]
@ugogo Thanks for your help :) Here is the git repo : [https://github.com/arsenalol69/react-redux-exemple](url)

**Comment by ugogo** [comment]
@arsenalol69 Hah, you're using react-native. Redux 5^ is not supported. Please refer to the [README](https://github.com/reactjs/react-redux#react-native) 😉

**Comment by arsenalol69** [comment]
@ugogo The Readme says that 
> React Redux 5.x should work with React Native

I also try to run `npm ls react` and I only have `-- react@15.4.2`
So it should work no ?

**Comment by ugogo** [comment]
My bad, read too fast 😬 
Sorry I can't help you though, never used react-native

**Comment by timdorr** [comment]
Can you import anything from the react-redux module, or is it just Provider that's not working? Have you tried removing the `node_modules/react-redux` folder and trying to install it again? Perhaps you got a bad download.

**Comment by arsenalol69** [comment]
@ugogo No problem :) Thanks for your help !
@timdorr I just tested to delete the folder, and re-install the module again but still the same problem ..

**Comment by jimbolla** [comment]
Seems like something weird with your build config, but I know nothing about React Native. What if you try to import it in a Jest test?

**Comment by arsenalol69** [comment]
@jimbolla I don't understand why u want me to try a Jest test ? I has never used it and it will just try to run the project as I do myself... Maybe I just misunderstood the utility of the tool...

**Comment by arsenalol69** [comment]
I found a solution : instead of `import { Provider }  from 'react-redux'`, I write : `import { Provider }  from 'react-redux/src'` and it works 😄  Explication : I ckecked inside the react-redux's nodemodule folder and the export command was inside the src folder...

**Comment by timdorr** [comment]
You can also try the es folder too. It's transpiled, but leaves the import/export statements alone. 

Regardless, that's definitely some sort of build config issue. Glad you found a workaround!

**Comment by lloydbanks** [comment]
In case if you're coming from google and using TypeScript, you should also install types for react-redux: `npm install @types/react-redux`
