### ISSUE TITLE
dynamic images in local

### ISSUE THREAD

**Issue by rafaelbsconsult** [reactjs/react-redux#657]
How to do require local dynamic image with require ?

my code 
```
 render(){
         let image =  require(this.props.data.image)
        return(
            <View>
                <Image source={image}/>
            </View>
        );
    }
```

**Comment by markerikson** [comment]
Sorry, this isn't related to Redux (or even React-Redux) at all.  

I can tell you that Webpack needs all `require` or `import` statements to be statically analyzable at compile time, so that won't work as you want.
