### ISSUE TITLE
When mapStateToProps has an arity of 2, pass dispatch to ownProps

### ISSUE THREAD

**Issue by Jahans3** [reactjs/react-redux#661]
Recently I've started trying to cut down the pattern of passing `mapStateToProps`, `mapDispatchToProps` and `mergeProps` into `connect` because there seems to be a lot of redundancy there.

I have been experimenting with only passing a single function to `connect`; I have been able to achieve everything I would normally seek to achieve by simply using `mapStateToProps` with an arity of 2. The only problem is when I need `dispatch`.

Currently I am dealing with this in two ways:

Ideal scenario, in which I am using another library, in this case Redux-Form, which will allow me to get `dispatch` from `ownProps` at the start of my `mapStateToProps` function:

```
@reduxForm({
  form: 'someForm',
  validate: validateSomeForm
})
@connect((state, ownProps) => {
  const { x, y, z } = state
  const { dispatch } = ownProps

  const openSomething = () => {
    // Do something before dispatch
    // ...
    dispatch(Actions.openSomething)
  }

  return {
    ...ownProps,
    openRegistration
  }
})
export default someClass extends Component {
...
```

Less than ideal scenario (but, in my opinion, still better than passing three functions to `connect`). In this scenario I wrap whatever would use `dispatch` in a function that takes `dispatch` as an argument, and within the class I can get `dispatch` from `this.props` and pass it in.

```
@connect((state, ownProps) => {
  const { x, y } = state
  const { z } = ownProps

  const openLogin = dispatch => {
    // Do something before dispatch
    // ...
    dispatch(Actions.login)
  }

  return {
    ...ownProps,
    openLogin
  }
})
export default someClass extends Something {

  someMethod () {
    const { dispatch } = this.props
    openLogin(dispatch)
  }
```

How do others feel about this? Do you guys think it would be a good change to allow us to have all the functionality of `mapStateToProps`, `mapDispatchToProps` and `mergeProps` in one function?

Personally, I feel it would be worth it to cut down on this pattern with inherent redundancy:

```
@connect(
  state => ({ state }),
  dispatch => ({ dispatch }),
  ({ state }, { dispatch }, ownProps ) => {
    // do something
  }
)
export default someClass extends Component { 
...
```

**Comment by jimbolla** [comment]
This pattern would create a new `openLogin` function every time store state changed, causing this component to re-render every single time. That would be very bad. You shouldn't do this, but if you want to, you can implement it in userland by coding your own wrapper on `connectAdvanced`.

**Comment by Jahans3** [comment]
@jimbolla So if the function was defined inside `mapDispatchToProps` or `mergeProps` it would not cause a re-render?

**Comment by jimbolla** [comment]
MapDispatch: Only when receiving new props, never because of state. MergeProps: Only if mapState or mapDispatch produced a new value, not great either. 

My personal opinion is that the only form of `mapDispatch` that should be used is the object notation. So you would have `connect(mapState, { openLogin: Actions.login })`.

**Comment by Jahans3** [comment]
@jimbolla Thanks for your explanation, quite informative.

Could I pass `pure: true` to `connect`'s `options` param, and since I'm not using anything from the state and therefore won't be mutating the given props, achieve what I wanted in my original post?
