### ISSUE TITLE
index.d.ts provides incorrect typings for connect

### ISSUE THREAD

**Issue by yhaskell** [reactjs/react-redux#667]
As for now, the following typing is provided:
```typescript
export declare function connect<TStateProps, TDispatchProps, TOwnProps>(
    mapStateToProps?: MapStateToProps<TStateProps, TOwnProps> | MapStateToPropsFactory<TStateProps, TOwnProps>,
    mapDispatchToProps?: MapDispatchToProps<TDispatchProps, TOwnProps> | MapDispatchToPropsFactory<TDispatchProps, TOwnProps>,
    mergeProps?: MergeProps<TStateProps, TDispatchProps, TOwnProps>,
    options?: Options
): ComponentDecorator<TStateProps & TDispatchProps, TOwnProps>;
```

Problem lies in the following type:
```typescript
type MapDispatchToProps<TDispatchProps, TOwnProps> =
    MapDispatchToPropsFunction<TDispatchProps, TOwnProps> | MapDispatchToPropsObject;
```
This makes it impossible for typescript compiler to deduce TDispatchProps from the second parameter of connect function. 

Essentially, we need to do the following:

1) remove `MapDispatchToPropsObject` and `MapDispatchToPropsFunction`
2) change `MapDispatchToProps` type to the following:
```typescript
type MapDispatchToProps<TDispatchProps, TOwnProps> = TDispatchProps;
```

Please note that it only will automatically deduce types if component has no `TOwnProps`. That will change when either typescript/#4183 or typescript/#13470 will land.

**Comment by timdorr** [comment]
These typings aren't on this repo. Please open this on the repo where you obtained them from.
