### ISSUE TITLE
No errors caught when a state change triggers re-render

### ISSUE THREAD

**Issue by danielrs** [reactjs/react-redux#671]
Basically what the title says. I'm using `react-redux` in my `react-native` app. I was having some problems with some bugs without any errors at all. After messing with the code I managed to find the cause for the problems I'm having:

```js
import React, { Component } from 'react';                                                                                  
import { Button, Text, View } from 'react-native';
import { connect } from 'react-redux';

import DivisionAction from '../../actions/division';

class DivisionIndexView extends Component {
  constructor(props) {
    super(props);
    this.state = {showNumbers: false};
  }

  componentDidMount() {
    const { dispatch } = this.props;
    dispatch(DivisionAction.requestDivisions());
  }

  _handlePress = () => {
    this.setState({showNumbers: !this.state.showNumbers});
  }

  render() {
    let nums = []; 
    // >>> CHECKPOINT 1
    if (this.state.showNumbers) nums = [1, 2, 3]; 
    const numbers = nums.map((n) =>
        // >>> CHECKPOINT 2
        <DoesnExists key={n}>{n}</DoesnExists>
    );  

    return (
      <View>
        <Button title="Toggle numbers" onPress={this._handlePress} />
        {numbers}
      </View>
    );  
  }
}

const mapStateToProps = (state) => {
  // state.division reducer has a boolean `loaded` field.
  return state.division;
}

export default connect(mapStateToProps)(DivisionIndexView);
```

The previous code triggers an error when you press the button. Each time the button is pressed, state.showNumbers changes between `true` and `false`; when it is true, it makes the array `nums` (CHECKPOINT 1) equal to some elements which are then used to render the non-existing element `<DoesntExits>...</DoesnExists>` (CHECKPOINT 2).

The previous error is expected, however, if I change `this.state.showNumbers` at CHECKPOINT 1 to `this.props.loaded`, I get no errors at all, the element just doesn't render.

**I'm not sure** if this error is caused by `react-redux`, however, that seems to be the case. Maybe the way `react-redux` triggers a re-render is conflicting in some way?

**Comment by markerikson** [comment]
I'm sorry, I'm very unclear on what's going on here.  What error are you seeing, specifically, or at least expecting to occur?  Can you create an example that reproduces the problem?

**Comment by danielrs** [comment]
@markerikson Alright, I'm working on an example right now :smile:

**Comment by danielrs** [comment]
I apologize, the minimal example I just made worked as expected. I'll edit my question once I find the real culprit.

**Comment by danielrs** [comment]
Solved! Turns out I wasn't calling `.done()` after a Promise chain in my action creator (`.requestDivisions()`).
