### ISSUE TITLE
Is it a good idea to fetch network resources in mapStateToProps

### ISSUE THREAD

**Issue by coodoo** [reactjs/react-redux#678]
Use case is: while mapping `article` object from redux store using `mapStateToProps`, if article's body hasn't be fetched, run an action to fetch the data from API server.

Three questions:

1. Is this a good idea?

2. If so, how to run the action within `mapStateToProps`, since `dispatch` is not available there?

3. If not, what's the suggested approach for this scenario?

**Comment by timdorr** [comment]
Nope, I would do this in a plain lifecycle hook. You have more control that way anyways.

**Comment by coodoo** [comment]
The reason behind doing so is that I want to make the component a real dumb one, handling no data fetching and stuff, hence needing to fetch the data somewhere else, any suggestion?

**Comment by gaearon** [comment]
If you need to fetch data your component is already not simple. I'd embrace it instead of trying to work around the fact.
