### ISSUE TITLE
dispatch one more times but only the first time is synchronous

### ISSUE THREAD

**Issue by yezihaohao** [reactjs/react-redux#684]
I just dispatch three times :

```
    const { dispatch, searchCondition } = this.props;
    dispatch(trendSearch(50, 'sortEnum'));
    dispatch(trendSearch(1, 'pageNo'));
    dispatch(trendSearch(0, 'rowOffset'));

    console.log(searchCondition);
```

But i only got the value of the key sortEnum changed, why?

How can i dispatch in the correct way?

I want all the value of sortEnum, pageNo, and rowOffset changed synchronously.

**Comment by timdorr** [comment]
Dispatching will immediately fire off changes in your state tree to be rendered. If you need to change multiple fields at once, you need to create a single action that will change all of them at once.
