### ISSUE TITLE
warning: Accessing PropTypes

### ISSUE THREAD

**Issue by mhebrard** [reactjs/react-redux#687]
Hello I use `create-react-app`
then use `react-redux` in the app

I get a warning
```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

but i scan all my files and I use `prop-types` everywhere...
do I miss something ?

**Comment by markerikson** [comment]
React 15.5 has added a new warning to let people know that the library is changing.  This means that one of the other libraries you're using has not been updated yet to switch from `React.PropTypes` to `prop-types`.

**Comment by jimbolla** [comment]
Here's how to figure out which one: https://twitter.com/brian_d_vaughn/status/851110928720445443

**Comment by mhebrard** [comment]
Thanks for the useful link. and sorry for flooding your issues.
I get the info I wanted :)
