### ISSUE TITLE
State Stale in Render

### ISSUE THREAD

**Issue by coreyperkins** [reactjs/react-redux#690]
I am working with Redux 3.6.0, I haven't yet attempted an upgrade to the latest version. I wanted to chunk this out there because I feel like it is something I am doing that could be useful to others.

I have a component that is making a dispatch and receiving the correct results in mapStateToProps. But I have noticed that in the render my state still has the old values in this.state. My dispatch happens after I do a setState as the result of a button click. This seems to be common among all of the components I've built to this point, which leads me to believe I have done something in constructing my reducers.

// component constructor
```
constructor(props) {
    super(props);

    this.state = { 
      IsFetching: false
    };
```
// component button handler
```
    self.setState({ IsFetching: true }, function() {
      self.props.dispatch(getDataAct({ SearchValue: searchValue }));
    }.bind(self));
```

// component render
```
    if (this.state.IsFetching) {
      return (<div>Loading</div>)
    } else {
      return (<div>Loading</div>)
    }
```

// component mapStateToProps
```
const mapStateToProps = (state) => {
  return {
    IsFetching: state.DataReducer.IsFetching
  }
};
```

I was expecting this.state.IsFetching to be updated to false because that is what the reducer returns (as verified via the mapStateToProps). However, once IsFetching is set to true via the button click it remains that way for the remainder of the component's life.

**Comment by markerikson** [comment]
Hi.  A couple thoughts.  

First, the relevant lib version would be for React-Redux, not Redux itself.  For clarity, are you using version 4.x, or 5.x?

Second, this actually looks sorta like the behavior described in @carlsverre 's recent talk: https://github.com/carlsverre/talk-react-redux-learnings .  It may be worth watching his presentation and seeing if that matches what you're seeing.  (Also see a bit of additional discussion in https://github.com/carlsverre/talk-react-redux-learnings/issues/1 ).

Er... waitaminute.  Scratch what I just said, I think.  You seem to be mistaking two different things.  `this.state` is data that's controlled and updated by the component itself.  Any data extracted from the Redux store comes in as _props_  (hence the name, `mapStateToProps`).  So, you should be looking at `this.props.IsFetching`, not `this.state.isFetching`, if you're trying to base behavior off what's in the Redux store.

**Comment by coreyperkins** [comment]
Hi markerikson, the version is 5.0.2, sorry for the mistake there.

I will watch the presentation, too. Every little bit helps. :)

In my original hack I was looking at this.props.IsFetching. However, since props are read-only I decided to shift the logic to look at this.state.IsFetching instead. That way the button click could modify this.state.IsFetching and then the reducer could send back false after the fetch is complete (via mapStateToProps). Perhaps I took the wrong approach there?

**Comment by timdorr** [comment]
What I find works best for this is something like redux-thunk and a Promise. The action creator dispatches to the store, but also returns a Promise you can interact with:
```js
handleClick(e) {
  e.preventDefault()

  this.setState({ fetching: true })
  this.props.doAsyncThing().then(
    () => this.setState({ fetching: false }),
    error => this.setState({ fetching: false, error })
  )
}
```
That way you keep the local UI state to the component, but still get the global stuff into the store.
