### ISSUE TITLE
It is possible and safe to import `storeShape` from `react-redux/utils/proptypes`?

### ISSUE THREAD

**Issue by langpavel** [reactjs/react-redux#692]
I want validate props in my piece of app.

I want import store shape from one single place, I thing, it should be this library.

How I can do this in safe way?

**Comment by timdorr** [comment]
It's generally not a good idea to directly import something from a package, as the layout could change at any time. Instead, you can copy over the proptype to your own application, as it's just a shape with 3 properties. Nothing all that complex.

**Comment by langpavel** [comment]
I'm doing this right now, but because store shape is not really interesting for me and store itself is result of calling redux factory function I think that better is letting redux and it's binding do this for me...

**Comment by langpavel** [comment]
Let me explain more. I have `App` component which wraps all the providers I need, for example `react-intl`, `react-apollo` etc..
I want define propTypes but I really don't want define `store` shape as this is only third party dependency.
I can write this ugly (by my opinion) code..
```js
class App extends React.Component {

  static propTypes = {
    store: ReduxProvider.propTypes.store,
  };

  render() {
    const { store } = this.props;
    return <ReduxProvider store={store}>{this.props.children}</ReduxProvider>;
  }
}
```

**Comment by gaearon** [comment]
Why not define it just as an `object`? If you intentionally don't care about it's exact type.

In my view typing it as shape with `dispatch`, `subscribe`, and `getState` is the best way. Even if you just copy and paste them. Redux API will never change with regards to those three methods.

**Comment by langpavel** [comment]
Hi @gaearon, thank you for answer :+1: 
I should avoid typing it as any or object because we have set [`forbid-prop-types`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md#forbid-certain-proptypes-forbid-prop-types) inherited from airbnb eslint rules.
But, because I only pass store prop down, I can borrow type definition from react-redux's Provider. But I'm not sure if this good code style..

**Comment by gaearon** [comment]
It's perfectly fine.

**Comment by gaearon** [comment]
I mean—as I said, I would suggest just typing it as

```js
store: PropTypes.shape({
  subscribe: PropTypes.func.isRequired,
  dispatch: PropTypes.func.isRequired,
  getState: PropTypes.func.isRequired
})
```

This API won't ever change.
Is there some reason why this doesn't work for you?

**Comment by langpavel** [comment]
It works, of course, I had explicitly described store shape before..
Now I ended with this: https://github.com/kriasoft/react-starter-kit/blob/feature/redux/src/components/App.js#L22
