### ISSUE TITLE
custom storeKey in connect() and Provider conflict

### ISSUE THREAD

**Issue by tleunen** [reactjs/react-redux#693]
`connect` allows the user to set a custom `storeKey`, which is interesting when we have multiple store.

But the `<Provider>` component doesn't allow to set a custom store key. So does `connect()` only work when using the store as prop instead of context?

Will it make sense to add a function to create a custom provider using a specific store key as well?

**Comment by markerikson** [comment]
That's... an interesting question.  I'd noted that @jimbolla added the `storeKey` option, but it didn't click that `<Provider>` still only ever uses `store`.

Jim, any thoughts?

**Comment by jimbolla** [comment]
Right. Current `Provider` can only do `store`. Depending on how much demand there is for that feature, we should either fully implement the Provider half of it, or just remove it completely.

**Comment by timdorr** [comment]
Maybe non-`store` stores can be done like this: `<Provider store={store} stores={{ otherStore, anotherStore, etcStore }}>`.
