### ISSUE TITLE
Prepublish script is not run on prepublish

### ISSUE THREAD

**Issue by zackliston** [reactjs/react-redux#697]
I noticed you have a [prepublish script](https://github.com/reactjs/react-redux/blob/master/prepublish.js) that runs `es3ify` on files. But it appears that this script is [not actually run on prepublish](https://github.com/reactjs/react-redux/blob/master/package.json#L16). This is making it so that the code is not es3 safe.

**Comment by timdorr** [comment]
That's correct. A side effect of 5.0 was dropping old IE support. Anything other than IE 11 is at sub-1% usage and most major sites (FB, Gmail, etc.) have dropped support for anything older than 11. 

If you need old IE support, you can use 4.x, which is API compatible with 5.0.
