### ISSUE TITLE
Is it possible to Suspend/Resume all component re-rendering?

### ISSUE THREAD

**Issue by hepiyellow** [reactjs/react-redux#699]
Hi,

A good title is hard to find for this question.

Is there a way to "suspend" all react-redux re-rendering of components, and the later `resume` it which will cause all the relevant re-renders to occur?
(When I say "suspend" re-rendering, I mean as a result of store state changes by actionReducers)

My case for this, is that I am using also [Mobx](https://mobx.js.org) in conjunction with react-redux.
I need to create a single "transaction" so I can make all Mobx changes and redux store change "atomically", and have the re-renders occur only after the "transaction" is done.

I'd appreciate any ideas...
Thanks,
Erez

**Comment by jimbolla** [comment]
Not really. Your best option is probably to write a custom store enhancer that intercepts `subscribe()`.

**Comment by timdorr** [comment]
Yeah, you'll need to enhance the store to `runInAction` things inside of Redux. It's more on the side of Redux than the React bindings.

**Comment by hepiyellow** [comment]
I found this:
https://github.com/tappleby/redux-batched-subscribe

I have a feeling it solves my need.
I assume react-redux is subscribing to the store, and if I suspend those subscribe callback from being called, then react-redux would not re-render any component, until I use the `notify()` (In `redux-batched-subscribe`, which will get `react-redux` started again.

Thanks !

**Comment by markerikson** [comment]
@hepiyellow : there's actually several ways to implement batching, each with varying tradeoffs:

- Dispatching a `"BATCH"` action with other actions in an array
- Using a middleware
- Debouncing the store notification process
- Allowing an array of items to be passed to `dispatch`, and only notifying once after those actions are dispatched
