### ISSUE TITLE
Perf.printWasted got print when using connect's component

### ISSUE THREAD

**Issue by darwinchyd** [reactjs/react-redux#700]
![](https://cloud.githubusercontent.com/assets/9840254/26160981/d2651970-3b4c-11e7-8590-11542c82812a.png)

Here is a git repo that i create: https://github.com/darwinchyd/perf-wasted-react-redux-connect

This is happen when handle edit comment

I'm curious why this is happen on my container's component(using `connect`) whereas my presentational's component didn't got printWasted at all. Didn't get it ):

Is this possible to remove printWasted of the connect's component(?)

**Comment by timdorr** [comment]
It looks like that button is just setting the title of the article to the same value as before. So, it's "wasted" time because it's not actually changing the DOM in any way after re-rendering. If you actually change the value of the title in some way, I believe that warning will go away.
