### ISSUE TITLE
Small typo on doc for connect's mapDispatchToProps?

### ISSUE THREAD

**Issue by filipewl** [reactjs/react-redux#706]
While reading the documentation for `connect`'s `mapDispatchToProps` the following caught my attention:

> ["[mapDispatchToProps(dispatch, [ownProps]): dispatchProps] (Object or Function):... If you don't want to subscribe to store updates, pass null or undefined in place of **mapStateToProps**..."](https://github.com/reactjs/react-redux/blob/27ab1697d82175e00f34508b3e76d2f17ed894bd/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options)

Shouldn't it be "_If you don't want to subscribe to store updates, pass null or undefined in place of map**Dispatch**ToProps_"? It's the same sentence found in the explanation for `mapStateToProps`.

The rest of the documentation already indirectly covers the case when you pass null or undefined with the "_If you omit it, the default implementation just injects dispatch..._".

I just found it a bit confusing, but it might actually be how it was intented so I decided to ask.

**Comment by naw** [comment]
You're correct that it is confusing.  The sentence is technically correct as-is, but it doesn't belong in that paragraph.  It should be removed altogether.  To be clear, changing the word as you suggested would actually make it incorrect.
