### ISSUE TITLE
Error after freezing store state

### ISSUE THREAD

**Issue by larsbs** [reactjs/react-redux#708]
Hello

I'm monkeypatching the store to freeze the result of `store.getState()` during development and I'm getting a weird error in only one connected component. The error is: 

`Uncaught TypeError: Cannot assign to read only property 'setWrappedInstance' of object '#<Connect>'`

and it's happening on [this line in connectAdvanced.js](https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L124). What's the relation between `getState()` and `connectAdvanced` so that error is happening?

It's related for sure to freezing the state and also to connect the component, what I don't know if it's the main cause of it's an underlying problem that's being triggered by it. But if I remove one of both conditions (freezing the state or connecting the component) the problem goes away.

EDIT:

This is the monkeypatching code in case it provides more context:

```javascript
if (process.env.NODE_ENV === 'development') {
  const oldGetState = store.getState();
  store.getState = () => deepFreeze(oldGetState());
}
```

**Comment by timdorr** [comment]
Are you perhaps putting the wrapped component into state somewhere? I believe that's what the deepFreeze will do if you have it in there somewhere. That will end up making the component's properties frozen. How are you actually connecting the component?

**Comment by markerikson** [comment]
@larsbs : There are several other options for detecting mutations to state in development, including existing middlewares that freeze the state.  You might want to look into those.  See the [DevTools#Linting](https://github.com/markerikson/redux-ecosystem-links/blob/master/devtools.md#linting) section of my Redux addons catalog.

**Comment by larsbs** [comment]
The component is nothing fancy, it's exactly like this:

```javascript
import React from 'react';
import { connect } from 'react-redux';

const Overview = () => {
  return (
    <div>Overview</div>
  );
};

export default connect()(Overview);  // If I remove this line, the error goes away.
```

For now I just disabled the freezing of the state, at this moment, the question is more a curiosity than a real problem, because I have the impression that something is going here under the hood.

@timdorr The wrapped component is a route, but also others, and they're not triggering the error.

@markerikson thanks, I'm gonna have a look.

**Comment by gdub22** [comment]
Noticing this same error show up after a recent `react-redux` upgrade and using `redux-freeze`

**Comment by XronikaM** [comment]
test
