### ISSUE TITLE
connect on superclass doesnt render subclass

### ISSUE THREAD

**Issue by vendramini** [reactjs/react-redux#712]
I've created a superclass for my react native app called Boilerplate. It has the header, a Drawer menu and a floating bottom icon. Also, there's a method called 'content' which is overrated by subclass.

Every other scene extends this superclass, overriding the 'content' method with your own content.

I would like to connect each scene with redux. If I try to connect the Boilerplate, it doesnt work. No errors, no warning, just doesnt render anything.

I do have to connect each scene.

**Boilerplate.js**
```
class Boilerplate extends React.Component {

//subclasse MUST override
content() {}

render() {
  //header
  {this.content()}
  //stuffs
}

const mapStateToProps = (state) => ({
    state
});

export default connect(mapStateToProps, null)(Boilerplate); //I do want this, but i cant.

}
```

**SomeScene.js**
```
class SomeScene extends Boilerplate {
  content() {
    //specific content
  }
}

export default SomeScene; //doesnt work. I do have to connect here each scene to work.
```
Is this a bug? Or is it wrong what I trying to do? Why do 'connect' makes inheritance stop to work?

Just to be clearly: if I connect my scenes instead my superclass, everything works fine.

Thanks.

**Comment by gaearon** [comment]
Using inheritance is (intentionally) not fully supported.
Please read this section explaining how to easily avoid it:

https://facebook.github.io/react/docs/composition-vs-inheritance.html

**Comment by vendramini** [comment]
All clear now. Thank you!
