### ISSUE TITLE
Question about connect api: mapDispatchToProps

### ISSUE THREAD

**Issue by rockchalkwushock** [reactjs/react-redux#720]
I'm hoping someone can explain to me why I'm running into this case with the `connect` api:

```js
connect(null, dispatch => ({ someAction })); // this will work
```

```js
connect(null, { someAction }); // this will fail to provide the actionCreator as props
```

`mapDispatchToProps` is just a function that returns an object holding the key/value pairs of whatever actions I would be passing as props on the component. So I can deconstruct the object as the second argument to `connect` & this has never failed for me before; however, I've ran into this twice now where as soon as a I place my actionCreator for dispatching as the second argument in `connect` I lose the ability to dispatch & my actionCreator is not provided as props on the component as it should be. I've looked into a possible import/export mistakes but I've found nothing. As `handleSubmit` is what is accepting the actionCreator I end up with an error message from `redux-form`; but upon inspection it's that the actionCreator is not being provided by `connect` as expected. I'm wondering if there is a scope issue in my file structure. I say this because if I use the same code, _ using the correct paths_ at the root level I have no issues; but when I run this code in a sub-directory I'm forced to use the `dispatch =>` .

At root level
```js
import { compose, withHandlers, withState } from 'recompose'
import { Field, reduxForm } from 'redux-form'
import { connect } from 'react-redux'

import { getQuestions } from './lib'
import {
  Form,
  Input,
  StyledButton,
  StyledClosingSpan,
  StyledInputHolder,
  StyledSpan,
  StyledWrapper
} from './components/searchCommons'

const enhance = compose(
  connect(null, { getQuestions }), // this format works at root level
  reduxForm({ form: 'searchbar' }),
  withState('view', 'toggle', false),
  withHandlers({
    handleOnClick: props => () => {
      props.toggle(!props.view)
    }
  })
)

// deconstruct props provided by enhance()
const SearchBar = ({ getQuestions, handleOnClick, handleSubmit, view }) =>
  <Form onSubmit={handleSubmit(getQuestions)}>
    <StyledWrapper>
      <StyledInputHolder open={view}>
        <Field
          component={Input}
          name="query"
          open={view}
          placeholder="Search a topic on StackOverflow"
          type="text"
        />
        <StyledButton type="button" onClick={handleOnClick} open={view}>
          <StyledSpan open={view} />
        </StyledButton>
      </StyledInputHolder>
      <StyledClosingSpan onClick={handleOnClick} open={view} />
    </StyledWrapper>
  </Form>

export default enhance(SearchBar)
```

In sub-directory:
```js
import { compose, withHandlers, withState } from 'recompose'
import { Field, reduxForm } from 'redux-form'
import { connect } from 'react-redux'

import { getQuestions } from '../lib'
import {
  Form,
  Input,
  StyledButton,
  StyledClosingSpan,
  StyledInputHolder,
  StyledSpan,
  StyledWrapper
} from './searchCommons'

const enhance = compose(
  connect(null, { getQuestions }), // will not work must be in `dispatch =>` format
  reduxForm({ form: 'searchbar' }),
  withState('view', 'toggle', false),
  withHandlers({
    handleOnClick: props => () => {
      props.toggle(!props.view)
    }
  })
)

const SearchBar = ({ getQuestions, handleOnClick, handleSubmit, view }) =>
  <Form onSubmit={handleSubmit(getQuestions)}>
    <StyledWrapper>
      <StyledInputHolder open={view}>
        <Field
          component={Input}
          name="query"
          open={view}
          placeholder="Search a topic on StackOverflow"
          type="text"
        />
        <StyledButton type="button" onClick={handleOnClick} open={view}>
          <StyledSpan open={view} />
        </StyledButton>
      </StyledInputHolder>
      <StyledClosingSpan onClick={handleOnClick} open={view} />
    </StyledWrapper>
  </Form>

export default enhance(SearchBar)
```

In both cases `<SearchBar />` is provided as a child component in `Home`. Home is wrapped by a composed HOC that includes `withData` which is used for wrapping the component in the `<Provider />` component & giving the component the ability to _connect_ to the reduxStore if the `connect` api is used.

Home
```js
import { Component } from 'react'
import { connect } from 'react-redux'

import { page } from '../lib'
import { SearchBar } from '../components' // sub-directory level

// import SearchBar from '../recomposeSearchBar' // root level

class Home extends Component {
  render() {
    const { questions } = this.props.questions
    return (
      <div>
        <div>
          <SearchBar {...this.props} />
        </div>
        <div>
          <ul>
            {questions.map(q =>
              <li key={Math.random()}>
                <a href={q.link}><h3>{q.title}</h3></a>
              </li>
            )}
          </ul>
        </div>
      </div>
    )
  }
}

export default page(connect(state => ({ questions: state.questions }))(Home))
```

withData
```js
import { Component } from 'react'
import { Provider } from 'react-redux'
import PropTypes from 'prop-types'
import { loadGetInitialProps } from 'next/dist/lib/utils'

import { reduxStore } from '../redux'

/**
 * @function withData
 * @param {Func} ComposedComponent Higher-Order-Function/Component for applying data to components.
 * @returns {Function} Returns component with access to redux store.
 */
export default ComposedComponent =>
  class WithData extends Component {
    static propTypes = {
      url: PropTypes.shape({
        pathname: PropTypes.string.isRequired
      }).isRequired
    }
    static getInitialProps = async ctx => {
      const subProps = await loadGetInitialProps(ComposedComponent, ctx)
      const props = {
        url: { query: ctx.query, pathname: ctx.pathname },
        ...subProps
      }
      return {
        ...props
      }
    }
    render() {
      return (
        <Provider store={reduxStore}>
          <ComposedComponent {...this.props} />
        </Provider>
      )
    }
  }
```

**Comment by markerikson** [comment]
I'm kind of lost on what exactly the problem is here.  Are you saying that in the second example, the `getQuestions` prop is undefined?

Overall, this looks more like a usage question than any actual bug in React-Redux.

**Comment by rockchalkwushock** [comment]
@markerikson 

Yes more of a usage question. I apologize this was hard to write in general because I was confused myself. I've been trying to use HOC's to cut down on the amount of replicated code in my _pages_ with `next` & I believe that is where my trouble with this was stemming. I reverted back to having the code all written out in one _page_ and I'm slowly lifting things back out with  HOC's and have yet to run into this _strange_ usage case again. First time using `recompose` as well. Need to pause and regroup on my understanding of what is happening. 

I apologize for the very poorly defined question / user created problem.

**Comment by dwilt** [comment]
@rockchalkwushock I'm running into this now on this _new_ project I'm on. I can't seem to get the props to pass correctly when just sending in an object to `mapDispatchToProps` but it _does_ pass when I pass a function instead. This is not happening in `4.4.1` but I am experiencing it in `5.0.5`:

This doesn't work:
```js
export default connect(null, {
    goToUtilitySelector,
})(Splash);
```
This does:
```js
export default connect(null, dispatch => ({
    goToUtilitySelector,
}))(Splash);
```

I am `import`ing `goToUtilitySelector` from another file and it looks like this (how I always structure my actions when doing this):
```js
export const goToUtilitySelector = () => dispatch => {
    dispatch(NavigationActions.navigate({
        routeName: UTILITY_SELECTOR_SCENE_KEY,
    }));
};
```

**Comment by dwilt** [comment]
Found the issue: I had a circular dependency.

When I was calling my `connect`, `goToUtilitySelector` was `undefined`. But when I used the callback variation and `dispatch`, it wasn't `undefined` then so it worked. My fault - that one tripped me up.
