### ISSUE TITLE
Most recent typings in @types/react-redux error out with TypeScript 2

### ISSUE THREAD

**Issue by arackaf** [reactjs/react-redux#722]
It seems any attempted use of `connect` as a decorator errors out with TypeScript 2.4.  For example

```ts
@connect(null, actions)
class BookRowRaw extends Component<any, any> {
```

produces the error
> file: 'file:///c%3A/GIT/booklist/react-redux/modules/books/components/bookViewList-grid.tsx'
severity: 'Error'
message: 'Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<any>' is not assignable to type 'typeof BookRowRaw'.
    Type 'Component<any, ComponentState>' is not assignable to type 'BookRowRaw'.
      Types of property 'render' are incompatible.
        Type '() => false | Element' is not assignable to type '() => Element'.
          Type 'false | Element' is not assignable to type 'Element'.
            Type 'false' is not assignable to type 'Element'.'
at: '10,1'
source: 'ts'

I'm using the latest typings from `@types/react-redux`

My current workaround, for anyone here from Google with the same problem, is to use older typings from `typings` (or just make your own, really)

**Comment by timdorr** [comment]
Those typings aren't stored on this repo and we don't maintain them officially. I believe they're on DT. Sorry, but I don't think anyone here can help, unfortunately.

**Comment by arackaf** [comment]
No worries at all - apologies for opening this in the wrong place :)

**Comment by labkey-joshd** [comment]
@arackaf we were previously using the decorators to inject dispatch only, but for what it's worth I was able to get this to work using:

```
const MyComponentImpl extends Component<any, any> { ...

const MyComponentWrap = (props: MyComponentProps & Dispatch<any>) => <MyComponentImpl {...props}/>;
const MyComponent = connect()(MyComponentWrap);
```

not the prettiest, but I've had success with it thus far.

**Comment by arackaf** [comment]
Thanks - yeah, that or somehow casting the connected component to any.  

Really hoping TypeScript supports decorators better.

**Comment by cuitianze** [comment]
Unable to resolve signature of class decorator when called as an expression.
+1
