### ISSUE TITLE
Why not just call `trySubscribe` in `componentWillMount` if `typeof window !== 'undefined'`?

### ISSUE THREAD

**Issue by faceyspacey** [reactjs/react-redux#725]
I'm referring to this line in `connectedAdvanced`:

https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L154

It seems it would make things faster for the case where *child components* trigger a state change, and perhaps even a little bit for components that don't.

I understand the correct idiom is to define state in your constructor or as an instance property, but still. Are we simply trying to prepare for a very rare use case that `window` is defined on the server. When running tests in Jests, it will be defined. But if `componentWillUnmount` is called there, it's not an issue there as well. And if it is, perhaps we can detect jest and do the `componentDidMount` technique currently in use.  

Why is `typeof window !== 'undefined'` not considered a good enough solution?

**Comment by timdorr** [comment]
Because componentWillMount does this for us. We don't really care about it being in the browser or the server or whatever. We care about whether there will be a cleanup stage when the component is unmounted. When rendering to a string, there is no unmount step, so you can get a memory leak very easily. Doing an environment check doesn't tell us that, so it's a weak smoke test to be doing that sort of thing.

**Comment by faceyspacey** [comment]
The "weak smoke test" thing was what I was assuming, but it's the use case 99% of the time. So performance is being sacrificed for a 1% of the time case. Possibly a 0% of the time case.

**Comment by faceyspacey** [comment]
where is there a window object when componentWillUnmount is not called?

**Comment by gaearon** [comment]
Can you expand a bit more on the speed benefit we'd get if we didn't do this? I don't fully understand.

**Comment by timdorr** [comment]
> where is there a window object when componentWillUnmount is not called?

If you `renderToString` in the browser, which is a perfectly valid thing to do.

**Comment by faceyspacey** [comment]
That's a valid use case. No other way to detect we are running in that function?

The perf benefit is forceUpdate doesn't need to be called in the function I linked above because the selector will get the necessary state before the first render. So one render vs 2.

**Comment by gaearon** [comment]
Calling forceUpdate in componentDidMount is really unfortunate if that's what happens. I haven't been keeping a close look at v5 and I'm worried there's a bunch of things that may become worse in future versions of React.

I think at this point we should wait for React 16 to be out and then re-evaluate choices made in v5 with regards to how subscriptions are set up and updates are scheduled. It's probably not worth doing that now though.

**Comment by gaearon** [comment]
In the meantime you can keep use v4 which to my knowledge doesn't do this. I might be wrong though or misunderstand this discussion. Sorry if this is the case.

**Comment by faceyspacey** [comment]
To be clear, forceUpdate is only called if child components (not just the wrapped component but the entire branch) dispatch an action resulting in a state change.

**Comment by jimbolla** [comment]
@gaearon This is behavior that existed in v4.

**Comment by faceyspacey** [comment]
It seems to me renderToString should set some indicator that componentWillUnmount will not be called. Simple as that. Knowledge that ur running within renderToString sounds like a must at this point. Redux is the second most important package in the React world. Can that not be coordinated? Perhaps surrounding the 16 release.

**Comment by markerikson** [comment]
@faceyspacey : I'm kind of confused.  What's the original concern here?  A performance issue?  If so, what's the actual perf impact in play, and why is it such a big deal?

**Comment by markerikson** [comment]
@gaearon : I know React 16 is still a ways off, but can you point to any specific concerns about v5's behavior and implementation?  I know you've expressed some hesitation in a couple different threads, but I'm really not clear on what actual things are bothering you.

**Comment by faceyspacey** [comment]
`forceUpdate` can possibly be called here: 

https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L156

causing a 2nd unnecessary render after mounting.

This happens when actions are dispatched in the child component of the wrapped component *AND ALL ITS CHILDREN*. I.e. the whole branch is subject to another render.

**Comment by markerikson** [comment]
So, you're specifically worried about one potential extra render?

**Comment by faceyspacey** [comment]
Absolutely. 

Jank during animations coinciding with renders is a constant problem with React on real apps.

**Comment by markerikson** [comment]
Do you have any specific benchmarks indicating that that line is an actual issue?

**Comment by timdorr** [comment]
Why would that ever fire? We [run the selector via the constructor](https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L191), so [nextProps should equal selector.props](https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L17) and [selector.shouldComponentUpdate should still be false](https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L251). 

Question I have: Why run the selector twice? I realize it's memoized, but we've got two problems: 1) You're doing the work twice. 2) `render()` isn't pure. Why not just initialize the selector in `makeSelectorStateful` with those properties already defined and set for the initial state? That would seem to obviate the need for the `forceUpdate()` call as well.

**Comment by faceyspacey** [comment]
@markerikson No, but of course it is. Frames dropped is a function of the number of simultaneous animations + components re-rendering. When apps go from being "sites" to animation-heavy apps, you're dropping frames all the time. Less so in RN, but especially within the browser.

@timdorr if it's never called, `forceUpdate` should be removed. 

The following seems to be the reason why this is done:

https://github.com/reactjs/react-redux/issues/210#issuecomment-166055644
> By the time componentWillMount fires on the child, it is too late to change the props child receives. Since store dispatch changes child's props, this must happen on the next render.

There's another problem with this:
*during SSR, you can't dispatch anything in `componentWillMount` and expected it to be reflected further down the tree.*

I think we need to solve what @gaearon mentioned regarding it to being "too late to change the props children receive" and then after change the `trySubscribe` implementation to:

```js
componentWillMount() {
  if (!shouldHandleStateChanges) return

  if (Render.hasComponentWillUnMount()) {
    this.subscription.trySubscribe()
  }
}
```

**Comment by faceyspacey** [comment]
The one caveat is if in `componentWillMount` you dispatch something that changes what parents or siblings render, they won't render the correct thing. Doing it this way only solves things for the wrapped component and children. Damn.

At which point double renders are unavoidable, and it doesn't really matter if we do `trySubscribe` in `componentDidMount` since we need the method anyway. 

I actually never dispatch in `componentWillMount`, which I think is the correct idiomatic way. But I ran into this problem when a developer I was talking to couldn't figure out why SSR wasn't working correctly. At the very least this should be mentioned in bold as a **DONT DO** in the readme.

**Comment by faceyspacey** [comment]
SSR is more important than ever. With SSR + Code-Splitting being a [solved a problem](https://medium.com/@faceyspacey/code-cracked-for-code-splitting-ssr-in-reactlandia-react-loadable-webpack-flush-chunks-and-1a6b0112a8b8), we should expect all apps to have SSR. The SPA days are over.

**Comment by faceyspacey** [comment]
And by the way, I think the correct solution was already arrived at. Maybe Fiber will allow for an additional opportunity to re-render during SSR. Here's a PR to the readme: 

https://github.com/reactjs/react-redux/pull/726

The case is likely closed until Fiber. @gaearon if you could bring this up with the Fiber team that would be awesome. Talk to you all later.
