### ISSUE TITLE
Cannot use custom context and connect (as es7 decorator) together

### ISSUE THREAD

**Issue by c0d0g3n** [reactjs/react-redux#730]
When connecting a react component using es7 decorators, you cannot make custom context properties available:

    @connect((store) => {
        return store
    })
    class MyComp extends React.Component {
      // ... component definition here
    }

    // BELOW DOES NOT WORK
    MyComp.contextTypes = {
      // Keep contextTypes defined by connect, otherwise react will crash because connect can't access its context
      ...MyComp.contextTypes,
      prop: PropTypes.string
    }

Everything seems to work fine, but `this.context` stays empty in `MyComp`. There's no issue when you use `connect` as a normal function (not a decorator):

    class MyComp {...}
    MyComp.contextTypes = {
      prop: PropTypes.string
    }
    connect(...)(MyComp)

This behavior is probably not even under react-redux' control (es7, maybe I don't understand decorators fully), but I thought I'd post anyway, so it is at least documented.

(Off topic: Some of you may cringe that I use custom context in addition to redux, but I think I've actually found a legitimate use case; I use context with custom table components so that every part of the table is aware of its row, column and kind of data being displayed. :) )

**Comment by markerikson** [comment]
Yep, this is likely the same general issue as trying to `propTypes` or `defaultProps`.  When you use `@connect()` as a decorator, the "plain" component is never exposed, and those items are applied to the wrapper component definition instead.

This is one of several reasons why the Redux team recommends that you do _not_ use `connect` as a decorator, but rather use it as a standard function call instead.

**Comment by yeliex** [comment]
@markerikson what i should to if i want to use `decorator`, it worked fine with `react-redux@4.x` before
