### ISSUE TITLE
mapDispatchToProps can't recognize anonymous function

### ISSUE THREAD

**Issue by jake-daniels** [reactjs/react-redux#737]
Hi guys, I've encountered one very tricky issue and I wasn't able to find any working solution so far.
I will try to describe it as clearly as possible.

I have a file, let's say `actions.js` which contains some action creators. Two of them are important:
```
export function actionCreator_A (param) {
	return {
		type: ACTION_TYPE_A,
		payload: {param},
	}
}
export const actionCreator_B = (param) => {
	return {
		type: ACTION_TYPE_B,
		payload: {param},
	}
}
```
As you can see, one is ES5 function and the other is ES6 anonymous function. Then I have a component, which is connected to store.
```
@connect(
    (state) => ({
        ...some state selectors,
    }), 
    {actionCreator_A, actionCreator_B},
)
export default class MyComponent extends PureComponent {
    	onClick = () => {
		const {actionCreator_A, actionCreator_B} = this.props
                actionCreator_A(123)
                actionCreator_B(456)
	}
        ...
}
```
With this setup, inside the `onClick` function, the `actionCreator_A` is properly bound action creator, I can call it and the action is dispatched. But `actionCreator_B` is `undefined`!  
`Uncaught TypeError: actionCreator_B is not a function` appears.

When I change the connect setup to this...
```
const mapDispatchToProps = (dispatch) => {
	return {
		actions: bindActionCreators({
			actionCreator_A,
			actionCreator_B,
		}, dispatch),
	}
}

@connect(
    (state) => ({
        ...some state selectors,
    }), 
    mapDispatchToProps,
)
```
...everything works fine and both actions are properly dispatched. Also when I change `actionCreator_B` to ES5 function, it works as well.

What is really weird is that I use both these action creators in different component and it works fine there.

Am I missing something or is it a bug in the library?

**Comment by markerikson** [comment]
Are you defining those functions in the same file as the `connect` / `mapDispatch` usage?  If so, are you defining them _after_ the `mapDispatch` declaration?  The `function` keyword gets hoisted to the top of the file, but `const` and `let`-declared variables don't exist until the line they're declared on.

That said, your comment that directly using `bindActionCreators` inside of `mapDispatch` works fine seems confusing.

I would need to see all of your code together to be able to give a more definitive answer.  Overall, though, my guess is that you're having issues with variable scoping, and that this is not an actual issue with `connect` at all.

**Comment by jake-daniels** [comment]
Action creators are defined in a separate file.
I know that this issue is very specific and it's hard to even guess where the problem could be, but I can't post here entire codebase of the project. Moreover, I wasn't able to reproduce the issue in different project. It doesn't even happen in the same project. I always define all functions as constants and use  `mapDispatchToProps` as object with shorthand notation. And this confuses me the most: I have components **A** and **B**, where **A** is a parent of **B**. It works fine in **A**, doesn't work in **B**.

**Comment by jimbolla** [comment]
My guess is that this has to do with the fact an anonymous function is not hoisted like a normal function, combined with cyclical references between your files. So it's undefined when the component js file is first executed, but is defined when it's instantiated.

**Comment by jake-daniels** [comment]
@jimbolla That seems to be the most natural solution, but what about `bindActionCreators` ? It would receives the same `undefined` as `connect`.

**Comment by markerikson** [comment]
Something about when the code is executed, I would guess?

**Comment by jimbolla** [comment]
By the time mapDispatchToProps function is invoked, the references have been updated. Basically...

```js

import { A } from 'somewhere';

var obj = { A }; // A is evaluated once immediately.

var func = () => ({ A }); // A is live reference and will be evaluated every time.
```

I'm fairly confident this is a js build issue and not related to redux, so closing this out.
