### ISSUE TITLE
typo on the source code for connectAdvanced?

### ISSUE THREAD

**Issue by hkjpotato** [reactjs/react-redux#739]
Hi, in the source of connectAdvanced line 255  it seems there is a typo in the comment

  //Doing it this way vs having a permanent `componentDidMount` that does
 // a boolean check every time avoids an extra method call most of the time, resulting
 // in some perf boost.

How to do a boolean check in the 'componentDidMount' for the succesive update since it will only be called once in the lifecycle? Could you explain how to use a permanent `componentDidMount` method that does the same thing like the current temporal 'componentDidUpdate' approach?

Thank you.

**Comment by jimbolla** [comment]
That was probably supposed to be componentDidUpdate.

**Comment by timdorr** [comment]
Yeah, I'll go change it.

**Comment by hkjpotato** [comment]
Thank you. It makes sense know. I guess the logic here is that only when an update triggered by its `onStateChange` need to do the `notifyNestedSubs`.  If we implement a permanent `componentDidUpdate` then if it is triggered by a parent's re-render it should have a boolean to stop it from doing the notification.

**Comment by hkjpotato** [comment]
@timdorr Hi timdorr, I finally finish reading the source code and write a medium to illustrate a simplified version of react-redux about it. For anyone who is interested in the implementation of react-redux maybe it is a good source. https://medium.com/@kj_huang/implementation-of-react-redux-part-1-411b971a9b5b

And please correct me if my explanation is wrong :)

**Comment by xusanduo08** [comment]
@hkjpotato ，Hi，I got a question,you said ' If we implement a permanent componentDidUpdate then if it is triggered by a parent's re-render it should have a boolean to stop it from doing the notification.' Did you mean parent is not wrapped by `connect` method?
