### ISSUE TITLE
How to keep balance between passing pros vs. using multiple connect() fn

### ISSUE THREAD

**Issue by michaltaberski** [reactjs/react-redux#745]
Hey,

I am working on quite complex, in browser graphics editor.

Just as a concept it looks like this:

<img width="923" alt="screen shot 2017-07-14 at 18 57 06" src="https://user-images.githubusercontent.com/202033/28222220-cab5ce02-68c6-11e7-8d22-f087021d9d4e.png">

You can imagine components structure as something like this:

```
<App>
  <Canvas>
     <CanvasElement />
     <CanvasElement />
  </Canvas>
  <Sidebar />
</App>
```

obviously in a real world application it looks more like this

```
<App>
  <Canvas>
     <..>
       <..>
         <..>
           <..>
             <..>
               <CanvasElement />
               <CanvasElement />
             </..>
           </..>
         </..>
       </..>
     </..>
  </Canvas>
  <Sidebar />
</App>
```

So far I am using `connect()` fn on root `App` component. However most of the interactions is performed deep down the app at `<CanvasElement />`.

It means that each time I am adding new action to the `<CanvasElement />` I need to pass the prop through several (~6) components.

My question are:
- Isn't it just more pragmatic to use `connect()` for each `<CanvasElement />` and remove all the props which are just proxied over several layers?
- How do you judge where to use `connect()` fn?
- Do you always stick with rule of using `connect()` at root only component?

**Comment by markerikson** [comment]
This is really a usage question, not a bug report or a feature request.

You should feel free to connect any component that "makes sense" to connect (and definitely should _not_ be constrained to only connecting the root component).  For more info, see [the Redux FAQ entry on connecting multiple components](), my blog post [Practical Redux, Part 6: Connected Lists, Forms, and Performance](http://blog.isquaredsoftware.com/2017/01/practical-redux-part-6-connected-lists-forms-and-performance/), and the [Redux Performances](https://github.com/markerikson/react-redux-links/blob/master/react-performance.md#redux-performance) and [Redux Architecture](https://github.com/markerikson/react-redux-links/blob/master/redux-architecture.md) sections of my [React/Redux links list](https://github.com/markerikson/react-redux-links).
