### ISSUE TITLE
Helper function for simplifying mapStateToProps

### ISSUE THREAD

**Issue by baron816** [reactjs/react-redux#749]
I've written this simple function that I believe simplifies creating mapStateToProps:

```
export function makeProps(selectors) {
  return function (state, ownProps) {
    return Object.keys(selectors).reduce(function(acc, key) {
      acc[key] = selectors[key](state, ownProps);
      return acc;
    }, {});
  };
}
```

This will allows me to do `const mapStateToProps = makeProps({products, total});` where `products` and `total` are selector functions. I believe it's somewhat similar to combineReducers (at least in spirit).

1) There aren't any performance issues that I'm overlooking, are there?
2) Can I add this to react-redux?

**Comment by timdorr** [comment]
There's already an open PR for this: #724
