### ISSUE TITLE
Why is create-react-class in dependencies on npm?

### ISSUE THREAD

**Issue by gaearon** [reactjs/react-redux#755]
Found this a bit weird: `create-react-class` seems to be in npm `dependencies` in published package: https://unpkg.com/react-redux@5.0.5/package.json

But not in the source `package.json`. Is this some npm artifact?

**Comment by jimbolla** [comment]
Looks like it was added in fcc28ff487b85e64da6d0b3d0c9014597d3585cf. Then 5.0.5 was published. It was then moved from dependencies to devDependencies in bf61f5b51cf3c9689de8e4f3e3fd857db74b0c9b which hasn't been published yet.

**Comment by gaearon** [comment]
Aah okay. Thanks for explaining.

**Comment by timdorr** [comment]
Yep, my bad on that. Is it causing issues? I can publish a patch quickly.

**Comment by gaearon** [comment]
No, just noticed it randomly and was curious. Thanks for the offer though!
