### ISSUE TITLE
mapDispatchToProps add action creator name

### ISSUE THREAD

**Issue by jEnbuska** [reactjs/react-redux#758]
Hi. When I use redux-thunk i can find it time time taking to figure out what actionCreator is the source of dispatching a specific action that changes the state.
Could the function passed to mapDispatchToProps be named (when process.env.NODE_ENV === 'developmen')?
Something like this <sub>(sorry I don't quite understand how the implementation of react-redux connect)</sub>:
```
const mapDispatchToProps = Object.entries(connectMapDispatchToProps)
      .reduce((acc, [ name, action, ]) => {
        if (typeof action === 'function') {
          acc[name] = (...args) => {
            store.dispatch({
              [name]() {
                action(...args);
              },
            }[name].bind(this)());
          };
        } else {
          acc[name] = (obj) => store.dispatch(obj);
        }
        return acc;
      }, {});
```
So thunk could do something like: 
```
function createThunkMiddleware(extraArgument) {
  if(process.env.NODE_ENV === 'development'){
    return ({ dispatch, getState }) => next => action => {
      if (typeof action === 'function') {
        return action((...args)=> dispatch({...args, 'THUNK@@ACTION_NAME': action.name}), getState, extraArgument);
      }
      return next(action);
    };
  }
  return ({ dispatch, getState }) => next => action => {
    if (typeof action === 'function') {
      return action(dispatch, getState, extraArgument);
    }
    return next(action);
  };
}
```
Could this work?

**Comment by markerikson** [comment]
One of the main points of dispatching Redux actions is that you can look at the `type` of an action, and search your codebase to see exactly where that got dispatched.  If you're using an action creator, then there's probably only one place in the codebase where a given action is created, and then you can just search for where that action creator is used.

I don't think there's any actual changes we would want to make, but thanks for the suggestions.

**Comment by jEnbuska** [comment]
Ok. I'm used to be very imperative with my action types, so that's probably part of my problem. 

I have a double motive for being able to track which action creator is responsible for a specific change.
The 2nd one is that is that I've been coding a library that tries to get rid of reducers, by automating path copying, and the action dispatched are very imperative.

```
function updateUser(userId, update){
   return function({users}){
      users[userId].setState(update); 
     //result to `dispatch({type: SET_STATE, SUBJECT: [$userId, users], PARAM: $update})`
   }
}
```
