### ISSUE TITLE
State not changed in component props but has changed in the store.

### ISSUE THREAD

**Issue by Panoplos** [reactjs/react-redux#760]
I have run into an issue where I am updating the redux store via a reducer, but the app's copy of the state is not updated. See these shots below:

![redux state](https://user-images.githubusercontent.com/2549985/28878302-cec1cf2e-77d9-11e7-8a41-49cd699e4c7e.png)

![app state](https://user-images.githubusercontent.com/2549985/28878309-d3081836-77d9-11e7-8b3a-2d5e07c0de05.png)

Has anyone else seen this before? Any ideas where I can look for the issue?

The code is very simple at this point, just `connect`ing props as follows:

```es6
export default (hash) => {
  
  const mapStateToProps = (state: Object) => ({
    navigatable: state.modal.navigatable
  })

  const mapDispatchToProps = (dispatch: Dispatch) => ({
    toggleNavigability() {
      dispatch(toggleNavigability())
    }
  })

  return [
    connect(mapStateToProps, mapDispatchToProps),
    lifecycle({
      componentDidMount() {
        $(hash)
          .modal({
            detachable: false,
            onHidden: () => {
              if (this.props.navigatable) {
                this.props.history.goBack()
              }
              this.props.toggleNavigability()
              return true
            }
          })
          .modal('show')
      },
      componentWillUnmount() {
        if (this.props.navigatable) {
          this.props.toggleNavigability()
          $(hash).modal('hide')
        } else {
          this.props.toggleNavigability()
        }
      }
    })
  ]
}
```

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by Panoplos** [comment]
Here's the thing, I am rendering this component using a `Route`, as follows:

```es6
// Container
const LandingContainer = ({modal}) =>
  <div className='landing-container'>
    <Header inverted />
    ...
    {!!modal ? <Route path='' component={modal} /> : ''}
  </div>

**Comment by timdorr** [comment]
Read this guide if you want something more specific to Redux: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md This is the exact problem you are having.

**Comment by Panoplos** [comment]
I am not seeing it. The document clearly states that state should update if the component is rendered via a Route, which in my case it is, and the state is not updating in the props, even though it has in the store.

**Comment by timdorr** [comment]
You have to wrap your component in `withRouter` when you use `connect`.

**Comment by Panoplos** [comment]
That was the answer to what I was looking for but didn't actually solve the problem. LOL
My assumption that redux state would be reflected in the component props after `componentWillUnmount()` was wrong... Thanks for the help, anyway.
