### ISSUE TITLE
Can ownProps ever be undefined in mapStateToProps or mapDispatchToProps?

### ISSUE THREAD

**Issue by tansongyang** [reactjs/react-redux#764]
I think there may be a small issue with the TypeScript typings on DT. An answer to this question will help me determine if that is the case.

Consider this snippet from [the docs](https://github.com/reactjs/react-redux/blob/master/docs/api.md#the-arity-of-mapstatetoprops-and-mapdispatchtoprops-determines-whether-they-receive-ownprops):

```JavaScript
const mapStateToProps = (state, ownProps) => {
  console.log(state); // state
  console.log(ownProps); // ownProps
}
```

The docs say:

> Functions with no mandatory parameters or two parameters **will receive** `ownProps`.

It's not clear to me if that received value can ever be `undefined`. Based on my testing, `ownProps` is always an object. However, I want to confirm that this is guaranteed.

**Comment by timdorr** [comment]
Yes, if your mapStateToProps is determined to not need ownProps, [it is never passed into the function](https://github.com/reactjs/react-redux/blob/fd81f1812c2420aa72805b61f1d06754cb5bfb43/src/connect/wrapMapToProps.js#L41-L43). So, it can be undefined.

**Comment by jimbolla** [comment]
This appears to be looking at the 4.x branch. The master branch does this differently anyways.

**Comment by tansongyang** [comment]
@timdorr Thanks for the quick response. The code you pointed me to helped me get my answer.

When you specify the `ownProps` parameter, passes in the props of the `Connect` class ([initSelector](https://github.com/reactjs/react-redux/blob/fd81f1812c2420aa72805b61f1d06754cb5bfb43/src/components/connectAdvanced.js#L191)). This will always be an object.

Therefore:

```JavaScript
const mapStateToProps = (state, ownProps) => {
  // Because we specified the ownProps argument, ownProps will always be an object.
  console.log(ownProps);
}

Thanks again.

**Comment by flushentitypacket** [comment]
@tansongyang 

Seems to me that the DT package should just set ownProps to not be undefined, since it will always be defined when the arg is specified. Typing it as undefined only creates friction for the developer at no benefit.
