### ISSUE TITLE
Possible Connect handleChange optimisation?

### ISSUE THREAD

**Issue by martinkadlec0** [reactjs/react-redux#765]
Imagine a reducer that in some instances (e.g. when action A is dispatched) returns new object but its content is still the same (shallowCompare equals).

Now, if such thing happens the `Connect.prototype.handleChange` method will not be stoped at:
```javascript
if (pure && prevStoreState === storeState) {
```
but will continue further and will call `updateStatePropsIfNeeded` to check if anything has changed. It likely hasn't since the state is still essentially the same and so the following condition
```javascript
if (!haveStatePropsChanged) {
  return;
}
```
will be truthy and the function will end.

Now, for the first time this is fine - the state has changed in some way and so we need to check if the component should rerender.

The problem is, the next time another action (e.g. action B) is dispatched and store returns exactly the same state as after action A then `handleChange` will still call `updateStatePropsIfNeeded` because storeState in Connect's component state is still the one before action A was called.

What I am proposing is to update the store state in Connect's state inside the `if (!haveStatePropsChanged) {` condition block before the return.
```javascript
if (!haveStatePropsChanged) {
  this.setState({ storeState: storeState });
  return;
}
```
This will prevent further unnecessary updateStatePropsIfNeeded calls.

If this seems like a good idea I can do a PR but my knowledge of redux and react-redux isn't perfect so I am asking first :)

**Comment by timdorr** [comment]
This won't practically matter. If a section of state covered by a reducer is unaffected by an action, it should return the same state object by default. So, the `prevStoreState === storeState` check should be true unless you've affected state controlled by that reducer. There may be some very tiny edge cases this would cover, but they are extremely rare in practice.
