### ISSUE TITLE
Subscription notification order question

### ISSUE THREAD

**Issue by skiano** [reactjs/react-redux#766]
This is maybe a naive question. But I was looking at the `Subscription` code and specifically thinking about this comment https://github.com/reactjs/react-redux/blob/master/src/utils/Subscription.js#L1-L3

If the goal is to ensure that children are notified after parents, could that be accomplished by an event emitter that notifies in the opposite direction? Like, if the event emitter added listeners to the beginning of the list rather than pushing them on the end? And if that was true would it eliminate the complexity of the nested subscriptions?

**Comment by jimbolla** [comment]
Reversing the order is only part of it. The more complicated part is ensuring children don't get notified until parents have finished, so that they send fresh props to the children. Otherwise you end up with the situation where a child component's mapStateToProps is running with the new state but old props.

A lot of the complexity is for avoiding calls to `setState`, which, as of React 15, was the biggest performance loss. I'm hoping that React 16's "Fiber" implementation has changed things, because the React Redux code could be simplified if we could move props calculation into the setState call.

**Comment by skiano** [comment]
@jimbolla Thanks for the reply!

**Comment by markerikson** [comment]
As a vaguely related note: I talked with Dan some about v5 at ReactRally.  He said he doesn't particularly understand how it works, has general concerns about React-Redux's overall interaction with the React component tree in terms of trigger multiple independent re-renders, and isn't yet sure how we might need to update things for "best" interaction with React 16 and later.  I also remember Andrew making a comment at some point about wanting to convene a summit of the major state management libs sometime around 16's release to discuss possible updates.

**Comment by skiano** [comment]
Very interesting. I was wondering about this because I feel that a lot of the appeal of adopting redux has much less to do with redux than it has to do with how difficult it is to write the connector component in a air-tight way. Like if I could just have something to help me write a connector like this, but could handle the state with redux or a behavior subject or just a plain event emitter I would feel more empowered.

**Comment by markerikson** [comment]
@skiano : not quite sure I follow what you're saying there.  Can you clarify?

**Comment by skiano** [comment]
@markerikson sure, I am just saying that the hardest part of state mgmt to wrap my mind around in react is what it means to actually connect the components to updates, especially when those components are nested, or worse, if the components care about some of the same events but not the others.

So in a way, I use redux less because of redux architecture itself, and more because react-redux provides a way to connect to redux. In other words, I find myself adopting redux structures (reducers, actions, middleware) _not_ because I want to express my application state that way, but because if I do, I can take advantage of this connector, knowing that it already takes care of things like @jimbolla points out above.
