### ISSUE TITLE
Handle "store not found" exception

### ISSUE THREAD

**Issue by MarcAtrapalo** [reactjs/react-redux#767]
Hi guys, this is a tricky doubt I am not sure how to address, but that I find very needed.

I want **a connected component to gracefully degrade to an unconnected one** whenever store is not found.
Since the connect function contains the code for the exception, one would expect this to work (code available [here](https://codepen.io/MarcAtrapalo/pen/GvBRjY)):

```js
const store = createStore(s => s, {salutation: 'hi!'});

const Comp = (props) => {
    console.log(props)
    return <span>{props.hi}</span>;
}

class NoStoreHandler extends React.Component {
    render() {
        try {
            const mapStateToProps = s => ({hi: s.salutation});
            const ConComp = connect(mapStateToProps)(Comp);
            return <ConComp/>;
        } catch (e) {
            console.log(e);
            return <Comp hi="hello world!"/>;
        }
    }
}
[...]
```

However, as it seems the exception is being thrown on the `constructor` of the HOC, I do not find any way to catch that exception from a parent component, as it only can be catched on the render method, on top of the app:
```js
try {
    ReactDOM.render(
        <NoStoreHandler/>,
        document.getElementById('app')
    );
} catch (e) {
    console.log(e);
}
```

Would there be any way to handle this exception from a parent component, or somehow detect, from a connected component, if the store is available or not, without crashing the whole app?

Thanks in advance for any pointing in the right direction.

P.D: The reason I need this is for testing. I have a connected component (i.e. the Translator) that is being used in almost every unconnected component in my app. If I want to test the view rendering, I need to connect the components with a fake store for every single component test, and I am sure react-redux has to have better support for testing than that.

**Comment by timdorr** [comment]
You can create a do-nothing store like we do in our tests:

https://github.com/reactjs/react-redux/blob/master/test/components/connect.spec.js#L77

Then just include a Provider above your tests and it will be good to go. Having your code behave differently in a test environment is likely going to lead to behavior mismatches with production code. I'd advise against that.
