### ISSUE TITLE
[question] is it possible to pass props to component from connect & parent

### ISSUE THREAD

**Issue by hozefaj** [reactjs/react-redux#770]
I have a component that relies on some data/actions that right now I am passing from my parent component that. The parent component is connected to actions/state using `connect`.

The data the child relies on, can come directly(does not need parent). So I am wondering that I could also use `connect` on my child component to pass data & rest props come through parent.

Right now, I am seeing that the props passed through `connect` are not added to the child.

**Comment by timdorr** [comment]
Yes, [this definitely works](https://github.com/reactjs/react-redux/blob/master/test/components/connect.spec.js#L1155). 

If you're using the 3rd mergeProps argument, make sure you're taking in ownProps correctly.
