### ISSUE TITLE
flow-typed (v5.x.x) Missing proper Connector check when component has defaultProps.

### ISSUE THREAD

**Issue by CarlosGines** [reactjs/react-redux#773]
Given a simple component with defaultProps:
```
type Props = { a: number };

class MyComponent extends React.Component<Props> {
  static defaultProps = { a: 0 };
}
```
This works out of the box with flow:
```
<MyComponent />;
```
I would expect the same behaviour for containers, in order to have a consistent use of defaultProps. But this fails:
```
const connector: Connector<{}, Props> = connect();
```
Of course the Connector has no information about the defaultProps of the component there yet...
Any way to achieve this type check now? or plans to do it?

**Comment by timdorr** [comment]
Our flow types aren't maintained here. I'd ask this on the flow-typed repo.
