### ISSUE TITLE
[Possible Doc error] mapStateToProps gets called no matter what

### ISSUE THREAD

**Issue by riwu** [reactjs/react-redux#780]
From https://github.com/reactjs/react-redux/blob/master/docs/api.md#arguments

> [pure] (Boolean): If true, connect() will avoid re-renders and calls to mapStateToProps, mapDispatchToProps, and mergeProps if the relevant state/props objects remain equal based on their respective equality checks. 

https://codesandbox.io/s/ymmpmlmqxx
When I clicked on `B`, `mapStateToProps` of `a.js` got called even though `state.a` did not change. 
Hence the above doc appears to be false?

**Comment by markerikson** [comment]
`connect` does two primary checks based on immutability:

- First, it checks to see if the root state object has changed at all.  If it hasn't, then it assumes that no other state has changed, and does _not_ run `mapStateToProps`
- If the root state _has_ changed, then it will go ahead and run `mapStateToProps`.  

Note that `mapStateToProps` is always called with the _entire_ state.  It's the job of `mapState` to determine which pieces of store data that component cares about.  A `mapState` function is not limited to only running when certain slices of state change.
