### ISSUE TITLE
HMR not work for container components

### ISSUE THREAD

**Issue by Mr-Binary** [reactjs/react-redux#787]
### Packages:
- "react": "^15.6.1",
- "redux": "^3.7.2",
- "react-redux": "^5.0.6",
- "react-hot-loader": "^3.0.0-beta.7",
- "webpack": "^3.6.0",

### What is the problem?
HMR works for component which is not wrapped by `connect()`

### Could you reproduce it?
The repo is here, https://github.com/Mr-Binary/fullstack-react-boilerplate
1. Clone and install dependencies
2. `npm run start` - start server
3. `npm run dev` - start webpack-dev-server
4. Open the page in browser at `http://localhost:9876`
5. Open `client/components/App/index.jsx`, add some text after `<div>`, the HMR works as expected
6. Open `client/containers/SearchBox.jsx`, change the button text to any text you want. The browser will show no error and `App/index.jsx` and `SearchBox.jsx` updated. But nothing changed.

BTW: I tried go back to `react-redux@4.4.x and 5.0.3`, not work as well.

**Comment by timdorr** [comment]
This isn't an issue with react-redux. It's either your configuration or react-hot-loader.
