### ISSUE TITLE
Improve docs for "factory function" syntax

### ISSUE THREAD

**Issue by markerikson** [reactjs/react-redux#797]
The current docs for the "factory function" syntax are not very clear, and also say that "most apps should never need this".  We should rewrite that section, and also be sure to provide examples of using the factory function syntax.

For reference, discussion, and examples, see #279 , [a Reddit comment I made with use cases and samples](https://www.reddit.com/r/reactjs/comments/5dxasp/any_deepdiveadvanced_tutorials_on_reselect/), and I think some of the articles in the [Redux Performance](https://github.com/markerikson/react-redux-links/blob/master/react-performance.md#redux-performance) section of my links list might discuss this.

**Comment by timdorr** [comment]
I would like this too. I've never been clear on what another level of indirection affords you when constructing these functions. I prefer the simplest object syntax, personally :)

**Comment by markerikson** [comment]
The short answer is that it provides a closure where you can create unique selector instances per component instance, so that the selectors memoize "properly" for that component.

**Comment by jimbolla** [comment]
I mostly use this for component-scoped memoization of selector results.

```javascript
function mapState() {
  const getSomeProp= createSelector(...);
  return (state, props) => ({
    someProp: getSomeProp(state, props),
  });
}
```

**Comment by markerikson** [comment]
Right, that's the use case. What I'm saying is that the current doc page really doesn't actually describe how to do that or give examples.  It hand-waves things, says, "you probably don't need to do what we just vaguely described anyway", and points to an old issue for examples.  Since this is part of the API, it should be meaningfully documented.
