### ISSUE TITLE
hacktoberfest issues?

### ISSUE THREAD

**Issue by sw-yx** [reactjs/react-redux#800]
i love react-redux, let me know if i can help out for hacktoberfest!

**Comment by timdorr** [comment]
Go for it! PRs of any sort are welcome.

**Comment by markerikson** [comment]
In particular, I'd love help with docs in both the Redux and React-Redux repos!  Please feel free to help with any issues tagged "documentation".

**Comment by sw-yx** [comment]
ok u got it
