### ISSUE TITLE
React Hot Loader v3 "this component is not accepted by Hot Loader" error

### ISSUE THREAD

**Issue by dizlexik** [reactjs/react-redux#806]
After switching to React Hot Loader v3 I'm now getting the following error:

```
React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 ƒ Connect(props, context) {
...
```

And the source is https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L115

I was getting plenty of errors like this with my own code too until I updated everything to export each intermediate HOC as described in the React Hot Loader FAQ here: https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#react-hot-loader-this-component-is-not-accepted-by-hot-loader

Would you consider moving the Connect component outside of wrapWithConnect and exporting it? There's really nothing functionally wrong with the code as it currently is, but this would help with hot module reloading, and clear up this annoying error message.

**Comment by timdorr** [comment]
connectAdvanced and the inner wrapWithConnect function are pretty integral to how this version works. You can use react-redux 4.x, which is fully API-compatible with 5.x.

**Comment by dizlexik** [comment]
Sorry, it does look like this change is probably more painful that the benefit is worth. Thanks for taking the time to reply.

**Comment by JustFly1984** [comment]
I have same issue, I cant roll back react-redux from 5.0.6 to 4.x.x

<img width="958" alt="screenshot 2017-11-05 17 46 25" src="https://user-images.githubusercontent.com/2255993/32413653-51fc2012-c251-11e7-9a73-a5227652cdb4.png">

**Comment by pattiereaves** [comment]
I'm having the same issue. :/ How did you work around it @dizlexik ?

**Comment by dizlexik** [comment]
@pattiereaves I was just dealing with it and filtering it out in Chrome for a while and at some point it just stopped happening. I'm not sure what changed in my project to make these warnings go away, sorry :/

**Comment by pattiereaves** [comment]
I'm not sure what causes this issue, but if anyone else comes to this ticket via google, refactoring my app to look [more like this example](https://github.com/krasevych/react-redux-styled-hot-universal) fixed it.
