### ISSUE TITLE
Connect refactor no longer sends dispatch prop

### ISSUE THREAD

**Issue by jtadmor** [reactjs/react-redux#820]
Before the refactor to `createConnect`, I could do something like

`connect(mySelector, { doThing, doOtherThing })(MyComponent)`

If `MyComponent` needed to do something else with `dispatch` (perhaps with no action set up, or maybe we wanted to inline a more complex flow, it could do that):

```
class MyComponent extends Component {
  doComplexThing = payload => {
    this.props.dispatch({
       type: 'complex start',
       payload,
     })
     
    doApiCall().then( results =>
      this.props.dispatch({
        type: 'complex done',
        payload: results
      })
    )
  }
```

Now maybe a decision was made not to support this, and if someone is going to bother with `mapDispatchToProps` they need to stick with it, and use `redux-thunk` or some other similar library to handle async flows and use action creators for all actions.

But that seems like a bit of an unfair and unnecessary decision for a library to make.
If it seems reasonable, I'm happy to submit a PR to pass the `dispatch` prop whenever a plain object `mapDispatchToProps` is provided (I think the fn form has access to it, and so it can decide whether to pass it or no).

(It looks all that is needed is:
```
export function whenMapDispatchToPropsIsObject(mapDispatchToProps) {
  return (mapDispatchToProps && typeof mapDispatchToProps === 'object')
    ? wrapMapToPropsConstant(dispatch => ({
         dispatch,
         ...bindActionCreators(mapDispatchToProps, dispatch))
    }))
    : undefined
}
```
)

**Comment by timdorr** [comment]
Can we get a repro, or perhaps a failing test?

**Comment by jtadmor** [comment]
Just want to clarify that this is not a bug that appears in certain circumstances, rather a request for changed behavior (I *thought* that it was old behavior, but looking through prior commits I may have been mistaken, and it was never the behavior).

I think the code is clear on what it expects to return:

```
export function whenMapDispatchToPropsIsMissing(mapDispatchToProps) {
  return (!mapDispatchToProps)
    ? wrapMapToPropsConstant(dispatch => ({ dispatch }))
    : undefined
}

export function whenMapDispatchToPropsIsObject(mapDispatchToProps) {
  return (mapDispatchToProps && typeof mapDispatchToProps === 'object')
    ? wrapMapToPropsConstant(dispatch => bindActionCreators(mapDispatchToProps, dispatch))
    : undefined
}
```
So, if you pass an object as the `mapDispatchToProps`, you get those keys bound to `dispatch`, but you do not get the `dispatch` prop itself. You can only get the `dispatch` prop if you pass nothing at all.

(The source for `bindActionCreators` is here: https://github.com/reactjs/redux/blob/master/src/bindActionCreators.js . As per its documentation, it returns an object with the same keys.)

**Comment by jtadmor** [comment]
Here is a bare-bones repro just to confirm that no dispatch is passed:
https://codepen.io/anon/pen/pdojLE?editors=0010

**Comment by markerikson** [comment]
Yes, this is the expected API.  Don't have time to dig back in the code history atm, but the behavior has "always" been that if you provide either form of a `mapDispatch` argument (either a function that accepts `dispatch`, or an object full of action creators), then `connect()` does _not_ pass in `dispatch` by default.  By passing in a `mapDispatch` argument, you've declared you're taking responsibility for what dispatch-related props should be passed into the component.  So, this did not change between 4.x and 5.x - this was the existing behavior, and we maintained it in the 5.x update.
