### ISSUE TITLE
Provide a dispatcher callback creator

### ISSUE THREAD

**Issue by gnapse** [reactjs/react-redux#821]
Not sure if this makes sense, but I've encountered this functionality quite often, and I keep providing it myself. It happens when you have a set of actions that you want to provide in a `mapDispatchToProps` function, and the callbacks' signatures map directly to the action creator signatures, and also what they do is just calling dispatch with whatever the corresponding action creator returns:

```javascript
const mapDispatchToProps = dispatch => ({
  myActionName: (a, b) => dispatch(actions.someAction(a, b)),
  extraActionName: (x, y, z) => dispatch(actions.otherAction(x, y, z)),
});
```

Imagine if we had a sort of `dispatcher` function, that would allow to abstract this out:

```javascript
const mapDispatchToProps = dispatch => ({
  myActionName: dispatcher(dispatch, actions.someAction),
  extraActionName: dispatcher(dispatch, actions.otherAction),
});
```

Or we could alternatively (or additionally) support dealing with a mapping of names to action creators):

```javascript
const mapDispatchToProps = dispatch => ({
  ...dispatchers(dispatch, {
    myActionName: actions.someAction,
    extraActionName: actions.otherAction,
  }),
});
```

Does this makes sense for `react-redux` to provide? Or would it fit better being its own independent package? Does it already exist as an independent package? If so, what's it. If not, what do you people think about the proposal? Perhaps the signature should be different, the way `dispatch` is passed to it, etc?

**Comment by timdorr** [comment]
I believe you're looking for the object shorthand syntax, which basically does this, but even more succinctly: https://github.com/reactjs/react-redux/blob/master/docs/api.md#inject-todos-and-specific-action-creators-addtodo-and-deletetodo-with-shorthand-syntax

**Comment by gnapse** [comment]
Wow, I didn't know this works that way. Sorry 😬 , and thanks for the info 👍
