### ISSUE TITLE
Cannot read property 'shape' of undefined

### ISSUE THREAD

**Issue by MihaiSandor** [reactjs/react-redux#822]
I use react-redux:  "react-redux": "5.0.6" and "react": "^16.0.0". Before compile I have this errors:
![screen shot 2017-11-05 at 11 26 01](https://user-images.githubusercontent.com/13609095/32413566-8f107352-c21c-11e7-8132-49547bafd495.png)
![screen shot 2017-11-05 at 11 26 11](https://user-images.githubusercontent.com/13609095/32413567-8f2c397a-c21c-11e7-85c5-96fc41803eb2.png)
![screen shot 2017-11-05 at 11 26 49](https://user-images.githubusercontent.com/13609095/32413568-8f473db0-c21c-11e7-815f-c1ddcde9a15a.png)
Do you have any idea how I fix this?

**Comment by BTMPL** [comment]
Can you check that you're not aliasing prop-types in webpack configuration?

**Comment by MihaiSandor** [comment]
I do not use prop-types in webpack.

**Comment by BTMPL** [comment]
Also, are you 100% sure it is complaining about this part? The requirejs syntax shows to be exporting `default` while the ES6 modules one ( from https://github.com/reactjs/react-redux/blob/cdf1369089c2a1616f3f21e72865a371aabcc7eb/src/utils/PropTypes.js ) does not use default.

**Comment by MihaiSandor** [comment]
Yes, I'm sure. If I remove from react-redux from package.json and delete node_modules and then npm install, works. With react-redux module doesn't work.

**Comment by timdorr** [comment]
You do not have the correct version of react-redux installed. The transpiled version looks like this: https://unpkg.com/react-redux@5.0.6/lib/utils/PropTypes.js That doesn't match the code you showed, so you either have the wrong version installed or a bad npm cache.

**Comment by augbog** [comment]
For other people that might run into this, just FYI if you have other packages that by chance have `react-redux` as a dependency, those may need to be updated as well (i.e. `redux-devtools`) in case you're wondering why `react-redux` seems to be throwing the error despite updating it. You can dig deeper into the console to see the specific package that is giving you the error.

**Comment by melloc01** [comment]
The exact same thing is happening to me on the current version. 5.0.6

Trying to update a React app from React@15 to React@16

![image](https://user-images.githubusercontent.com/4994258/37232207-cfc0c9da-23cc-11e8-9c2e-280f7c515ca8.png)

I do have the correct version of the lib.

I use "prop-types" as an external module served via browserify  and it works like a charm when outside react-redux.
Any clue of what could possibly be happening?
