### ISSUE TITLE
test cases coverge `coverage.Icov` is empty

### ISSUE THREAD

**Issue by ahmdsolmn** [reactjs/react-redux#828]
I tried cloning and running test coverage but `coverge.Icov` is empty.

Steps to reproduce:

1) clone and `npm install`
2) `npm run test:cov`

    All test cases succeed but coverage looks like this in the terminal
```
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```
and the `coverage.Icov` file is empty

**Comment by timdorr** [comment]
I haven't touched coverage in over a year. We should probably get it working again.

**Comment by ahmdsolmn** [comment]
if your run `npm run test:cov` returns `unknown`
but if you edit `/src/utils/shallowEqual.js` line 12 and add a semicolon at the end then rerun `npm run test:cov` `shallowEqual.js` shows in the coverage.
-----
alsot if you edit `src/utils/wrapActionCreators.js` line 1 and add a semicolon at the end  and then rerun `npm run test:cov` `wrapActionCreators.js` shows in the coverage.

Not sure what it means actually but maybe it will help you discover something

**Comment by IlyaRucavitcyn** [comment]
If nobody is working on that issue could I have a try during next few days? This issue seems a good one to start with:)

**Comment by timdorr** [comment]
Absolutely. It's a race to the PR! 😄

**Comment by IlyaRucavitcyn** [comment]
This days I've been working on the issue and for now I am stuck and perhaps need some help or advise. 
For now I have managed to change config of the nyc (istanbul cli) as shown on the picture below:
![screen shot 2017-12-12 at 11 21 18 am](https://user-images.githubusercontent.com/14336732/33874144-c3e8b858-df2e-11e7-998a-d8fb742c6b5a.png)
and all the src folder files appear to be in the report but with some kind of strange coverage results
![screen shot 2017-12-12 at 11 21 36 am](https://user-images.githubusercontent.com/14336732/33874189-ebb72b12-df2e-11e7-83d2-469f11aecbbb.png)

Current investigaton and nyc/babel/istanbul issues checking didn't point at the idea of what could have happened here.
Any ideas from anyone where to point the attention to?
Original changes can be found [in the fork](https://github.com/IlyaRucavitcyn/react-redux/tree/Test-coverage-fix)
