### ISSUE TITLE
Use connect on HOC compoennts

### ISSUE THREAD

**Issue by farskid** [reactjs/react-redux#837]
Is there any way one could use connect on HOCs and fetch a data from store?
```javascript
import React from 'react';
import {connect} from 'react-redux';

function withCurrentUser(Component) {
  return function(...props) {
    return <Component currentUser={/* Pass current user fetched from store here */} {...props} />
  }
}

function mapStateToProps(state) {
  return {
    currentUser: state.user
  }
}

export default connect(mapStateToProps)(withCurrentUser);
```

**Comment by markerikson** [comment]
Not written that way, since `connect` expects an actual component type as the second function's parameter.  However, this _should_ work:

```js
import {compose} from "redux";
import {connect} from "react-redux";

const composedHoc = compose(
    connect(mapStateToProps),
    withCurrentUser
);

export default composedHoc;

**Comment by farskid** [comment]
@markerikson That helped a lot! thanks 👍

**Comment by markerikson** [comment]
You can certainly flip the order of composition so that the `connect` wrapper is inside the `withCurrentUser` wrapper.  Also, you may want to try binding specific action creators so that they become known props, instead of skipping the `mapDispatch` argument.  See http://blog.isquaredsoftware.com/2016/10/idiomatic-redux-why-use-action-creators/ for some related thoughts.

**Comment by andrewmartin** [comment]
Random question, stumbled on this thread.

I'm getting `cannot call a class as a function` when I copy paste out your code here. Any idea why?

**Comment by foadk** [comment]
It's a bit old, but you could achieve this with a little modification on your code:
```javascript
import React from 'react';
import {connect} from 'react-redux';

function withCurrentUser(Component) {
  function yourFunction(...props) {
    return <Component currentUser={/* Pass current user fetched from store here */} {...props} />
  }
  return connect(mapStateToProps)(yourFunction);
}

function mapStateToProps(state) {
  return {
    currentUser: state.user
  }
}

export default withCurrentUser;
```

**Comment by BradyEdgar94** [comment]
Also a bit late but here is my solution:

`import React from 'react'
import { connect } from 'react-redux'

const Container = Comp => {
  const Wrapper = props => (
    class extends React.Component {
      render () {
        return <Comp {...this.props} />
      }
    }
  )

  return connect(mapStateToProps)(Wrapper());
}

function mapStateToProps ({ uuid }) {
  return { uuid }
}

export default Container
`

**Comment by BradyEdgar94** [comment]
Also a bit late but here is my solution:

`import React from 'react'
import { connect } from 'react-redux'

const Container = Comp => {
  const Wrapper = props => (
    class extends React.Component {
      render () {
        return <Comp {...this.props} />
      }
    }
  )

  return connect(mapStateToProps)(Wrapper());
}

function mapStateToProps ({ myValue }) {
  return { myValue }
}

export default Container`

**Comment by BradyEdgar94** [comment]
Also a bit late but here is my solution:
```javascript
import React from 'react'
import { connect } from 'react-redux'

const Container = Comp => {
  const Wrapper = props => (
    class extends React.Component {
      render () {
        return <Comp {...this.props} />
      }
    }
  )

  return connect(mapStateToProps)(Wrapper());
}

function mapStateToProps ({ myValue }) {
  return { myValue }
}

export default Container
```

**Comment by barisusanmaz** [comment]
@BradyEdgar94  @markerikson  All redux actions are passing into wrapped component when connect is used in hoc. May this behaviour be prevented?

**Comment by yuzhakovvv** [comment]
All suggested solutions didn't work for us. Check the error below. We figured out that the problem was in version `7.0.3`. Roll back to `5.0.1` fixed everything.

![image](https://user-images.githubusercontent.com/10023109/60662248-819d5200-9e64-11e9-8796-f77108b25d0f.png)

**Comment by markerikson** [comment]
@yuzhakovvv : if you're seeing that error, please make sure that you have _exactly_ matching versions of React and ReactDOM in your app, and that you're not pulling in any other versions of React anywhere.
