### ISSUE TITLE
Using a `props` property in connected components

### ISSUE THREAD

**Issue by claudiorodriguez** [reactjs/react-redux#838]
Hi everyone.

It seems that passing a `store` property into a connected component overrides the store from the context in typical cases (i.e. not specifying a `storeKey`, using standard `connect`, etc).
This seems to be expected as you mention here https://github.com/reactjs/react-redux/blob/master/docs/api.md#L8 but it has been a surprise as the error messages resulting from trying to use the property for something else, unawares, have been a bit hard to decipher

My question is - do you think it would be a good idea to check here
https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L122
somehow if the value of the property is an actual redux store, and throw a useful error if it's not?
Or perhaps using a different default `storeKey` like `__store`?

Cheers

**Comment by timdorr** [comment]
[We do this via propTypes](https://github.com/reactjs/react-redux/blob/775765ab2ce457ea0ffea05ba736ff0702d8a3ca/src/utils/PropTypes.js#L10-L14). You should get a warning related to that if you're passing in something that doesn't match the expected shape.
