### ISSUE TITLE
Providing action-creators through context

### ISSUE THREAD

**Issue by jEnbuska** [reactjs/react-redux#841]
Hi. I would like to make my Component files cleaner by getting rid of imports.
Actioncreators and actions could be provided using context.
Is there a technical reason why react-redux does not implement action creator providing through context?

This was ~ what is was thinking:
```
... index.jsx
const ActionProvider = createActionProvider({addTodo, ...etc});

const Root = () => (
    <Provider store={store}>
         <ActionProvider>
             <Todos/>
         </ActionProvider>
    </Provider>
)

... Todos.jsx
const Todos = (props, context) => [
    <AddTodo onSubmit={context.addTodo}/>,
   {props.todos.map(todo => <Todo todo={todo} ... />)}
]
/*define actions types in contexTypes*/
Todos.contextTypes = {
  addTodo: func, 
  ...
}
export default connect(...)(...);
``` 

This would also simplify the logic that has to be performed by the Component created by 'connect'

**Comment by markerikson** [comment]
A few reasons.  One is that that simply isn't part of the original API design.  Another is that `connect` is about being explicit, and only intended to pass values directly to the wrapped component.  After all, the entire state isn't just passed to every deeply nested component, or even every connected component - only the values and functions you return from your own `mapState` and `mapDispatch` functions.  

Beyond that, the React team advises that `context` be used sparingly, and when it is used, it should be hidden from app code.  A feature like this would involve a much tighter tie to `context`, which we're trying to avoid.  (In fact, the React team just introduced [a proposed new API that will eventually replace the existing `context` API](https://github.com/reactjs/rfcs/pull/2).)

**Comment by jEnbuska** [comment]
Ok. It will be interesting to see how context API will change.
I see the the point, of in being explicit, but I still think that how mapDispatchToProps is defined separately on every single Component, is gallons of explicit:y.
