### ISSUE TITLE
Hot reloading reducers is now explicit - example broken?

### ISSUE THREAD

**Issue by pldilley** [reactjs/react-redux#843]
The example on hot loading reducers is given here: https://github.com/reactjs/react-redux/releases/tag/v2.0.0

> if (module.hot) {
>     // Enable Webpack hot module replacement for reducers
>     module.hot.accept('../reducers', () => {
>       const nextRootReducer = require('../reducers/index');
>       store.replaceReducer(nextRootReducer);
>     });
>   }

For me, it didn't work until I changed the following:
`module.hot.accept('../reducers', () => {` **TO** `module.hot.accept('../reducers/index', () => {`

Is  the example on that page incorrect or am I missing something?

**Comment by timdorr** [comment]
Those are very old release notes. You should consult your build tool's docs for now to do this.

**Comment by pldilley** [comment]
P.S. For anyone else looking for a recent solution, this seems more on track: https://github.com/reactjs/redux/issues/1864

(I opted not to bother for now)
