### ISSUE TITLE
Misleading documentation for mapStateToProps Factory

### ISSUE THREAD

**Issue by ethankong113** [reactjs/react-redux#849]
In the doc for 'mapStateToProps', it writes

> The mapStateToProps function takes a single argument of the entire Redux store’s state and returns an object to be passed as props. It is often called a selector. Use reselect to efficiently compose selectors and compute derived data.

However, in the source code, it actually takes two arguments state and props:
https://github.com/reactjs/react-redux/blob/7bde889738b4e4716bcd5fa7acf75e2675798997/src/connect/wrapMapToProps.js#L57

I have tested in the console and it indeed takes a second argument as props. If the doc is wrong, I can submit a PR for that.

Also, what's the 'dependsOnOwnProps' flag for? If you don't pass props as the argument, the mapStateToProps doesn't recalculate if props updates?

**Comment by timdorr** [comment]
PRs are best for documentation updates. But I've updated it now to be a bit more clear.

And yes, that is an optimization that's done.
