### ISSUE TITLE
reserved word on store

### ISSUE THREAD

**Issue by tahaemin** [reactjs/react-redux#851]
Hello,

i am using react-redux with react 16. So i found a bug (i think). when i use 'segment' word in my store and fire an action to set this value, it terminates some functions (like setState). But i could not find any reserved words doc. 

here is my code: 

    import React, { Component } from 'react';
    import PropTypes from 'prop-types';

    class SSelect extends Component {
        state = {
            selectedName: '',
        }

        handleSelect = (id, name) => {
            this.setState({ isClicked: false, selectedName: name });
            this.props.handleSelect(this.props.segmentIndex, id); // redux action as prop
        }

        render() {
            console.log(this.state.selectedName);
            return (
                <div>
                    {
                        this.props.options.map(option => (
                            <div
                                key={option.id}
                                role="button"
                                onKeyPress={() => this.handleSelect(option.id, option.name)}
                                onClick={() => this.handleSelect(option.id, option.name)}
                                tabIndex="0"
                            >
                                {option.name}
                            </div>
                        ))
                    }
                </div>
            );
        }
    }

    SSelect.propTypes = {
        handleSelect: PropTypes.func.isRequired,
        options: PropTypes.array.isRequired,
        segmentIndex: PropTypes.number,
    };

    SSelect.defaultProps = {
        segmentIndex: 0,
    };

    export default SSelect;

and my package json: 

    "airbnb-prop-types": "^2.8.1",
    "autoprefixer": "7.1.6",
    "axios": "^0.17.1",
    "babel-core": "6.26.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.2",
    "babel-preset-react-app": "^3.1.0",
    "babel-runtime": "6.26.0",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "css-loader": "0.28.7",
    "dotenv": "4.0.0",
    "eslint": "4.10.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-react-app": "^2.0.1",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.4.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "immutable": "^3.8.2",
    "jest": "20.0.4",
    "lodash": "^4.17.4",
    "moment": "^2.20.1",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "prop-types": "^15.6.0",
    "raf": "^3.4.0",
    "react": "^16.2.0",
    "react-big-calendar": "^0.17.0",
    "react-dates": "^16.0.1",
    "react-dev-utils": "^4.2.1",
    "react-dom": "^16.2.0",
    "react-flip-move": "^2.9.17",
    "react-moment-proptypes": "^1.5.0",
    "react-notification-system": "^0.2.16",
    "react-onclickoutside": "^6.7.0",
    "react-portal": "^4.0.0",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "redux": "^3.7.2",
    "redux-batched-subscribe": "^0.1.6",
    "redux-saga": "^0.16.0",
    "redux-saga-devtools": "^0.1.2",
    "reselect": "^3.0.1",
    "style-loader": "0.19.0",
    "styled-components": "^2.2.3",
    "sw-precache-webpack-plugin": "0.11.4",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.4",
    "webpack-manifest-plugin": "1.3.2",
    "whatwg-fetch": "2.0.3"

**Comment by timdorr** [comment]
There are no reserved words on the store, other than what might come from JavaScript itself. But, as far as I know, `segment` isn't one of them. I would check with your middleware, which may be causing this.
