### ISSUE TITLE
Passing an object as the mapDispatchToProps argument of connect isn't working

### ISSUE THREAD

**Issue by bsonntag** [reactjs/react-redux#858]
Somehow passing an object as the `mapDispatchToProps` argument of `connect` isn't working. No actions are passed to the component's props. If instead I pass a function it works, but of course I have to wrap every action in a `dispatch` call.

What's strange is that I'm using the same version of `react-redux` (which is 5.0.6 by the way) on other projects and never had this issue.

**Comment by timdorr** [comment]
Without a repro, we don't have any way of diagnosing what's going on.

**Comment by bsonntag** [comment]
I'm sorry. It turns out my webpack isn't including my actions in the bundle for some reason (which means I was passing an object with values set as `undefined`).

**Comment by harvey56** [comment]
> I'm sorry. It turns out my webpack isn't including my actions in the bundle for some reason (which means I was passing an object with values set as `undefined`).

Hi @bsonntag May I know how you fixed that ? I seem to have the same issue.
