### ISSUE TITLE
New Feature: optionally pass an array or string instead of `mapStateToProps`

### ISSUE THREAD

**Issue by meChrisReed** [reactjs/react-redux#861]
Currently I am using `recompose` in every place where I am using `connect`. my `mapStateToProps` is essentially always:
``` javascript
connect(({apples, bananas, carrots, daikon}) => ({apples, bananas, carrots, daikon}))
```
I would like to get your thoughts on passing:
``` javascript
connect(["apples", "bananas", "carrots", "daikon"])
```
Is this an idea worth implementing?
Is there an existing way to cut this extra code out?
Am I just super off on this pattern?

**Comment by timdorr** [comment]
You can write a utility function to make that a little easier on your end. 
```js
function makeSelector(keys) {
  return function(state) {
    const selected = {}
    keys.forEach(k => selected[k] = state[k])
    return selected
  }
}
```

**Comment by meChrisReed** [comment]
Thanks @timdorr

**Comment by franciscop-invast** [comment]
You can also use [the package `only()`](https://www.npmjs.com/package/only):

```js
connect(obj => only(obj, 'apples bananas carrots daikon'))
```

**Comment by franciscop-invast** [comment]
I am using an even simpler way:

```js
connect(state => state)
```

I was going to make the same suggestion as @meChrisReed but found this issue saying basically that it's not wanted as a core functionality react-redux.

**Comment by markerikson** [comment]
@franciscop-invast : that's almost always a bad idea, because of performance.  Your component will now re-render _every_ time an action is dispatched and the store is updated, rather than just when the data this component actually needs has changed.

**Comment by franciscop-invast** [comment]
@markerikson woah, that is awesome to know, than you! I have a fairly thin state tree (but deep) so I haven't seen any difference so far, but I'll definitely keep it into mind for the future.
