### ISSUE TITLE
[PERF] - optimization - advancedConnect

### ISSUE THREAD

**Issue by michaelBenin** [reactjs/react-redux#863]
We just did some testing with clinic - here's the flame graph.

![screen shot 2018-01-26 at 12 46 17 pm](https://user-images.githubusercontent.com/521971/35453147-1f762b52-0297-11e8-9b45-bf9c773dda5f.png)

Feel free to close - thought I'd share the results here.

**Comment by timdorr** [comment]
I'm not sure what I'm looking at here. Also, there is no code to correlate. Closing due to lack of context.
