### ISSUE TITLE
mapDispatchToProps doesn't map dispatch

### ISSUE THREAD

**Issue by TheDutchCoder** [reactjs/react-redux#866]
The following example doesn't seem to work correctly: https://redux.js.org/docs/recipes/ComputingDerivedData.html#motivation-for-memoized-selectors

The console complains: `TypeError: dispatch is not a function`

It works fine when calling `this.props.dispatch(addCameraPhotos(payload))`, but not with `this.props.addCameraPhotos(payload)`

Here's the code:
```js
import React from 'react'
import PropTypes from 'prop-types';
import { connect } from 'react-redux'
import { Text } from 'react-native'
import { addCameraPhotos } from '../../redux/actions/index';

const mapDispatchToProps = (dispatch) => {
  return {
    addCameraPhotos: (photos) => {
      dispatch(addCameraPhotos(photos)) // This is the `dispatch` that produces the error
    }
  }
}

class PhotoPicker extends React.Component {
  
  componentDidMount() {
    addCameraPhotos([{ foo: 'bar' }])
  }

  render() {
    return (
      <Text>Test</Text>
    )
  }
}

export default connect(mapDispatchToProps)(PhotoPicker)
```

**Comment by timdorr** [comment]
You're referencing the wrong function in your component:
```js
  componentDidMount() {
    this.props.addCameraPhotos([{ foo: 'bar' }])
  }
```

**Comment by TheDutchCoder** [comment]
But the docs I referenced don't use `this.props`, why is that?
Is the example wrong, or is it some sort of different case?

**Comment by timdorr** [comment]
The page you linked doesn't have any React components on it. I think you're mis-reading it.
