### ISSUE TITLE
possibly unnecessary dependency to lodash

### ISSUE THREAD

**Issue by OlafMerkert** [reactjs/react-redux#867]
The only usage of lodash is in verifyPlainObject.js imports `isPlainObject`.

However redux itself also includes an `isPlainObject` function. Using this would allow to remove the dependency on lodash.

**Comment by timdorr** [comment]
That function isn't exported at the moment, as we're waiting on some upstream lodash changes that will let us bring it back in with minimal bundle size impact.

But copying it over shouldn't be a big deal. There are some edge cases it doesn't handle, but it should be fine for our purposes here.

**Comment by OlafMerkert** [comment]
Ah ok. I was just wondering why this was handled differently in redux and react-redux.

**Comment by a-x-** [comment]
lodash/isPlainObject might be too slow because it does extra checks.
Are you sure, you need all of lodash/isPlainObject checks?

Redux issue: https://github.com/reactjs/redux/pull/2599
