### ISSUE TITLE
mapStateToProps - camelCase Object Key which Contains Object Transformed Into a Function

### ISSUE THREAD

**Issue by wisn** [reactjs/react-redux#869]
Here is an example of this issue. Suppose we have two objects looks like below.

```javascript
const mapStateToProps = state => ({
  userId: state.auth.user.id,

  conversations: {
    data: state.messageThread.data,
    error: state.messageThread.error,
    message: state.messageThread.message,
    fetching: state.messageThread.fetching,
  },

  createDraft: {
    data: state.messageCompose.data,
    error: state.messageCompose.error,
    message: state.messageCompose.message,
    fetching: state.messageCompose.fetching,
  },
})
```

- `userId` using camelCase and the value is a positive integer. Working fine.
- `conversations` doesn't use camelCase and the value is an object. Working fine.
- `createDraft` using camelCase and the value is an object. When using `componentWillReceiveProps(nextProps)` method, calling `nextProps.createDraft` will return a function like below.

```javascript
function createDraft(...) {
  return dispatch(...);
}
```

The another two are working fine. If we rename `createDraft` to `createdraft`, it will working correctly and the return value is an object just like in the `mapStateToProps`.

**Comment by timdorr** [comment]
Something else is going on in that case. Check your reducers. Object keys are case sensitive.

**Comment by wisn** [comment]
What was that? There is no problem with my reducers. I'm just asking why using camelCase with objects in it transformed to function? I've tested it several cases as well.

**Comment by jimbolla** [comment]
Are you sure you don't have createDraft in your mapDispatchToProps?

**Comment by wisn** [comment]
I've one.

**Comment by timdorr** [comment]
Then that's your problem. They're all getting mapped to this.props, and your action dispatchers are overwriting your state props.

**Comment by wisn** [comment]
Ah, I got it now. Thanks a lot!
