### ISSUE TITLE
Incorrect require() example in v2.0.0 release notes

### ISSUE THREAD

**Issue by emlun** [reactjs/react-redux#871]
Hi! Thanks for making this great tool!

The upgrade instructions in the [v2.0.0 release notes][rn] (which a console error message links to) give the following **After** code example:

```javascript
import { createStore } from 'redux';
import rootReducer from '../reducers/index';

export default function configureStore(initialState) {
  const store = createStore(rootReducer, initialState);

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('../reducers', () => {
      const nextRootReducer = require('../reducers/index');
      store.replaceReducer(nextRootReducer);
    });
  }

  return store;
}
```

However, this makes HMR break because we are first importing `../reducers/index` as an ES6 module and later using `require()`. In the former case the `rootReducer` takes the value of the default export, but in the latter case the `nextRootReducer` takes the value of an object whose `default` property is the default export. So the proper usage of the `require()` result in this example is

```javascript
const nextRootReducer = require('../reducers/index').default;
```

This took me a while of head-scratching to pin down. 😃

[rn]: https://github.com/reactjs/react-redux/releases/tag/v2.0.0

**Comment by timdorr** [comment]
This would be a side effect of using Babel. As it's written, it will work according to spec-compliant environments.

**Comment by emlun** [comment]
Oh, I see. Sorry about that.
