### ISSUE TITLE
Allow setting custom areMergedPropsEqual function globally

### ISSUE THREAD

**Issue by CamJN** [reactjs/react-redux#873]
Hi all, I'd like to ask if it would be possible to set a custom `areMergedPropsEqual` function in one place instead of on each wrapped component.

The default `areMergedPropsEqual` function does a shallow compare according to the docs, and I need to use my custom deep comparison function (I could go into why but it'll get ranty and I don't want to be an ass). It'd be really nice to be able to globally set the `areMergedPropsEqual` function to be used for all connected components, instead of having to set it every time, since I know I'll always need to use my version.

**Comment by timdorr** [comment]
You can wrap your own `connect` function to do this:
```js
import { connect as origConnect } from 'react-redux'
import customAreStatesEqual from './customAreStatesEqual'
export const connect = (mSTP, mDTP, mP, options) => origConnect(mSTP, mDTP, mP, { ...options, areStatesEqual: customAreStatesEqual })
```
