### ISSUE TITLE
connectAdvanced: allow WrappedComponents to be a strict function: extraProps => react element

### ISSUE THREAD

**Issue by aappddeevv** [reactjs/react-redux#874]
connectAdvanced makes a final call in its Connect proxy class to `createElement` which creates the WrappedComponent.  The issue is that if we can allow WrappedComponent to be a function, we could allow 3rd party libs written in other transpiled languages (like reasonml or scala.js) to integrate more seamlessly with react-redux. react-redux infrastructure to help reduce renders when state changes do not affect a specific component would be hard to replicate otherwise. Instead, by allowing a different element creation method, we can open this up a bit.

Right now there is an invariant check to weed out functions but apparently there is only two places where being a function matters--in the places to derive the "Connect" proxy component's name.

This may need some more thinking time.

**Comment by timdorr** [comment]
I'm not sure I understand. The invariant check is specifically for if WrapperComponent is a function. This works just fine with Reason and other transpiled languages.
