### ISSUE TITLE
can't access children from <Connect(Component)>

### ISSUE THREAD

**Issue by mrigdon** [reactjs/react-redux#875]
Calling `React.Children.only()` on a `Connect(Component)` generated by the react-redux `connect` function does not expose its children.

Here's a screenshot of calling `React.Children.only(component)` on a plain React component:

![image](https://user-images.githubusercontent.com/7377110/36177483-a5dd2cfe-10ca-11e8-9af2-ba624eae81d3.png)

And here's one of calling `React.Children.only(component)` on a `Connect(Component)` generated by the connect function:

![image](https://user-images.githubusercontent.com/7377110/36177564-fa8858d2-10ca-11e8-8010-303dddc29364.png)

I need access to the `Connect` children because I have a component wrapper that injects a prop into deeply nested children of a certain type.

Does this make sense?

**Comment by gaearon** [comment]
That's not how React works. Components *rendered* by something are the implementation detail. You can manipulate children that you *create* in *your* component, but you can't use it as an "introspection" tool to manipulate the output of other components.

**Comment by mrigdon** [comment]
Maybe I should be more specific about my use case, and maybe you can point me in the right direction.

I'm trying to replace this:

```
<TextField readOnly={myReadOnlyFlag} />
<TextField readOnly={myReadOnlyFlag} />
<TextField readOnly={myReadOnlyFlag} />
```

with this:

```
<Authorize readOnly={myReadOnlyFlag}>
  // the following three components are now readOnly
  <TextField />
  <TextField />
  <TextField />
</Authorize>
```
Is there a more _React_ way of doing this than injecting a prop?

**Comment by gaearon** [comment]
I don't understand what "replace" means in this context. Can you show a fuller example?

**Comment by mrigdon** [comment]
I'm trying to DRY the code out by passing the readOnly flag to an HOC once rather than pass it to each TextField component.

Consider a complex form:

```
<form>
    <column>
      <TextField readOnly={readOnly} />
      <TextArea readOnly={readOnly} />

      <grid>
        <column>
          <TextField readOnly={readOnly} />
          <TextField readOnly={readOnly} />
        </column>
      </grid>

      <grid>
        <column>
          <TextArea readOnly={readOnly} />
        </column>
      </grid>
    </column>
  </form>
```
It's kinda lame to have to pass readOnly to each form field. I'd rather have some logic where I can just do this:

```
<Authorize readOnly={readOnly}>
    <form>
      <column>
        <TextField />
        <TextArea />

        <grid>
          <column>
            <TextField />
            <TextField />
          </column>
        </grid>

        <grid>
          <column>
            <TextArea />
          </column>
        </grid>
      </column>
    </form>
  </Authorize>
```
And all those form fields will automatically be readOnly.

**Comment by gaearon** [comment]
I don't see a HOC here. Where is the HOC?

**Comment by gaearon** [comment]
(That said, to be honest, I would advise against what you're trying to do. Passing it explicitly and manually *is* the "React way" of doing it. It's much easier to understand what's going on this way.)

**Comment by mrigdon** [comment]
But if you were to pretend to agree with the way I'm trying to do it, does there exist a way to do it? I guess I'm still confused why the `children` prop of a `<Connect(Component)>` comes back as `undefined`.

**Comment by gaearon** [comment]
@mrigdon I'm confused by three things: (1) where do you see a HOC, (2) where is `connect()` there, (3) where do you manipulate the children. That's why I asked for a full code sample.

**Comment by gaearon** [comment]
Here's why the API you propose probably isn't a great idea.

```js
<Authorize readOnly={readOnly}>
    <form>
        <TextField />
        <TextArea />
    </form>
</Authorize>
```

Okay, say this works. Then somebody extracts a component:

```js
function MyForm() {
  return (
    <form>
        <TextField />
        <TextArea />
    </form>
  );
}

<Authorize readOnly={readOnly}>
  <MyForm />
</Authorize>
```

Now the code is broken because there is no way `Authorize` could "look into" what `MyForm` rendered to.

If it helps the explanation, *React elements are rendered lazily rather than eagerly*. So by the time `Authorize` renders, it doesn't actually "know" what `MyForm` renders to (and won't know because React isolates them).

**Comment by mrigdon** [comment]
Oh I see. That last sentence explains it. Theoretically, if the components were not rendered "lazily", you could do this:

```
function injectReadOnly(children) {
  return React.Children.map(children, child => {
    const { props, type } = child;

    let newChild = child;

    // if child is a form field that accepts readOnly (e.g. TextField)
    if (type !== undefined && type.name !== 'TextField') {
      const { readOnly } = props;

      newChild = React.cloneElement(
        child,
        { readOnly: true }
      );
    }

    // if this component has any children, injectReadOnly on them too
    if (props !== undefined && props.children !== undefined) {
      return React.cloneElement(
        newChild,
        { children: injectReadOnly(props.children) }
      );
    }

    return newChild;
  });
}

/**
 * React component wrapper to authorize component(s).
 * @param {Object} props - The React props
 * @param {boolean} props.canUpdate - If false, it makes subcomponents readOnly.
 * @param {boolean} props.canView - If false, it renders nothing.
 * @param {Array} props.children - The React immediate children
 * @returns {Array} - An array of the authorized React children
 */
export default function Authorize({
  canUpdate = true,
  canView = true,
  children,
}) {
  if (!canView) return null;

  if (!canUpdate) {
    return injectReadOnly(children);
  }

  return children;
}
```

**Comment by gaearon** [comment]
Yeah. It's rather intentional that you can't do this though because otherwise many debugging benefits of React go out of the window. There'd be no guarantees that after the component has rendered, something else wouldn't mess with its output.

**Comment by gaearon** [comment]
The new context API coming in 16.3 might be a good solution to your problem.
https://github.com/reactjs/rfcs/blob/master/text/0002-new-version-of-context.md

**Comment by mrigdon** [comment]
Got it. Well I'll stick to the "React way" for now then. Thanks for taking the time to help me out, and thanks for an awesome library.

**Comment by mrigdon** [comment]
Just wanted to follow up on this--the context API in 16.3 does in fact support what I was trying to do.

**Comment by noway** [comment]
I found this thread because I'm trying to implement a custom module in react native. For anyone trying to access props.children of a component in react native, try the native methods `- (void)insertReactSubview:(UIView *)subview atIndex:(NSInteger)atIndex` and `- (void)removeReactSubview:(UIView *)subview` instead of iterating react elements in javascript
