### ISSUE TITLE
Integrate DefinitelyTyped TypeScript types into the project

### ISSUE THREAD

**Issue by severen** [reactjs/react-redux#880]
Redux itself currently ships with TypeScript types bundled, yet this does not. It seems like it would make sense to me to also ship types in this repository, especially as react-redux and redux are tightly integrated.

I ended up thinking about this due to the fact that using @types/react-redux with the latest beta releases of Redux (which have overhauled type definitions that fix an issue I was having) requires me going into the node_modules folder and manually deleting its dependency on Redux 3.x so that everything works how it should. If this project included the definitions like Redux does, both projects could then have matching beta/@next releases, which would fix this issue.

**Comment by stereobooster** [comment]
Maybe make `redux` a peerDependency?

**Comment by ericanderson** [comment]
Could you not just map in your own types for a pre release?

**Comment by aikoven** [comment]
See discussion in https://github.com/reactjs/react-redux/pull/815

**Comment by stereobooster** [comment]
@aikoven what about making `redux` a peerDependency? So I can use latest `redux` with `react-redux`

**Comment by aikoven** [comment]
@stereobooster Isn't it a `peer` already? [package.json#L50](https://github.com/reactjs/react-redux/blob/v5.0.7/package.json#L50)

**Comment by stereobooster** [comment]
Yes indeed, then my issue is due to some other cause. Thank you
