### ISSUE TITLE
Discussion: Is adding async method in a Reducer is an anti pattern?

### ISSUE THREAD

**Issue by alanlanglois** [reactjs/react-redux#896]
I'm pretty new to the whole react-native / redux world, maybe this question will sound dumb :)

I know that for API Call or stuff like that the convention is to do that via middleware but is it always necessary (it adds a lot of boilerplate).

I succefully added async methode in a reducer to manage device API connection such as In-App or Local Notifications, but I wonder if it is ok to handling it this way.

For instance in my reducer there is this methode:

```
function initInApp(state, itemSkus){
  init(state, itemSkus);
  return {
    ...state,
    itemSkus: itemSkus,
  }
}
```
And this one which manage the async part:

```
async function init(state, itemSkus){
  try {
    if( !state.isInit ){
      const prepare = await RNIap.prepareAndroid();
      return{
        ...state,
        isInit: true,
        errorCode: false,
      }
    }
    else {
       return ...state;
    }
  } catch (errorCode) {
    return{
      ...state,
      isInit: false,
      errorCode: errorCode,
      itemSkus: itemSkus
    }
  }
}
```
Maybe it's not efficient in terms of performances or hard to maintain. What are your thought on it?

Thanks :)

**Comment by timdorr** [comment]
Your reducers have to be pure functions. If you want to handle async, your do that in a middleware.
