### ISSUE TITLE
When using Context API, store is undefined unless I specify it in each connected component's `contextTypes`

### ISSUE THREAD

**Issue by Jahans3** [reactjs/react-redux#899]
Hi, thanks for the great work on this library, it's served me very well for a long time! Unfortunately I think I have encountered an error (or I am using the Context API wrong).

### My problem:

I am rendering multiple React apps on a single domain, a lot of these apps do not require Redux but I do have some information that I need to make available to all components. To achieve this I created* a Provider component (*= copied this library's Provider 😎).

VersionProvider.js:
```
// @flow
import { Children, Component } from 'react'
import PropTypes from 'prop-types'

type Props = {
  version: string
}

export function createVersionProvider (contextKey: string = '__IYA_VERSION__') {
  return class VersionProvider extends Component<Props> {
    static childContextTypes = {
      [contextKey]: PropTypes.string.isRequired
    }

    getChildContext () {
      return { [contextKey]: this.props.version }
    }

    render () {
      return Children.only(this.props.children)
    }
  }
}

export default createVersionProvider()
```

However this causes the following error:
```
Error: Could not find "store" in either the context or props of "Connect(r)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(r)".
```

I am able to get around this issue by adding `store` to my connected component's `contextTypes`:
```
static contextTypes = {
    __IYA_VERSION__: PropTypes.string.isRequired,
    store: PropTypes.object
  }
```

**Comment by timdorr** [comment]
That's how the context API works in React <= 16.2: https://reactjs.org/docs/context.html

> If contextTypes is not defined, then context will be an empty object.

**Comment by Jahans3** [comment]
@timdorr I would never normally define `contextTypes` inside a connected component. Why would adding my own property to the context mean I have to add store to `contextTypes`?

I would have thought that by the stage I am trying to access my custom context property that the store should just be props?

Sorry, I know the above are more related to context API itself
