### ISSUE TITLE
peer invalid: react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 using React Native 0.54

### ISSUE THREAD

**Issue by NachtRitter** [reactjs/react-redux#903]
Can not generate npm-shrinkwrap.json file.

Environment:
OS: Ubuntu 14.04.5
Node.js: 6.13.1
npm: 3.10.10
React Native: 0.54.2
**React: 16.3.0-alpha.1**
react-redux: 5.0.7

**Comment by timdorr** [comment]
Upgrade your npm version. The `^16.0.0-0` will cover this.

**Comment by NachtRitter** [comment]
@timdorr yeap with node 8.x and npm 5.x everything is fine and package-lock.json is generated.
But for building mobile app I use Visual studio app center and their environment has only node 6.x and npm 3.x
So I can not generate npm-shrinkwrap.json file for locking my dependencies with npm 3.x

**Comment by ThaJay** [comment]
```
$ npm -v
6.0.0
$ node -v
v9.11.1
$ npm list react-native
└── react-native@0.55.0 
```
```npm WARN react-redux@5.0.7 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.
```

**Comment by lvdesign** [comment]
Hello,
Since I upgrade json-server to 0.14.0, the connection is failling  (react-redux": "5.0.7")

Some advice ?

Thanks 

Cordially
osx 10.13.4, yarn : 1.7.0, npm : 6.1.0, node : v8.11.1
 "jest-expo": "~27.0.0",
 "react-native-scripts": "1.14.0",
 "react-test-renderer": "16.3.1"
