### ISSUE TITLE
Uncaught ReferenceError: g is not defined

### ISSUE THREAD

**Issue by abhishekwadhawan** [reactjs/react-redux#904]
while updating version from 4.4.8 to 4.4.9, there is uncaught reference error saying g is not defined. Please fix.

**Comment by timdorr** [comment]
This isn't enough information to go on. Can you give a stack trace of some sort?

**Comment by abhishek2409** [comment]
Actually, I don't have enough information on this because in one of my project it is upgraded and suddenly this Uncaught error come but when I've downgraded to the previous version it works.

**Comment by enoh-barbu** [comment]
run the app in dev mode, that could lead to an indication of what that **g** is. Production code is minified and all let/const declarations are renamed.

**Comment by abhishekwadhawan** [comment]
I couldn't generate stack trace of error, so I'm closing this issues for now.

**Comment by crisanlucid** [comment]
the error is still occurred, in the dev environment is not possible but in production (where is the min file) i got the same error: Solution is to downgrade to : react-redux: 4.4.8

```javascript
app.public.acd6b31728a4d902021b.js:47 Uncaught ReferenceError: g is not defined
    at a (react-redux.min.js?5a76:1)
    at a (react-redux.min.js?5a76:1)
    at react-redux.min.js?5a76:1
```
