### ISSUE TITLE
Is this guaranteed to be bound to the props object in a mapDispatchToProps object's functions?

### ISSUE THREAD

**Issue by stefanoborini** [reactjs/react-redux#910]
As from title. If I have a mapDispatchToProps defined as follows

```
const mapDispatchToProps = dispatch => ({
  onToggle: function() {
     console.log(this);
  }
});
```
is `this` guaranteed to be bound to the props object of the component? There's no documentation about it, at least that I can find. The need is that I have to check the current redux state to decide if to perform some operation inside that onToggle function, and it is my understanding that I can't access the store from there.

**Comment by timdorr** [comment]
Nope, we don't bind those functions. Check out mergeProps.

**Comment by stefanoborini** [comment]
@timdorr this is strange, because I actually have used it and it results to be bound to the props object, so I am a bit confused where this takes place.

**Comment by timdorr** [comment]
I wouldn't be trying to access props from your action creator. Make them pure functions and simply pass in the props when calling the action creator:
```js
connect(mSTP, { addTodo })(MyComponent)

// Somewhere inside MyComponent...
this.props.addTodo(this.props.inputText)
```

**Comment by stefanoborini** [comment]
@timdorr ok, but this means that my component is now required to perform an ajax request, something that currently lives in the onToggle function outside of the component. The problem is that this ajax request depends on the toggled/untoggled status. 

But I see that I could probably change the callback prop and have the decision making in the component, and call the external callback that does the ajax call.
