### ISSUE TITLE
Using connect in other HOC's

### ISSUE THREAD

**Issue by btmdave** [reactjs/react-redux#911]
I'm trying to use `connect` in other high order components, for example:

```
function withAuth (WrappedComponent) {
  class Auth extends React.Component {
    getRequestToken() {
     
    }
    render () {
      return (
        <WrappedComponent getRequestToken={this.getRequestToken} {...this.props} />
      )
    }
  }

  function mapStateToProps (state) {
    return {
      /* .. */
    }
  }

  function mapDispatchToProps (dispatch) {
    return {
      /* .. */
    }
  }

  return connect(mapStateToProps, mapDispatchToProps)(Auth)
}

export default withAuth
```

I'm receiving errors that `Could not find "store" in either the context or props`.  Any suggestions on how to do this?

**Comment by markerikson** [comment]
Are you actually wrapping your component tree in `<Provider store={store}>` ?

**Comment by btmdave** [comment]
@markerikson Yeah, I have that at the top level.   Using redux throughout the app, just for some reason with this not getting the store.

**Comment by btmdave** [comment]
Ok, I'm going to close this.  This was due to a 3rd party library that this was being wrapped in, it works fine outside of this.  Thanks for the help.
