### ISSUE TITLE
Remove verifyPlainObject?

### ISSUE THREAD

**Issue by anuraaga** [reactjs/react-redux#912]
I was wondering, what is the motivation behind requiring plain objects in props? Recent versions of `immutablejs` have `Record` types, which have similar semantics to objects (property read access) and it'd be nice to be able to use them directly as props instead of converting them to objects.

**Comment by timdorr** [comment]
It's not checking the values of the props, but the entire props object that's returned. You can have props that are Record types, but the object that contains those props must be plain.

**Comment by anuraaga** [comment]
Sorry the question should have been specifically about `mergeProps` - is there a reason for the wrapper to also check plainness? The default merge function relies on the others returning plain objects, but post-merge the props are just passes to React, which doesn't place any restriction on its props. Specifically this code seems unnecessary but is there still a reason for it?

https://github.com/reactjs/react-redux/blob/master/src/connect/mergeProps.js#L26

**Comment by timdorr** [comment]
It's a sanity check to make sure mergeProps isn't returning something other than a plain object. Trying to do `<WrappedComponent {...mergeProps()}/> with a non-object return would cause confusing errors. It's a dev-only check for that reason.
