### ISSUE TITLE
Documentation request: Is there any reason that you can't memoize the entire mapStateToProps return value?

### ISSUE THREAD

**Issue by waynebloss** [reactjs/react-redux#917]
I am trying to figure out if there will be any difference in my program if I memoize the entire `mapStateToProps` return value. Looking at the code for [connect](https://github.com/reactjs/react-redux/blob/f892ec00d7e92ff7afb21498276472f0e3b000c5/src/connect/connect.js#L56) I can see that `shallowEqual` is being used for `areMergedPropsEqual` by default.

Therefore, I think the answer is: **No.** By default, there will be no performance gain or penalty for doing this. A shallow equality comparison will always run unless I use `createConnect` to create a custom connect function. I'm guessing that you could get a very slight performance increase if you used something like `strictOrShallowEqual` for the `areMergedPropsEqual` check.

To be clear, I'm not looking for performance - I just want to make sure that I don't break anything by doing so where necessary.

## Examples

Most examples that I see use reselect to memoize individual properties, like so:

```js
const mapStateToProps = (state) => {
  return {
    todos: getVisibleTodos(state) // A selector that memoizes.
  };
};
```

However, I have a need to do something like this:

```js
const mapStateToProps = (state) => {
  return getPropsWithTodos(state); // Also a selector that memoizes.
};
```

Both of the above will return the same object shape (`{ todos: {} }`), but the `getPropsWithTodos` selector will cache the entire props object whereas the `getVisibleTodos` selector will only cache the `todos` prop.

_NOTE: In all likelihood, the `getPropsWithTodos` selector itself will just be passed as `mapStateToProps`, instead of nesting the calls...this example is for discussion only._

**Comment by markerikson** [comment]
Yeah, it's a shallow equality check, so it shouldn't make any difference whether you return the exact same object reference from `mapState` or not.
