### ISSUE TITLE
code comments refer to functions not in the repository

### ISSUE THREAD

**Issue by tonyhallett** [reactjs/react-redux#921]
[wrapMapToProps](https://github.com/reactjs/react-redux/blob/master/src/connect/wrapMapToProps.js) 
// dependsOnOwnProps is used by **createMapToPropsProxy** to determine whether to pass props as args
// to the mapToProps function being wrapped. It is also used by **makePurePropsSelector** to determine
// whether mapToProps needs to be invoked when props have changed.

**Comment by timdorr** [comment]
Those did exist, but were refactored out. A code comment is just a lie waiting to happen. 

A PR to remove or update those comments would be appreciated.
