### ISSUE TITLE
warning  deapricated componentWillReceiveProps and componentWillUpdate

### ISSUE THREAD

**Issue by fereshtehaboohamzeh** [reactjs/react-redux#923]
warning in react-native v54 and react-redux v5.0.6

**Comment by markerikson** [comment]
Duplicate of #915 - please upgrade to 5.0.7 to fix this.

**Comment by gaearon** [comment]
I don’t think it’s related. This is probably about https://github.com/facebook/react-native/issues/18175#comment-379253428.

React Native 0.55.2 will fix this b

**Comment by markerikson** [comment]
Ah, okay.  Good to know.
