### ISSUE TITLE
using new context API

### ISSUE THREAD

**Issue by ankibalyan** [reactjs/react-redux#927]
**Do you want to request a *feature* or report a *bug*?**  
feature

**What is the current behavior?**
If using `react > v16.3`, would like to use react-redux with new context  api, rather than old depricated ones.

**Comment by TrySound** [comment]
There is pull request.

https://github.com/reactjs/react-redux/pull/898

Also old one is not deprecated yet.

**Comment by ankibalyan** [comment]
Oh alright! I haven't checked the pull request.

**Comment by markerikson** [comment]
Note that that's an internal implementation detail, and shouldn't actually make a difference to the end users.
