### ISSUE TITLE
Upgrade to redux 4

### ISSUE THREAD

**Issue by bartvde** [reactjs/react-redux#932]
Are there any plans to update to redux 4? If so, is there a timeline?

package.json lists ^3.0.0 currently

**Comment by Delapouite** [comment]
Hello. What about this PR:
https://github.com/reactjs/react-redux/commit/8abdf934f574a1873c87417a5e41c7a80e5121c3 ?

**Comment by bartvde** [comment]
ah sorry you are right, already done. Thanks.
