### ISSUE TITLE
No Redux state passed to getDerivedStateFromProps on initial render of connected components

### ISSUE THREAD

**Issue by danpantry** [reactjs/react-redux#939]
On the initial render of a React 16.3 component using `getDerivedStateFromProps` which is connected to a redux store, `react-redux` will not pass either `dispatch` or any props from the `mapStateToProps` or functions from `mapDispatchToProps` functions to the child component.

This can cause unexpected behaviour in connected components, as they may reasonably expect that Redux always provides at least the default state.

The below test case demonstrates the issue; the test will fail with the versions listed at the bottom of the issue report.

Expected behaviour would be that the component would always be rendered with the props from `mapStateToProps`/`mapDispatchToProps`.

The upshot of this is that a user of `react-redux` would have to check or provide defaults for all connected properties within their connected component, which is surprising and a poor experience.

Using the react lifecycles compat polyfill substitutes one issue for another, as that polyfill will cause the connected component to throw an error for mixing gDSFP and cWM.

## Test Case
````js
import React from "react";
import { Provider, connect } from "react-redux";
import { createStore } from "redux";
import { identity } from "ramda";
import { mount } from "enzyme";

class React163Component extends React.Component {
  static getDerivedStateFromProps(nextProps) {
    // nextProps will be an empty object on the initial pass.
    if (nextProps.dispatch === undefined) {
      throw new Error("redux props were absent!");
    }

    return null;
  }

  render() {
    return <div />;
  }
}

test("react-redux should not pass absent redux props to component", () => {
  const initialState = {};
  const store = createStore(identity, initialState);
  const Connected = connect(() => ({})))(React163Component);

  expect(() => {
    mount(
      <Provider store={store}>
        <Connected />
      </Provider>
    );
  }).not.toThrow("redux props were absent!");
});
````

## Versions

````
react-redux: 5.0.6
react: 16.3.2
redux: 3.7.2
jest: 22.1.4
enzyme: 3.1.0
````

**Comment by gaearon** [comment]
Update react-redux to 5.0.7 and try again?

**Comment by gaearon** [comment]
That's as expected, you need to define `state` if you use `getDerivedStateFromProps`.

**Comment by danpantry** [comment]
@gaearon Ah! I couldn't find that in documentation anywhere, but I suppose that makes sense
